# Bibliotecas

In [1]:
#!pip install -r requirements_all.txt

In [2]:
#!pip install datasets

In [3]:
import numpy as np
import os
from datetime import datetime

import datasets
import evaluate

import torch
import torch.nn as nn

from transformers import Trainer, TrainerCallback, TrainingArguments, EarlyStoppingCallback
from transformers import AutoTokenizer, BertConfig, BertModel, BertPreTrainedModel

/home/guilhermelima/msc/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Carregar os conjunto de dados pré-processado

In [4]:
#MAX_LENGTH = 512
NUM_TRAIN_EPOCHS = 10

timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

RESULTS_DIRECTORY = './results/experiment_{}'.format(timestamp)

LOGGING_DIRECTORY = './logs/experiement_{}'.format(timestamp)

RESULTS_DIRECTORY, LOGGING_DIRECTORY

('./results/experiment_2026-06-15_09-26-18',
 './logs/experiement_2026-06-15_09-26-18')

In [5]:
#XPOS_LABELS = ['DET', 'NOUN', 'ADP', 'ADJ', 'VERB', 'CONJ', 'ADV', 'AUX', '.', 'PNOUN', 'NUM', 'PRON', 'PRT', 'ADPPRON', 'X']

#DEPREL_LABELS = ['det', 'attr', 'adpmod', 'amod', 'adpobj', 'ROOT', 'mark', 'nsubj', 'advmod', 'aux', 'adp', 'csubj', 'cc', 'conj', 'p', 'compmod', 'appos', 'acomp', 'num', 'nsubjpass', 'auxpass', 'dobj', 'poss', 'partmod', 'xcomp', 'ccomp', 'adpcomp', 'advcl', 'rcmod', 'nmod', 'neg', 'mwe', 'dep', 'parataxis', 'iobj', 'prt', 'infmod', 'csubjpass']

#UPOS_LABELS = ['DET', 'NOUN', 'ADP', 'ADJ', 'VERB', 'CONJ', 'ADV', '.', 'NUM', 'PRON', 'PRT', 'X']

UPOS_LABELS = ['DET', 'NOUN', 'VERB', 'PUNCT', 'SCONJ', 'ADP', 'ADJ', 'CCONJ', 'ADV', 'PROPN', 'AUX', 'NUM', 'PRON', 'SYM', 'X', 'INTJ']
DEPREL_LABELS = ['det', 'nsubj', 'root', 'obj', 'xcomp', 'punct', 'mark', 'advcl', 'case', 'obl', 'amod', 'conj', 'cc', 'nmod', 'advmod', 'flat:name', 'ccomp', 'cop', 'acl', 'nummod', 'acl:relcl', 'ccomp:speech', 'parataxis', 'csubj', 'aux:pass', 'appos', 'fixed', 'nsubj:pass', 'aux', 'nsubj:outer', 'obl:agent', 'expl:impers', 'expl', 'discourse', 'orphan', 'dislocated', 'flat', 'flat:foreign', 'iobj', 'vocative', 'csubj:outer', 'list', 'reparandum', 'csubj:pass']

DEPREL_LABELS_TO_IDX = {
    i : idx
    for idx, i in enumerate(DEPREL_LABELS)
}

IDX_TO_DEPREL_LABELS = {
    i: j
    for j, i in DEPREL_LABELS_TO_IDX.items()
}


UPOS_LABELS_TO_IDX = {
    i : idx
    for idx, i in enumerate(UPOS_LABELS)
}

IDX_TO_UPOS_LABELS = {
    i: j
    for j, i in UPOS_LABELS_TO_IDX.items()
}


#MAX_SEQUENCE_LENGTH = 512#
#PRETRAINED_MODEL_NAME = "neuralmind/bert-base-portuguese-cased"
#PRETRAINED_MODEL_NAME = "google-bert/bert-base-multilingual-cased"
NUM_TRAIN_EPOCHS = 10
PRETRAINED_MODEL_NAME = "neuralmind/bert-base-portuguese-cased"

In [6]:
# initializing Config and Tokenizer
BERT_CONFIG = BertConfig.from_pretrained(PRETRAINED_MODEL_NAME)
TOKENIZER = AutoTokenizer.from_pretrained("neuralmind/bert-base-portuguese-cased", use_fast=True) #.is_fast

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
BERT_CONFIG = {
    "vocab_size": 29794,
    "hidden_size": 768,
    "num_hidden_layers": 12,
    "num_attention_heads": 12,
    "intermediate_size": 3072,
    "hidden_act": "gelu",
    "max_position_embeddings": 512,
    "type_vocab_size": 2,
    "initializer_range": 0.02,
    "layer_norm_eps": 1e-12,
    "pad_token_id": 0,
    "attention_probs_dropout_prob": 0.1,
    "hidden_dropout_prob": 0.1,
}

In [8]:
import ast
import pandas as pd
import datasets
from datasets import Dataset, DatasetDict

def load_csv_as_hf_dataset(filepath):
    df = pd.read_csv(filepath)
    records = []
    for _, row in df.iterrows():
        records.append({
            'tokens': ast.literal_eval(row['tokens']),
            'upos': ast.literal_eval(row['upos']),
            'deprel': ast.literal_eval(row['deprel']),
            'head_tags': ast.literal_eval(str(row['head_tags'])),
            'deprel_tags': ast.literal_eval(str(row['deprel_tags'])),
            'upos_tags': ast.literal_eval(str(row['upos_tags'])),
        })
    return Dataset.from_list(records)

data = DatasetDict({
    'train': load_csv_as_hf_dataset('/home/guilhermelima/msc/data_dois/train_outxpos.csv'),
    'val':   load_csv_as_hf_dataset('/home/guilhermelima/msc/data_dois/val_outxpos.csv'),
    'test':  load_csv_as_hf_dataset('/home/guilhermelima/msc/data_dois/test_outxpos.csv'),
})
data

DatasetDict({
    train: Dataset({
        features: ['tokens', 'upos', 'deprel', 'head_tags', 'deprel_tags', 'upos_tags'],
        num_rows: 5893
    })
    val: Dataset({
        features: ['tokens', 'upos', 'deprel', 'head_tags', 'deprel_tags', 'upos_tags'],
        num_rows: 842
    })
    test: Dataset({
        features: ['tokens', 'upos', 'deprel', 'head_tags', 'deprel_tags', 'upos_tags'],
        num_rows: 1683
    })
})

# Modelo

In [9]:
'''
class Biaffine(nn.Module):
    def __init__(self, in_features, out_features=1, bias_x=True, bias_y=True):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.bias_x = bias_x
        self.bias_y = bias_y

        self.weight = nn.Parameter(torch.Tensor(out_features, in_features + int(bias_x), in_features + int(bias_y)))
        nn.init.xavier_uniform_(self.weight)

    def forward(self, x, y):
        # x, y: [B, L, H]
        if self.bias_x:
            x = torch.cat([x, x.new_ones(*x.shape[:-1], 1)], dim=-1)  # [B, L, H+1]
        if self.bias_y:
            y = torch.cat([y, y.new_ones(*y.shape[:-1], 1)], dim=-1)  # [B, L, H+1]
        # cálculo biaffine
        # weight: [O, H+1, H+1]
        # resultado: [B, O, L, L]
        logits = torch.einsum('bxi,oij,byj->boxy', x, self.weight, y)
        return logits.squeeze(1) if self.out_features == 1 else logits
'''

"\nclass Biaffine(nn.Module):\n    def __init__(self, in_features, out_features=1, bias_x=True, bias_y=True):\n        super().__init__()\n        self.in_features = in_features\n        self.out_features = out_features\n        self.bias_x = bias_x\n        self.bias_y = bias_y\n\n        self.weight = nn.Parameter(torch.Tensor(out_features, in_features + int(bias_x), in_features + int(bias_y)))\n        nn.init.xavier_uniform_(self.weight)\n\n    def forward(self, x, y):\n        # x, y: [B, L, H]\n        if self.bias_x:\n            x = torch.cat([x, x.new_ones(*x.shape[:-1], 1)], dim=-1)  # [B, L, H+1]\n        if self.bias_y:\n            y = torch.cat([y, y.new_ones(*y.shape[:-1], 1)], dim=-1)  # [B, L, H+1]\n        # cálculo biaffine\n        # weight: [O, H+1, H+1]\n        # resultado: [B, O, L, L]\n        logits = torch.einsum('bxi,oij,byj->boxy', x, self.weight, y)\n        return logits.squeeze(1) if self.out_features == 1 else logits\n"

In [10]:
from transformers import AutoTokenizer, AutoModelForTokenClassification, DataCollatorForTokenClassification, TrainingArguments, Trainer

In [11]:
from transformers import PreTrainedModel, AutoModel
import torch.nn as nn
import torch

#DECODER

class MultiTaskSentencePrediction(PreTrainedModel):
    # Permite carregar QUALQUER config de modelo decoder
    config_class = None

    def __init__(self, config, num_deprel_labels, num_upos_labels, num_head_labels=100):
        super().__init__(config)

        self.num_deprel_labels = num_deprel_labels
        self.num_upos_labels = num_upos_labels
        self.num_head_labels = num_head_labels


        self.model = AutoModel.from_config(config)

        hidden = config.hidden_size

        self.deprel_classifier = nn.Linear(hidden, num_deprel_labels)
        self.upos_classifier   = nn.Linear(hidden, num_upos_labels)
        self.head_classifier   = nn.Linear(hidden, num_head_labels)


        dropout_prob = getattr(config, "hidden_dropout", None) \
                       or getattr(config, "hidden_dropout_prob", None) \
                       or getattr(config, "classifier_dropout", 0.1) \
                       or 0.1

        self.dropout = nn.Dropout(dropout_prob)

        self.post_init()

    def forward(
        self,
        input_ids,
        attention_mask=None,
        position_ids=None,
        deprel_label=None,
        upos_label=None,
        head_label=None
    ):

        model_kwargs = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
        }

        # decoders geralmente aceitam position_ids
        if position_ids is not None and "position_ids" in self.model.forward.__code__.co_varnames:
            model_kwargs["position_ids"] = position_ids

        outputs = self.model(**model_kwargs)


        h = self.dropout(outputs.last_hidden_state)

        logits_deprel = self.deprel_classifier(h)
        logits_upos   = self.upos_classifier(h)
        logits_head   = self.head_classifier(h)

        loss = None
        if (
            deprel_label is not None
            and upos_label is not None
            and head_label is not None
        ):

                loss_fct1 = nn.CrossEntropyLoss(ignore_index=-100)
                loss_fct2 = nn.CrossEntropyLoss(ignore_index=-100)
                loss_fct3 = nn.CrossEntropyLoss(ignore_index=-100)


                loss = loss_fct1(
                logits_deprel.view(-1, self.num_deprel_labels),  # [B * L, num_xpos_labels]
                deprel_label.view(-1)                          # [B * L]
            ) + loss_fct2(
                logits_upos.view(-1, self.num_upos_labels),
                upos_label.view(-1)
            ) + loss_fct3(
                logits_head.view(-1, self.num_head_labels),
                head_label.view(-1)
            )

        if loss is not None:
            return loss, logits_deprel, logits_upos, logits_head

        return logits_deprel, logits_upos, logits_head

In [12]:
'''import torch
import torch.nn as nn

class MultiTaskDecoder(nn.Module):
    def __init__(self, hidden_size, num_deprel_labels, num_upos_labels, num_head_labels=100, num_layers=6, num_heads=8, dropout_prob=0.1):
        super().__init__()
        self.hidden_size = hidden_size
        self.num_deprel_labels = num_deprel_labels
        self.num_upos_labels = num_upos_labels
        self.num_head_labels = num_head_labels

        # Decoder Transformer
        decoder_layer = nn.TransformerDecoderLayer(d_model=hidden_size, nhead=num_heads, dropout=dropout_prob)
        self.decoder = nn.TransformerDecoder(decoder_layer, num_layers=num_layers)
        self.dropout = nn.Dropout(dropout_prob)

        # Cabeças de classificação
        self.deprel_classifier = nn.Linear(hidden_size, num_deprel_labels)
        self.upos_classifier = nn.Linear(hidden_size, num_upos_labels)
        self.head_classifier = nn.Linear(hidden_size, num_head_labels)

    def forward(
        self,
        input_ids=None,
        attention_mask=None,   # precisa aceitar mesmo que você não use
        token_type_ids=None,   # pode ignorar se não usar
        deprel_label=None,
        upos_label=None,
        head_label=None
    ):
        # input_ids -> embeddings simuladas ou reais
        # se for decoder puro sem embedding layer, transforme input_ids em embeddings
        # exemplo: embeddings = self.embedding(input_ids)

        # Simulando sequence_output: [batch_size, seq_len, hidden_size]
        sequence_output = torch.randn(input_ids.size(0), input_ids.size(1), self.hidden_size, device=input_ids.device)

        sequence_output = self.dropout(sequence_output)

        logits_deprel = self.deprel_classifier(sequence_output)
        logits_upos = self.upos_classifier(sequence_output)
        logits_head = self.head_classifier(sequence_output)

        loss = None
        if deprel_label is not None and upos_label is not None and head_label is not None:
            loss_fct1 = nn.CrossEntropyLoss(ignore_index=-100)
            loss_fct2 = nn.CrossEntropyLoss(ignore_index=-100)
            loss_fct3 = nn.CrossEntropyLoss(ignore_index=-100)

            loss = loss_fct1(
            logits_deprel.view(-1, self.num_deprel_labels),  # [B * L, num_xpos_labels]
            deprel_label.view(-1)                          # [B * L]
            ) + loss_fct2(
                logits_upos.view(-1, self.num_upos_labels),
                upos_label.view(-1)
            ) + loss_fct3(
                logits_head.view(-1, self.num_head_labels),
                head_label.view(-1)
            )

        return (loss, logits_deprel, logits_upos, logits_head) if loss is not None else (logits_deprel, logits_upos, logits_head)
'''

'import torch\nimport torch.nn as nn\n\nclass MultiTaskDecoder(nn.Module):\n    def __init__(self, hidden_size, num_deprel_labels, num_upos_labels, num_head_labels=100, num_layers=6, num_heads=8, dropout_prob=0.1):\n        super().__init__()\n        self.hidden_size = hidden_size\n        self.num_deprel_labels = num_deprel_labels\n        self.num_upos_labels = num_upos_labels\n        self.num_head_labels = num_head_labels\n\n        # Decoder Transformer\n        decoder_layer = nn.TransformerDecoderLayer(d_model=hidden_size, nhead=num_heads, dropout=dropout_prob)\n        self.decoder = nn.TransformerDecoder(decoder_layer, num_layers=num_layers)\n        self.dropout = nn.Dropout(dropout_prob)\n\n        # Cabeças de classificação\n        self.deprel_classifier = nn.Linear(hidden_size, num_deprel_labels)\n        self.upos_classifier = nn.Linear(hidden_size, num_upos_labels)\n        self.head_classifier = nn.Linear(hidden_size, num_head_labels)\n\n    def forward(\n        self,\n        input_ids=None,\n        attention_mask=None,   # precisa aceitar mesmo que você não use\n        token_type_ids=None,   # pode ignorar se não usar\n        deprel_label=None,\n        upos_label=None,\n        head_label=None\n    ):\n        # input_ids -> embeddings simuladas ou reais\n        # se for decoder puro sem embedding layer, transforme input_ids em embeddings\n        # exemplo: embeddings = self.embedding(input_ids)\n\n        # Simulando sequence_output: [batch_size, seq_len, hidden_size]\n        sequence_output = torch.randn(input_ids.size(0), input_ids.size(1), self.hidden_size, device=input_ids.device)\n\n        sequence_output = self.dropout(sequence_output)\n\n        logits_deprel = self.deprel_classifier(sequence_output)\n        logits_upos = self.upos_classifier(sequence_output)\n        logits_head = self.head_classifier(sequence_output)\n\n        loss = None\n        if deprel_label is not None and upos_label is not None and head_label is not None:\n            loss_fct1 = nn.CrossEntropyLoss(ignore_index=-100)\n            loss_fct2 = nn.CrossEntropyLoss(ignore_index=-100)\n            loss_fct3 = nn.CrossEntropyLoss(ignore_index=-100)\n\n            loss = loss_fct1(\n            logits_deprel.view(-1, self.num_deprel_labels),  # [B * L, num_xpos_labels]\n            deprel_label.view(-1)                          # [B * L]\n            ) + loss_fct2(\n                logits_upos.view(-1, self.num_upos_labels),\n                upos_label.view(-1)\n            ) + loss_fct3(\n                logits_head.view(-1, self.num_head_labels),\n                head_label.view(-1)\n            )\n\n        return (loss, logits_deprel, logits_upos, logits_head) if loss is not None else (logits_deprel, logits_upos, logits_head)\n'

In [13]:
# model definition
'''class MultiTaskSentencePredictionEncoderBiaffine(BertPreTrainedModel):
    def __init__(self, config, num_deprel_labels, num_upos_labels):
        super().__init__(config)
        
        self.num_deprel_labels = num_deprel_labels
        self.num_upos_labels = num_upos_labels
        
        self.bert = BertModel(config)
        
        # Classificadores simples para DepRel e UPOS
        self.deprel_classifier = nn.Linear(config.hidden_size, num_deprel_labels)
        self.upos_classifier   = nn.Linear(config.hidden_size, num_upos_labels)
        
        # Biaffine para heads
        self.head_mlp = nn.Linear(config.hidden_size, config.hidden_size)
        self.dep_mlp  = nn.Linear(config.hidden_size, config.hidden_size)
        self.head_classifier = Biaffine(in_features=config.hidden_size, out_features=1)
        
        classifier_dropout = config.classifier_dropout if config.classifier_dropout is not None else config.hidden_dropout_prob
        self.dropout = nn.Dropout(classifier_dropout)
        
        self.init_weights()

    def forward(self, input_ids, attention_mask=None, token_type_ids=None,
                deprel_label=None, upos_label=None, head_label=None):
        
        outputs = self.bert(
            input_ids=input_ids, 
            attention_mask=attention_mask,
            token_type_ids=token_type_ids
        )
        sequence_output = self.dropout(outputs[0])  # [B, L, H]
        
        # Classificação UPOS e DepRel
        logits_deprel = self.deprel_classifier(sequence_output)
        logits_upos   = self.upos_classifier(sequence_output)
        
        # Classificação de heads usando Biaffine
        head_repr = self.head_mlp(sequence_output)  # [B, L, H]
        dep_repr  = self.dep_mlp(sequence_output)   # [B, L, H]
        logits_head = self.head_classifier(head_repr, dep_repr).squeeze(1)  # [B, L, L]
        
        loss = None
        if deprel_label is not None and upos_label is not None and head_label is not None:
            loss_fct = nn.CrossEntropyLoss(ignore_index=-100)
            
            loss = loss_fct(
                logits_deprel.view(-1, self.num_deprel_labels),
                deprel_label.view(-1)
            ) + loss_fct(
                logits_upos.view(-1, self.num_upos_labels),
                upos_label.view(-1)
            ) + loss_fct(
                logits_head.view(-1, logits_head.size(-1)),  # [B*L, L]
                head_label.view(-1)
            )
        
        return (loss, logits_deprel, logits_upos, logits_head) if loss is not None else (logits_deprel, logits_upos, logits_head)'''

'class MultiTaskSentencePredictionEncoderBiaffine(BertPreTrainedModel):\n    def __init__(self, config, num_deprel_labels, num_upos_labels):\n        super().__init__(config)\n        \n        self.num_deprel_labels = num_deprel_labels\n        self.num_upos_labels = num_upos_labels\n        \n        self.bert = BertModel(config)\n        \n        # Classificadores simples para DepRel e UPOS\n        self.deprel_classifier = nn.Linear(config.hidden_size, num_deprel_labels)\n        self.upos_classifier   = nn.Linear(config.hidden_size, num_upos_labels)\n        \n        # Biaffine para heads\n        self.head_mlp = nn.Linear(config.hidden_size, config.hidden_size)\n        self.dep_mlp  = nn.Linear(config.hidden_size, config.hidden_size)\n        self.head_classifier = Biaffine(in_features=config.hidden_size, out_features=1)\n        \n        classifier_dropout = config.classifier_dropout if config.classifier_dropout is not None else config.hidden_dropout_prob\n        self.dropout = nn.Dropout(classifier_dropout)\n        \n        self.init_weights()\n\n    def forward(self, input_ids, attention_mask=None, token_type_ids=None,\n                deprel_label=None, upos_label=None, head_label=None):\n        \n        outputs = self.bert(\n            input_ids=input_ids, \n            attention_mask=attention_mask,\n            token_type_ids=token_type_ids\n        )\n        sequence_output = self.dropout(outputs[0])  # [B, L, H]\n        \n        # Classificação UPOS e DepRel\n        logits_deprel = self.deprel_classifier(sequence_output)\n        logits_upos   = self.upos_classifier(sequence_output)\n        \n        # Classificação de heads usando Biaffine\n        head_repr = self.head_mlp(sequence_output)  # [B, L, H]\n        dep_repr  = self.dep_mlp(sequence_output)   # [B, L, H]\n        logits_head = self.head_classifier(head_repr, dep_repr).squeeze(1)  # [B, L, L]\n        \n        loss = None\n        if deprel_label is not None and upos_label is not None and head_label is not None:\n            loss_fct = nn.CrossEntropyLoss(ignore_index=-100)\n            \n            loss = loss_fct(\n                logits_deprel.view(-1, self.num_deprel_labels),\n                deprel_label.view(-1)\n            ) + loss_fct(\n                logits_upos.view(-1, self.num_upos_labels),\n                upos_label.view(-1)\n            ) + loss_fct(\n                logits_head.view(-1, logits_head.size(-1)),  # [B*L, L]\n                head_label.view(-1)\n            )\n        \n        return (loss, logits_deprel, logits_upos, logits_head) if loss is not None else (logits_deprel, logits_upos, logits_head)'

In [14]:
# ENCONDER
class MultiTaskSentencePredictionEncoder(BertPreTrainedModel):
        _tied_weights_keys = []
        all_tied_weights_keys = {}
        def __init__(self, config, num_deprel_labels, num_upos_labels, num_head_labels=200):
            super().__init__(config)
            #self.num_xpos_labels = num_xpos_labels
            
            self.num_deprel_labels = num_deprel_labels
            self.num_upos_labels = num_upos_labels
            self.num_head_labels = num_head_labels
            
            if False:
                self.bert = BertModel(config)
            else:
                self.bert = AutoModel.from_config(config)

            #self.xpos_classifier = nn.Linear(config.hidden_size, num_xpos_labels)
            self.deprel_classifier = nn.Linear(config.hidden_size, num_deprel_labels)
            self.upos_classifier = nn.Linear(config.hidden_size, num_upos_labels)
            self.head_classifier = nn.Linear(config.hidden_size, num_head_labels)
            
            #self.head_classifier = Biaffine(in_features=config.hidden_size, out_features=1)

            classifier_dropout = config.classifier_dropout if config.classifier_dropout is not None else config.hidden_dropout_prob
            
            self.dropout = nn.Dropout(classifier_dropout)
            self.init_weights()

        def forward(
                self, input_ids, attention_mask=None, token_type_ids=None, 
                deprel_label=None, upos_label=None , head_label=None
        ):
            outputs = self.bert(
                input_ids=input_ids, attention_mask=attention_mask,
                token_type_ids=token_type_ids
            )
            sequence_output = self.dropout(outputs[0])  # [batch_size, seq_len, hidden_size]
            """
            def debug_labels(name, labels, num_classes):
                    print(f"\n{name}")
                    print("min:", labels.min().item())
                    print("max:", labels.max().item())
                    print("unique:", torch.unique(labels))

                    invalid = (labels >= num_classes) | (labels < -100)
                    if invalid.any():
                        print("❌ VALORES INVÁLIDOS ENCONTRADOS!")

                            # dentro do forward
            debug_labels("deprel", deprel_label, self.num_deprel_labels)
            debug_labels("upos", upos_label, self.num_upos_labels)
            debug_labels("head", head_label, self.num_head_labels)"""
            
            # Classificação por token
            #logits_xpos = self.xpos_classifier(sequence_output)     # [batch_size, seq_len, num_xpos_labels]
            logits_deprel = self.deprel_classifier(sequence_output)
            logits_upos = self.upos_classifier(sequence_output)
            logits_head = self.head_classifier(sequence_output)

            loss = None
            if deprel_label is not None and upos_label is not None and head_label is not None:
                
                
                loss_fct1 = nn.CrossEntropyLoss(ignore_index=-100)
                loss_fct2 = nn.CrossEntropyLoss(ignore_index=-100)
                loss_fct3 = nn.CrossEntropyLoss(ignore_index=-100)
                #loss_fct4 = nn.CrossEntropyLoss(ignore_index=-100)

                loss = loss_fct1(
                logits_deprel.view(-1, self.num_deprel_labels),  # [B * L, num_xpos_labels]
                deprel_label.view(-1)                          # [B * L]
            ) + loss_fct2(
                logits_upos.view(-1, self.num_upos_labels),
                upos_label.view(-1)
            ) + loss_fct3(
                logits_head.view(-1, self.num_head_labels),
                head_label.view(-1)
            )

            return (loss, logits_deprel, logits_upos, logits_head) if loss is not None else (logits_deprel, logits_upos, logits_head)

# Tokenização

In [15]:
class POSDataset:

    def __init__(self, tokenizer_ckpt):
        #self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_ckpt, add_prefix_space=True)
        self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_ckpt)
        
    def align_labels_with_tokens(self, labels, word_ids):
        new_labels = []
        current_word = None
        for word_id in word_ids:
            if word_id != current_word:
                # Start of a new word!
                current_word = word_id
                try:
                    label = -100 if word_id is None else labels[word_id]
                except:
                    label = -100
                new_labels.append(label)
            elif word_id is None:
                # Special token
                new_labels.append(-100)
            else:
                # Same word as previous token
                label = labels[word_id]
                # If the label is B-XXX we change it to I-XXX
                #if label % 2 == 1:
                #    label += 1
                new_labels.append(label)

        return new_labels
    def preprocess_function(self, examples):
        tokenized_inputs = self.tokenizer(
        examples["tokens"], truncation=True , padding="max_length" , is_split_into_words=True, max_length=512)

        
        '''all_labels_xpos = examples["xpos_tags"]
        new_labels_xpos = []
        for i, labels in enumerate(all_labels_xpos):
            word_ids = tokenized_inputs.word_ids(i)
            new_labels_xpos.append(self.align_labels_with_tokens(labels, word_ids))'''

        all_labels_deprel = examples["deprel_tags"]
        new_labels_deprel = []
        for i, labels in enumerate(all_labels_deprel):
            word_ids = tokenized_inputs.word_ids(i)
            new_labels_deprel.append(self.align_labels_with_tokens(labels, word_ids))
        
        all_labels_upos = examples["upos_tags"]
        new_labels_upos = []
        for i, labels in enumerate(all_labels_upos):
            word_ids = tokenized_inputs.word_ids(i)
            new_labels_upos.append(self.align_labels_with_tokens(labels, word_ids))

        all_labels_head = examples["head_tags"]
        new_labels_head = []
        for i, labels in enumerate(all_labels_head):
            word_ids = tokenized_inputs.word_ids(i)
            new_labels_head.append(self.align_labels_with_tokens(labels, word_ids))

        #tokenized_inputs["xpos_label"] = new_labels_xpos
        tokenized_inputs["deprel_label"] = new_labels_deprel
        tokenized_inputs["upos_label"] = new_labels_upos
        tokenized_inputs["head_label"] = new_labels_head
        return tokenized_inputs

    def create_data(self, train, test):

        tokenized_train_dataset = train.map(
            self.preprocess_function,
            batched=True,
            remove_columns=train.column_names
        )

        tokenized_test_dataset = test.map(
            self.preprocess_function,
            batched=True,
            remove_columns= test.column_names
        )

        return tokenized_train_dataset, tokenized_test_dataset

In [16]:
#nerdataset = POSDataset("neuralmind/bert-base-portuguese-cased")
#nerdataset = POSDataset("google-bert/bert-base-multilingual-cased")
nerdataset = POSDataset("amadeusai/modernJabuticaBERT-Base-1k")

In [17]:
train_data, valid_data = nerdataset.create_data(data['train'], data['val'])

Map:   0%|                                      | 0/5893 [00:00<?, ? examples/s]

Map:  17%|████▏                    | 1000/5893 [00:00<00:02, 2046.61 examples/s]

Map:  34%|████████▍                | 2000/5893 [00:00<00:01, 2985.93 examples/s]

Map:  51%|████████████▋            | 3000/5893 [00:00<00:00, 3422.35 examples/s]

Map:  68%|████████████████▉        | 4000/5893 [00:01<00:00, 3750.34 examples/s]

Map:  85%|█████████████████████▏   | 5000/5893 [00:01<00:00, 3744.75 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3925.80 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3548.41 examples/s]

Map:   0%|                                       | 0/842 [00:00<?, ? examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2260.59 examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2233.13 examples/s]

In [18]:
train_data

Dataset({
    features: ['input_ids', 'attention_mask', 'deprel_label', 'upos_label', 'head_label'],
    num_rows: 5893
})

# Data Collator

In [19]:
def data_collator(batch, padding_token_id=TOKENIZER.pad_token_id):
    input_ids = [item["input_ids"] for item in batch]
    attention_masks = [item["attention_mask"] for item in batch]
    #xpos_label = [item["xpos_label"] for item in batch]
    deprel_label = [item["deprel_label"] for item in batch]
    upos_label = [item["upos_label"] for item in batch]
    head_label  = [item["head_label"] for item in batch]
    
    
    max_len = max(len(ids) for ids in input_ids)
    '''
    for i, labels in enumerate(head_label):  # ou head_label, deprel_label
        for j, label in enumerate(labels):
            if label != -100 and (label < 0 or label >= 75):
                print(f"Erro no exemplo {i}, posição {j}: label={label}")'''

    input_ids = torch.tensor([ids + [padding_token_id] * (max_len - len(ids)) for ids in input_ids])
    attention_masks = torch.tensor([masks + [0] * (max_len - len(masks)) for masks in attention_masks])
    #xpos_label = torch.tensor([labels + [-100] * (max_len - len(labels)) for labels in xpos_label])
    deprel_label = torch.tensor([labels + [-100] * (max_len - len(labels)) for labels in deprel_label])
    upos_label = torch.tensor([labels + [-100] * (max_len - len(labels)) for labels in upos_label])
    head_label = torch.tensor([labels + [-100] * (max_len - len(labels)) for labels in head_label])

    return {
        "input_ids": input_ids,
        "attention_mask": attention_masks,
        #"xpos_label": xpos_label,
        "deprel_label": deprel_label,
        "upos_label": upos_label,
        "head_label": head_label
    }

In [20]:
'''def data_collator(batch, padding_token_id=0):
    input_ids = [item["input_ids"] for item in batch]

    # Cria attention_mask se não existir
    if "attention_mask" in batch[0]:
        attention_masks = [item["attention_mask"] for item in batch]
    else:
        attention_masks = [[1] * len(ids) for ids in input_ids]  # tudo 1s

    deprel_label = [item["deprel_label"] for item in batch]
    upos_label = [item["upos_label"] for item in batch]
    head_label  = [item["head_label"] for item in batch]

    max_len = max(len(ids) for ids in input_ids)

    # Padding
    input_ids = torch.tensor([ids + [padding_token_id] * (max_len - len(ids)) for ids in input_ids])
    attention_masks = torch.tensor([mask + [0] * (max_len - len(mask)) for mask in attention_masks])
    deprel_label = torch.tensor([lbl + [-100] * (max_len - len(lbl)) for lbl in deprel_label])
    upos_label = torch.tensor([lbl + [-100] * (max_len - len(lbl)) for lbl in upos_label])
    head_label = torch.tensor([lbl + [-100] * (max_len - len(lbl)) for lbl in head_label])

    return {
        "input_ids": input_ids,
        "attention_mask": attention_masks,
        "deprel_label": deprel_label,
        "upos_label": upos_label,
        "head_label": head_label
    }
'''

'def data_collator(batch, padding_token_id=0):\n    input_ids = [item["input_ids"] for item in batch]\n\n    # Cria attention_mask se não existir\n    if "attention_mask" in batch[0]:\n        attention_masks = [item["attention_mask"] for item in batch]\n    else:\n        attention_masks = [[1] * len(ids) for ids in input_ids]  # tudo 1s\n\n    deprel_label = [item["deprel_label"] for item in batch]\n    upos_label = [item["upos_label"] for item in batch]\n    head_label  = [item["head_label"] for item in batch]\n\n    max_len = max(len(ids) for ids in input_ids)\n\n    # Padding\n    input_ids = torch.tensor([ids + [padding_token_id] * (max_len - len(ids)) for ids in input_ids])\n    attention_masks = torch.tensor([mask + [0] * (max_len - len(mask)) for mask in attention_masks])\n    deprel_label = torch.tensor([lbl + [-100] * (max_len - len(lbl)) for lbl in deprel_label])\n    upos_label = torch.tensor([lbl + [-100] * (max_len - len(lbl)) for lbl in upos_label])\n    head_label = torch.tensor([lbl + [-100] * (max_len - len(lbl)) for lbl in head_label])\n\n    return {\n        "input_ids": input_ids,\n        "attention_mask": attention_masks,\n        "deprel_label": deprel_label,\n        "upos_label": upos_label,\n        "head_label": head_label\n    }\n'

In [21]:
#config_encoder = BertConfig(**BERT_CONFIG)

# Criação do Modelo

In [22]:
#model = MultiTaskSentencePrediction.from_pretrained(
#    PRETRAINED_MODEL_NAME,
#    config=BERT_CONFIG,
#    num_deprel_labels=len(DEPREL_LABELS), num_upos_labels=len(UPOS_LABELS), num_head_labels=100
#)
from transformers import AutoConfig


config = AutoConfig.from_pretrained(PRETRAINED_MODEL_NAME)

# ESSENCIAL: registrar a classe no config
#MultiTaskSentencePrediction.config_class = config.__class_

In [23]:
model = MultiTaskSentencePrediction.from_pretrained(
    PRETRAINED_MODEL_NAME,
    config=config,
    num_deprel_labels=len(DEPREL_LABELS),
    num_upos_labels=len(UPOS_LABELS)
)
#model = model.to("cpu")
#torch.cuda.empty_cache()

Loading weights: 0it [00:00, ?it/s]

Loading weights: 0it [00:00, ?it/s]

[transformers] MultiTaskSentencePrediction LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                                            | Status     |
---------------------------------------------------------------+------------+-
bert.encoder.layer.{0...11}.attention.self.query.bias          | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.output.LayerNorm.bias    | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.self.query.weight        | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.self.key.bias            | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.self.key.weight          | UNEXPECTED |
bert.encoder.layer.{0...11}.output.dense.bias                  | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.output.dense.bias        | UNEXPECTED |
bert.encoder.layer.{0...11}.output.LayerNorm.bias              | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight                     | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.output.LayerNorm.weight  | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.output.dense.weight      | UNEXPECTED |
bert.encoder.layer.{0...11}.intermediate.dense.weight          | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.self.value.weight        | UNEXPECTED |
bert.encoder.layer.{0...11}.output.LayerNorm.weight            | UNEXPECTED |
bert.encoder.layer.{0...11}.intermediate.dense.bias            | UNEXPECTED |
bert.embeddings.LayerNorm.bias                                 | UNEXPECTED |
cls.predictions.bias                                           | UNEXPECTED |
bert.encoder.layer.{0...11}.attention.self.value.bias          | UNEXPECTED |
bert.pooler.dense.weight                                       | UNEXPECTED |
bert.encoder.layer.{0...11}.output.dense.weight                | UNEXPECTED |
bert.pooler.dense.bias                                         | UNEXPECTED |
cls.predictions.decoder.weight                                 | UNEXPECTED |
cls.seq_relationship.bias                                      | UNEXPECTED |
bert.embeddings.word_embeddings.weight                         | UNEXPECTED |
cls.predictions.transform.dense.bias                           | UNEXPECTED |
cls.seq_relationship.weight                                    | UNEXPECTED |
cls.predictions.transform.dense.weight                         | UNEXPECTED |
bert.embeddings.LayerNorm.weight                               | UNEXPECTED |
bert.embeddings.token_type_embeddings.weight                   | UNEXPECTED |
bert.embeddings.position_embeddings.weight                     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias                       | UNEXPECTED |
model.encoder.layer.{0...11}.output.LayerNorm.weight           | MISSING    |
model.encoder.layer.{0...11}.attention.self.query.bias         | MISSING    |
model.encoder.layer.{0...11}.output.dense.weight               | MISSING    |
model.encoder.layer.{0...11}.attention.self.value.bias         | MISSING    |
model.encoder.layer.{0...11}.output.dense.bias                 | MISSING    |
model.encoder.layer.{0...11}.attention.self.query.weight       | MISSING    |
model.encoder.layer.{0...11}.attention.output.LayerNorm.weight | MISSING    |
model.pooler.dense.weight                                      | MISSING    |
model.encoder.layer.{0...11}.intermediate.dense.bias           | MISSING    |
model.encoder.layer.{0...11}.attention.output.dense.bias       | MISSING    |
model.encoder.layer.{0...11}.output.LayerNorm.bias             | MISSING    |
upos_classifier.weight                                         | MISSING    |
model.embeddings.LayerNorm.weight                              | MISSING    |
model.encoder.layer.{0...11}.attention.self.value.weight       | MISSING    |
head_classifier.weight                                         | MISSING    |
model.encoder.layer.{0...11}.attention.self.key.bias           | MISSING    |
model.encoder.layer.{0...11}.attention.output.LayerNorm.bias   | MISSING    |
model.encoder.layer.{0...11}.attention.output.dense.weight     | MISSING    |
model.encoder.layer.{0...11}.intermediate.dense.weight         | MISSING    |
head_classifier.bias                                           | MISSING    |
deprel_classifier.weight                                       | MISSING    |
model.pooler.dense.bias                                        | MISSING    |
model.encoder.layer.{0...11}.attention.self.key.weight         | MISSING    |
model.embeddings.position_embeddings.weight                    | MISSING    |
model.embeddings.word_embeddings.weight                        | MISSING    |
deprel_classifier.bias                                         | MISSING    |
upos_classifier.bias                                           | MISSING    |
model.embeddings.token_type_embeddings.weight                  | MISSING    |
model.embeddings.LayerNorm.bias                                | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [24]:
model

MultiTaskSentencePrediction(
  (model): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(29794, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (deprel_classifier): Linear(in_features=768, out_features=44, bias=True)
  (upos_classifier): Linear(in_features=768, out_features=16, bias=True)
  (head_classifier): Linear(in_features=768, out_features=100, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [25]:
config = AutoConfig.from_pretrained(PRETRAINED_MODEL_NAME)

In [26]:
config = AutoConfig.from_pretrained(PRETRAINED_MODEL_NAME)

model = MultiTaskSentencePredictionEncoder.from_pretrained(
    PRETRAINED_MODEL_NAME,
    config=config,
    num_deprel_labels=len(DEPREL_LABELS),
    num_upos_labels=len(UPOS_LABELS)
)

Loading weights:   0%|                                  | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 199/199 [00:00<00:00, 30937.64it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
upos_classifier.weight                     | MISSING    |
head_classifier.weight                     | MISSING    |
head_classifier.bias                       | MISSING    |
deprel_classifier.weight                   | MISSING    |
deprel_classifier.bias                     | MISSING    |
upos_classifier.bias                       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [27]:
'''HIDDEN_SIZE = 512  # exemplo, ajuste conforme sua arquitetura
NUM_LAYERS = 6
NUM_HEADS = 8
DROPOUT = 0.1

# Instancia o decoder multitarefa
model = MultiTaskDecoder(
    hidden_size=HIDDEN_SIZE,
    num_deprel_labels=len(DEPREL_LABELS),
    num_upos_labels=len(UPOS_LABELS),
    num_head_labels=100,
    num_layers=NUM_LAYERS,
    num_heads=NUM_HEADS,
    dropout_prob=DROPOUT
)'''

'HIDDEN_SIZE = 512  # exemplo, ajuste conforme sua arquitetura\nNUM_LAYERS = 6\nNUM_HEADS = 8\nDROPOUT = 0.1\n\n# Instancia o decoder multitarefa\nmodel = MultiTaskDecoder(\n    hidden_size=HIDDEN_SIZE,\n    num_deprel_labels=len(DEPREL_LABELS),\n    num_upos_labels=len(UPOS_LABELS),\n    num_head_labels=100,\n    num_layers=NUM_LAYERS,\n    num_heads=NUM_HEADS,\n    dropout_prob=DROPOUT\n)'

In [28]:
model

MultiTaskSentencePredictionEncoder(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(29794, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (deprel_classifier): Linear(in_features=768, out_features=44, bias=True)
  (upos_classifier): Linear(in_features=768, out_features=16, bias=True)
  (head_classifier): Linear(in_features=768, out_features=200, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

# Compute Metrics Old

In [29]:
import numpy as np


def compute_metrics(eval_pred):
    logits, labels = eval_pred

    deprel_logits, upos_logits, head_logits = logits
    deprel_labels, upos_labels, head_labels = labels

    # Argmax
    deprel_preds = np.argmax(deprel_logits, axis=-1)
    upos_preds   = np.argmax(upos_logits, axis=-1)
    head_preds   = np.argmax(head_logits, axis=-1)

    # Máscara válida: token com HEAD e DEPREL anotados
    valid_mask = (
        (head_labels != -100) &
        (deprel_labels != -100)
    )

    # Filtrar
    head_preds = head_preds[valid_mask]
    head_labels = head_labels[valid_mask]

    deprel_preds = deprel_preds[valid_mask]
    deprel_labels = deprel_labels[valid_mask]

    # UAS: HEAD correto
    uas = (head_preds == head_labels).mean()

    # LAS: HEAD + DEPREL corretos
    las = ((head_preds == head_labels) &
           (deprel_preds == deprel_labels)).mean()

    # Métricas auxiliares (opcional)
    upos_mask = upos_labels != -100
    upos_acc = (upos_preds[upos_mask] == upos_labels[upos_mask]).mean()

    return {
        "uas": float(uas),
        "las": float(las),
        "upos_accuracy": float(upos_acc),
    }

# Compute Metrics

In [30]:
"""import numpy as np
import json
import os

def softmax(x, axis=-1):
    e_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return e_x / e_x.sum(axis=axis, keepdims=True)


def compute_metrics(eval_pred, PRETRAINED_MODEL=None, FOLD=None, TRIAL=None):

    save_path = "epoch_predictions/predictions_results.json"
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    # ---------------- IDENTIDADE DO EXPERIMENTO ----------------
    model_name = PRETRAINED_MODEL.split("/")[-1] if PRETRAINED_MODEL else "unknown_model"
    run_id = f"{model_name}_fold{FOLD}_trial{TRIAL}"

    logits, labels = eval_pred
    deprel_logits, upos_logits, head_logits = logits
    deprel_labels, upos_labels, head_labels = labels

    # ---------------- PROBABILIDADES ----------------
    deprel_probs = softmax(deprel_logits, axis=-1)
    upos_probs   = softmax(upos_logits, axis=-1)
    head_probs   = softmax(head_logits, axis=-1)

    # ---------------- PREDIÇÕES ----------------
    deprel_preds = np.argmax(deprel_logits, axis=-1)
    upos_preds   = np.argmax(upos_logits, axis=-1)
    head_preds   = np.argmax(head_logits, axis=-1)

    # ---------------- MASK DEPENDENCY ----------------
    valid_mask = (
        (head_labels != -100) &
        (deprel_labels != -100)
    )

    head_preds_masked   = head_preds[valid_mask]
    head_labels_masked  = head_labels[valid_mask]
    head_probs_masked   = head_probs[valid_mask]

    deprel_preds_masked  = deprel_preds[valid_mask]
    deprel_labels_masked = deprel_labels[valid_mask]
    deprel_probs_masked  = deprel_probs[valid_mask]

    # ---------------- MÉTRICAS PRINCIPAIS ----------------
    uas = (head_preds_masked == head_labels_masked).mean()

    las = (
        (head_preds_masked == head_labels_masked) &
        (deprel_preds_masked == deprel_labels_masked)
    ).mean()

    # ---------------- UPOS ----------------
    upos_mask = upos_labels != -100

    upos_preds_masked  = upos_preds[upos_mask]
    upos_labels_masked = upos_labels[upos_mask]
    upos_probs_masked  = upos_probs[upos_mask]

    upos_acc = (upos_preds_masked == upos_labels_masked).mean()

    # ---------------- CARREGAR JSON ----------------
    if os.path.exists(save_path):
        with open(save_path, "r", encoding="utf-8") as f:
            all_data = json.load(f)
    else:
        all_data = {}

    # ---------------- META ----------------
    if "META" not in all_data:
        all_data["META"] = {
            "model_name": model_name,
            "pretrained_model": PRETRAINED_MODEL,
            "fold": FOLD,
            "trial": TRIAL,
            "run_id": run_id
        }

    # ---------------- STORAGE ----------------
    if "RANK_PREDICTIONS" not in all_data:
        all_data["RANK_PREDICTIONS"] = {
            "deprel": [],
            "upos": [],
            "head": []
        }

    def get_correct_rank(prob_vector, correct_label):
        sorted_indices = np.argsort(prob_vector)[::-1]
        return int(np.where(sorted_indices == correct_label)[0][0] + 1)

    # ---------------- DEPREL ----------------
    for i in range(len(deprel_preds_masked)):
        probs = deprel_probs_masked[i]
        correct_label = int(deprel_labels_masked[i])
        pred_label = int(deprel_preds_masked[i])

        all_data["RANK_PREDICTIONS"]["deprel"].append({
            "run_id": run_id,
            "model": model_name,
            "fold": FOLD,
            "trial": TRIAL,
            "index": i,
            "correct_label": correct_label,
            "pred_label": pred_label,
            "correct_prob": float(probs[correct_label]),
            "pred_prob": float(probs[pred_label]),
            "correct_rank": get_correct_rank(probs, correct_label)
        })

    # ---------------- UPOS ----------------
    for i in range(len(upos_preds_masked)):
        probs = upos_probs_masked[i]
        correct_label = int(upos_labels_masked[i])
        pred_label = int(upos_preds_masked[i])

        all_data["RANK_PREDICTIONS"]["upos"].append({
            "run_id": run_id,
            "model": model_name,
            "fold": FOLD,
            "trial": TRIAL,
            "index": i,
            "correct_label": correct_label,
            "pred_label": pred_label,
            "correct_prob": float(probs[correct_label]),
            "pred_prob": float(probs[pred_label]),
            "correct_rank": get_correct_rank(probs, correct_label)
        })

    # ---------------- HEAD ----------------
    for i in range(len(head_preds_masked)):
        probs = head_probs_masked[i]
        correct_label = int(head_labels_masked[i])
        pred_label = int(head_preds_masked[i])

        all_data["RANK_PREDICTIONS"]["head"].append({
            "run_id": run_id,
            "model": model_name,
            "fold": FOLD,
            "trial": TRIAL,
            "index": i,
            "correct_label": correct_label,
            "pred_label": pred_label,
            "correct_prob": float(probs[correct_label]),
            "pred_prob": float(probs[pred_label]),
            "correct_rank": get_correct_rank(probs, correct_label)
        })

    # ---------------- SALVAR ----------------
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(all_data, f, indent=2, ensure_ascii=False)

    return {
        "uas": float(uas),
        "las": float(las),
        "upos_accuracy": float(upos_acc),
    }"""

'import numpy as np\nimport json\nimport os\n\ndef softmax(x, axis=-1):\n    e_x = np.exp(x - np.max(x, axis=axis, keepdims=True))\n    return e_x / e_x.sum(axis=axis, keepdims=True)\n\n\ndef compute_metrics(eval_pred, PRETRAINED_MODEL=None, FOLD=None, TRIAL=None):\n\n    save_path = "epoch_predictions/predictions_results.json"\n    os.makedirs(os.path.dirname(save_path), exist_ok=True)\n\n    # ---------------- IDENTIDADE DO EXPERIMENTO ----------------\n    model_name = PRETRAINED_MODEL.split("/")[-1] if PRETRAINED_MODEL else "unknown_model"\n    run_id = f"{model_name}_fold{FOLD}_trial{TRIAL}"\n\n    logits, labels = eval_pred\n    deprel_logits, upos_logits, head_logits = logits\n    deprel_labels, upos_labels, head_labels = labels\n\n    # ---------------- PROBABILIDADES ----------------\n    deprel_probs = softmax(deprel_logits, axis=-1)\n    upos_probs   = softmax(upos_logits, axis=-1)\n    head_probs   = softmax(head_logits, axis=-1)\n\n    # ---------------- PREDIÇÕES ----------------\n    deprel_preds = np.argmax(deprel_logits, axis=-1)\n    upos_preds   = np.argmax(upos_logits, axis=-1)\n    head_preds   = np.argmax(head_logits, axis=-1)\n\n    # ---------------- MASK DEPENDENCY ----------------\n    valid_mask = (\n        (head_labels != -100) &\n        (deprel_labels != -100)\n    )\n\n    head_preds_masked   = head_preds[valid_mask]\n    head_labels_masked  = head_labels[valid_mask]\n    head_probs_masked   = head_probs[valid_mask]\n\n    deprel_preds_masked  = deprel_preds[valid_mask]\n    deprel_labels_masked = deprel_labels[valid_mask]\n    deprel_probs_masked  = deprel_probs[valid_mask]\n\n    # ---------------- MÉTRICAS PRINCIPAIS ----------------\n    uas = (head_preds_masked == head_labels_masked).mean()\n\n    las = (\n        (head_preds_masked == head_labels_masked) &\n        (deprel_preds_masked == deprel_labels_masked)\n    ).mean()\n\n    # ---------------- UPOS ----------------\n    upos_mask = upos_labels != -100\n\n    upos_preds_masked  = upos_preds[upos_mask]\n    upos_labels_masked = upos_labels[upos_mask]\n    upos_probs_masked  = upos_probs[upos_mask]\n\n    upos_acc = (upos_preds_masked == upos_labels_masked).mean()\n\n    # ---------------- CARREGAR JSON ----------------\n    if os.path.exists(save_path):\n        with open(save_path, "r", encoding="utf-8") as f:\n            all_data = json.load(f)\n    else:\n        all_data = {}\n\n    # ---------------- META ----------------\n    if "META" not in all_data:\n        all_data["META"] = {\n            "model_name": model_name,\n            "pretrained_model": PRETRAINED_MODEL,\n            "fold": FOLD,\n            "trial": TRIAL,\n            "run_id": run_id\n        }\n\n    # ---------------- STORAGE ----------------\n    if "RANK_PREDICTIONS" not in all_data:\n        all_data["RANK_PREDICTIONS"] = {\n            "deprel": [],\n            "upos": [],\n            "head": []\n        }\n\n    def get_correct_rank(prob_vector, correct_label):\n        sorted_indices = np.argsort(prob_vector)[::-1]\n        return int(np.where(sorted_indices == correct_label)[0][0] + 1)\n\n    # ---------------- DEPREL ----------------\n    for i in range(len(deprel_preds_masked)):\n        probs = deprel_probs_masked[i]\n        correct_label = int(deprel_labels_masked[i])\n        pred_label = int(deprel_preds_masked[i])\n\n        all_data["RANK_PREDICTIONS"]["deprel"].append({\n            "run_id": run_id,\n            "model": model_name,\n            "fold": FOLD,\n            "trial": TRIAL,\n            "index": i,\n            "correct_label": correct_label,\n            "pred_label": pred_label,\n            "correct_prob": float(probs[correct_label]),\n            "pred_prob": float(probs[pred_label]),\n            "correct_rank": get_correct_rank(probs, correct_label)\n        })\n\n    # ---------------- UPOS ----------------\n    for i in range(len(upos_preds_masked)):\n        probs = upos_probs_masked[i]\n        correct_label = int(upos_labels_masked[i])\n        pred_label = int(upos_preds_masked[i])\n\n        all_data["RANK_PREDICTIONS"]["upos"].append({\n            "run_id": run_id,\n            "model": model_name,\n            "fold": FOLD,\n            "trial": TRIAL,\n            "index": i,\n            "correct_label": correct_label,\n            "pred_label": pred_label,\n            "correct_prob": float(probs[correct_label]),\n            "pred_prob": float(probs[pred_label]),\n            "correct_rank": get_correct_rank(probs, correct_label)\n        })\n\n    # ---------------- HEAD ----------------\n    for i in range(len(head_preds_masked)):\n        probs = head_probs_masked[i]\n        correct_label = int(head_labels_masked[i])\n        pred_label = int(head_preds_masked[i])\n\n        all_data["RANK_PREDICTIONS"]["head"].append({\n            "run_id": run_id,\n            "model": model_name,\n            "fold": FOLD,\n            "trial": TRIAL,\n            "index": i,\n            "correct_label": correct_label,\n            "pred_label": pred_label,\n            "correct_prob": float(probs[correct_label]),\n            "pred_prob": float(probs[pred_label]),\n            "correct_rank": get_correct_rank(probs, correct_label)\n        })\n\n    # ---------------- SALVAR ----------------\n    with open(save_path, "w", encoding="utf-8") as f:\n        json.dump(all_data, f, indent=2, ensure_ascii=False)\n\n    return {\n        "uas": float(uas),\n        "las": float(las),\n        "upos_accuracy": float(upos_acc),\n    }'

In [31]:
from sklearn.model_selection import KFold
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

In [32]:
from datasets import concatenate_datasets

In [33]:
import torch

if torch.cuda.is_available():
    print("GPU está ativa!")
    print(f"Nome da GPU: {torch.cuda.get_device_name(0)}")
    print(f"Número de GPUs disponíveis: {torch.cuda.device_count()}")
else:
    print("GPU não está disponível ou não foi detectada.")

GPU está ativa!
Nome da GPU: NVIDIA GeForce RTX 4090
Número de GPUs disponíveis: 1

In [34]:
import os
os.environ["WANDB_API_KEY"] = "7499f50c2fffad3ce3e34b7b7b02152988a1742c"

import wandb
#wandb.login()

In [35]:
output_directory = RESULTS_DIRECTORY
evaluation_strategy = 'epoch'
gradint_accumulation_steps = 1
learning_rate=2.2933248212781904e-05,
weight_decay=0.17042771903841708,
max_grad_norm = 1
num_train_epochs = 10 #NUM_TRAIN_EPOCHS
lr_scheduler_type = 'linear'
warmup_ratio=0.42465329939827173
logging_dir = LOGGING_DIRECTORY
logging_strategy = 'epoch'
save_strategy = 'epoch'
save_total_limit = 1
#label_names = ['xpos_label', 'deprel_label', 'upos_label', 'head_label']
label_names = ['deprel_label', 'upos_label', 'head_label']
load_best_model_at_end = True
metric_for_best_model="las"
greater_is_better = True
label_smoothing_factor = 0
#report_to = 'tensorboard'
gradient_checkpointing = False
remove_unused_columns=False

In [36]:
# Setup training arguments
'''training_args = TrainingArguments(
    #output_dir= f'./ettin-decoder-150m_parser',
    eval_strategy=evaluation_strategy,
    learning_rate=learning_rate,
    num_train_epochs=10,
    weight_decay=weight_decay,
    logging_dir=logging_dir,
    label_names=label_names,
    max_grad_norm=max_grad_norm,
    lr_scheduler_type=lr_scheduler_type,
    warmup_ratio=warmup_ratio,
    logging_strategy=logging_strategy,
    save_strategy=save_strategy,
    save_total_limit=save_total_limit,
    load_best_model_at_end=load_best_model_at_end,
    metric_for_best_model=metric_for_best_model,
    greater_is_better=greater_is_better,
    label_smoothing_factor=label_smoothing_factor,
    #report_to=report_to,
    gradient_checkpointing=gradient_checkpointing
)'''

early_stop_callback = EarlyStoppingCallback(3)

In [37]:
!pip freeze > requirements_all.txt

# Optuna

In [38]:
import optuna
from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments
from datasets import load_dataset
import torch
import numpy as np
from sklearn.metrics import accuracy_score
import os
import json
import gc
import torch
#os.environ["WANDB_DISABLED"] = "true"

from datasets import concatenate_datasets

def save_result_to_json(result_dict, filename="results.jsonl"):
    with open(filename, "a", encoding="utf-8") as f:
        f.write(json.dumps(result_dict, ensure_ascii=False) + "\n")



# K Folds

def objective(trial, name_model, train_data, valid_data, tokenizer=None, data_collator=None, name="model_run"):
    # Hiperparâmetros sugeridos pelo Optuna
    #while True:
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True)
    weight_decay = trial.suggest_float("weight_decay", 0.1, 0.3)
    warmup_ratio = trial.suggest_float("warmup_ratio", 0.3, 0.5)
    num_train_epochs = trial.suggest_int("num_train_epochs", 40, 40)
    label_smoothing_factor = 0 #trial.suggest_float("label_smoothing_factor", 0.0, 0.2)
    #config = (weight_decay, learning_rate, warmup_ratio)
    
    import os
    os.environ["WANDB_API_KEY"] = "7499f50c2fffad3ce3e34b7b7b02152988a1742c"

    import wandb
    

    kf = KFold(n_splits=k, shuffle=True, random_state=42)

    # Suponha que seus dados estejam assim:
    # data = {'train': list de exemplos, 'val': list de exemplos}

    # 1. Juntar tudo em um único data
    #full_data = concatenate_datasets([train_data, valid_data])
    full_data = concatenate_datasets([data['train'], data['val']])
    # Converter para numpy array só para facilitar a indexação
    indices = np.arange(len(full_data))
    nerdataset = POSDataset(name_model)
    for fold, (train_idx, val_idx) in enumerate(kf.split(full_data)):
        #gc.collect()

        #torch.cuda.empty_cache()

        #torch.cuda.ipc_collect()

        
        # reinstalar_pytorch_nightly()
        wandb.init(
            entity="gdlima-universidade-federal-de-pelotas",
            project="hf-optuna",
            name=f"linear_{name_model}_trial{trial.number}_fold{fold}",  # <- aqui define o nome do run
            config={
                "learning_rate": learning_rate,
                "architecture": name_model,
                "epochs": num_train_epochs,
                "weight_decay": weight_decay,
                "warmup_ratio": warmup_ratio,
                "label_smoothing_factor": label_smoothing_factor
            },
        )
        config = AutoConfig.from_pretrained(name_model)

        model = MultiTaskSentencePredictionEncoder.from_pretrained(
            name_model,
            config=config,
            num_deprel_labels=len(DEPREL_LABELS),
            num_upos_labels=len(UPOS_LABELS),
            _fast_init=False,  # garante que _init_weights roda para Biaffine/MLP
        )

        # Verificar CPU antes de mover para GPU — distingue bug de init vs CUDA corrompido
        for _name, _p in model.named_parameters():
            if not _p.requires_grad:
                continue
            if torch.isnan(_p).any() or torch.isinf(_p).any():
                raise RuntimeError(
                    f"[CPU] Peso '{_name}' é NaN/Inf antes de mover para CUDA. "
                    "Bug de inicialização — revise _init_weights."
                )

        _device = "cuda" if torch.cuda.is_available() else "cpu"
        model = model.to(_device)

        # Verificar CUDA: se o peso ficou NaN/Inf só após .to("cuda") → contexto corrompido
        for _name, _p in model.named_parameters():
            if not _p.requires_grad:
                continue
            if torch.isnan(_p).any() or torch.isinf(_p).any():
                raise RuntimeError(
                    f"[CUDA] Peso '{_name}' tornou-se NaN/Inf após .to(cuda). "
                    "Contexto CUDA corrompido → Kernel → Restart → Run All Cells."
                )
        
        print(f"\n===== Fold {fold + 1} / {k} =====")

        # 3. Selecionar os dados (Dataset, não list)
        train_split = full_data.select(train_idx.tolist())
        val_split = full_data.select(val_idx.tolist())
        
        # 4. Tokenizar novamente usando sua função existente
        train_data, valid_data = nerdataset.create_data(train_split, val_split)
        

        #train_data = train_data.shuffle(seed=42).select(range(400))
        #valid_data = valid_data.shuffle(seed=42).select(range(200))
        training_args = TrainingArguments(
            # output_dir por fold: evita conflito no load_best_model_at_end
            output_dir=f"./parser_{name_model.replace('/', '_')}/fold_{fold}",
            fp16=False,
            bf16=False,  # desativar até estabilizar; reativar após confirmar convergência
            eval_strategy="epoch",
            learning_rate=learning_rate,
            num_train_epochs=num_train_epochs,
            weight_decay=weight_decay,
            warmup_ratio=warmup_ratio,   # TODO: migrar para warmup_steps
            max_grad_norm=1.0,  # biaffine com 3 losses somados: 1.0 é seguro
            lr_scheduler_type="linear",
            logging_strategy="epoch",
            save_strategy="epoch",
            save_total_limit=1,
            load_best_model_at_end=True,  # necessário para EarlyStoppingCallback funcionar
            metric_for_best_model="las",
            greater_is_better=True,
            label_smoothing_factor=0.0,
            gradient_checkpointing=False, # incompatível com biaffine em alguns casos
            remove_unused_columns=False,  # obrigatório — modelo recebe labels customizadas
            label_names=["deprel_label", "upos_label", "head_label"],
            report_to="wandb",
            per_device_train_batch_size=16,
            per_device_eval_batch_size=32,
            dataloader_num_workers=4,
        )

        early_stop_callback = EarlyStoppingCallback(5)
        # Inicializa o Trainer
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_data,
            eval_dataset=valid_data,
            #tokenizer=tokenizer,          # opcional
            compute_metrics=compute_metrics,
            data_collator=data_collator,  # opcional
            callbacks=[early_stop_callback]  # se você quiser usar callbacks
        )


        trainer.train()
        eval_result = trainer.evaluate()

        result_dict = {
            "name": name_model,
            "Fold": fold+1,
            "trial_number": trial.number,
            "hyperparameters": {
                "learning_rate": learning_rate,
                "num_train_epochs": num_train_epochs,
                "weight_decay": weight_decay,
                "warmup_ratio": warmup_ratio,
                "label_smoothing_factor": label_smoothing_factor
            },
            "las": eval_result["eval_las"],
        }

        save_result_to_json(result_dict)
        print(f"Fold {fold + 1} metrics:", eval_result)

In [39]:

'''def objective(trial, name_model, train_data, valid_data, tokenizer=None, data_collator=None, optuna_count=0, name="model_run"):
    # Hiperparâmetros sugeridos pelo Optuna
    forbidden_configs = {
    (0.2147035642975132, 1.7109988776595992e-05, 0.41601400434863894),
    (0.2147035642975132, 2.208391537977642e-05, 0.41601400434863894),
    (0.2147035642975132, 2.5771715479732614e-05, 0.41601400434863894),
    (0.2147035642975132, 2.3346341563131348e-05, 0.41601400434863894),
    (0.2147035642975132, 4.818415253407452e-05, 0.41601400434863894),
}
    while True:
        learning_rate = trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True)
        weight_decay = trial.suggest_float("weight_decay", 0.1, 0.3)
        warmup_ratio = trial.suggest_float("warmup_ratio", 0.3, 0.5)
        num_train_epochs = trial.suggest_int("num_train_epochs", 40, 40)
        config = (weight_decay, learning_rate, warmup_ratio)

        if config not in forbidden_configs:
            break  # valor válido


    import os
    os.environ["WANDB_API_KEY"] = "7499f50c2fffad3ce3e34b7b7b02152988a1742c"

    import wandb
    
    #wandb.init(project="bracis", entity="gdlima")
    run = wandb.init(
        # Set the wandb entity where your project will be logged (generally your team name).
        entity="gdlima-universidade-federal-de-pelotas",
        # Set the wandb project where this run will be logged.
        project="bracis",
        # Track hyperparameters and run metadata.
        config={
            "learning_rate": learning_rate,
            "architecture": name_model,
            "epochs": num_train_epochs,
            "weight_decay": weight_decay,
            "warmup_ratio": warmup_ratio,
        },
    )
    #kf = KFold(n_splits=k, shuffle=True, random_state=42)

    # Suponha que seus dados estejam assim:
    # data = {'train': list de exemplos, 'val': list de exemplos}

    # 1. Juntar tudo em um único data
    #full_data = concatenate_datasets([train_data, valid_data])
    #full_data = concatenate_datasets([data['train'], data['val']])
    # Converter para numpy array só para facilitar a indexação
    #indices = np.arange(len(full_data))

    #for fold, (train_idx, val_idx) in enumerate(kf.split(full_data)):


    config = AutoConfig.from_pretrained(name_model)

    model = MultiTaskSentencePredictionEncoder.from_pretrained(
            name_model,
            config=config,
            num_deprel_labels=len(DEPREL_LABELS),
            num_upos_labels=len(UPOS_LABELS)
        ).to("cuda" if torch.cuda.is_available() else "cpu")
        
        #print(f"\n===== Fold {fold + 1} / {k} =====")

        # 3. Selecionar os dados (Dataset, não list)
        #train_split = full_data.select(train_idx.tolist())
        #val_split = full_data.select(val_idx.tolist())

        # 4. Tokenizar novamente usando sua função existente
    #train_data, valid_data = nerdataset.create_data(train_split, val_split)


        # Setup training arguments
    training_args = TrainingArguments(
            #output_dir= f'./ettin-decoder-150m_parser',
            eval_strategy=evaluation_strategy,
            learning_rate=learning_rate,
            num_train_epochs=num_train_epochs,
            weight_decay=weight_decay,
            logging_dir=logging_dir,
            label_names=label_names,
            max_grad_norm=max_grad_norm,
            lr_scheduler_type=lr_scheduler_type,
            warmup_ratio=warmup_ratio,
            logging_strategy=logging_strategy,
            save_strategy=save_strategy,
            save_total_limit=save_total_limit,
            #load_best_model_at_end=load_best_model_at_end,
            metric_for_best_model=metric_for_best_model,
            greater_is_better=greater_is_better,
            label_smoothing_factor=label_smoothing_factor,
            #report_to=report_to,
            #per_device_train_batch_size=per_device_batch_size,
            gradient_checkpointing=gradient_checkpointing,
            remove_unused_columns=remove_unused_columns,
        )

        
        # Inicializa o Trainer
    trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_data,  # Limitando o treinamento para 10 exemplos
            eval_dataset=valid_data,   # Limitando a avaliação para 10 exemplos
            #tokenizer=tokenizer,          # opcional
            compute_metrics=compute_metrics,
            data_collator=data_collator,  # opcional
            # callbacks=[early_stop_callback]  # se você quiser usar callbacks
        )


    trainer.train()
    eval_result = trainer.evaluate()
    print(eval_result)
    result_dict = {
            "name": name_model,
            "Fold": optuna_count,
            "trial_number": trial.number,
            "hyperparameters": {
                "learning_rate": learning_rate,
                "num_train_epochs": num_train_epochs,
            },
            "las": eval_result["eval_las"],
        }

    save_result_to_json(result_dict)
    print(f"Optuna {optuna_count + 1} metrics:", eval_result)
    '''

'def objective(trial, name_model, train_data, valid_data, tokenizer=None, data_collator=None, optuna_count=0, name="model_run"):\n    # Hiperparâmetros sugeridos pelo Optuna\n    forbidden_configs = {\n    (0.2147035642975132, 1.7109988776595992e-05, 0.41601400434863894),\n    (0.2147035642975132, 2.208391537977642e-05, 0.41601400434863894),\n    (0.2147035642975132, 2.5771715479732614e-05, 0.41601400434863894),\n    (0.2147035642975132, 2.3346341563131348e-05, 0.41601400434863894),\n    (0.2147035642975132, 4.818415253407452e-05, 0.41601400434863894),\n}\n    while True:\n        learning_rate = trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True)\n        weight_decay = trial.suggest_float("weight_decay", 0.1, 0.3)\n        warmup_ratio = trial.suggest_float("warmup_ratio", 0.3, 0.5)\n        num_train_epochs = trial.suggest_int("num_train_epochs", 40, 40)\n        config = (weight_decay, learning_rate, warmup_ratio)\n\n        if config not in forbidden_configs:\n            break  # valor válido\n\n\n    import os\n    os.environ["WANDB_API_KEY"] = "7499f50c2fffad3ce3e34b7b7b02152988a1742c"\n\n    import wandb\n    \n    #wandb.init(project="bracis", entity="gdlima")\n    run = wandb.init(\n        # Set the wandb entity where your project will be logged (generally your team name).\n        entity="gdlima-universidade-federal-de-pelotas",\n        # Set the wandb project where this run will be logged.\n        project="bracis",\n        # Track hyperparameters and run metadata.\n        config={\n            "learning_rate": learning_rate,\n            "architecture": name_model,\n            "epochs": num_train_epochs,\n            "weight_decay": weight_decay,\n            "warmup_ratio": warmup_ratio,\n        },\n    )\n    #kf = KFold(n_splits=k, shuffle=True, random_state=42)\n\n    # Suponha que seus dados estejam assim:\n    # data = {\'train\': list de exemplos, \'val\': list de exemplos}\n\n    # 1. Juntar tudo em um único data\n    #full_data = concatenate_datasets([train_data, valid_data])\n    #full_data = concatenate_datasets([data[\'train\'], data[\'val\']])\n    # Converter para numpy array só para facilitar a indexação\n    #indices = np.arange(len(full_data))\n\n    #for fold, (train_idx, val_idx) in enumerate(kf.split(full_data)):\n\n\n    config = AutoConfig.from_pretrained(name_model)\n\n    model = MultiTaskSentencePredictionEncoder.from_pretrained(\n            name_model,\n            config=config,\n            num_deprel_labels=len(DEPREL_LABELS),\n            num_upos_labels=len(UPOS_LABELS)\n        ).to("cuda" if torch.cuda.is_available() else "cpu")\n        \n        #print(f"\n===== Fold {fold + 1} / {k} =====")\n\n        # 3. Selecionar os dados (Dataset, não list)\n        #train_split = full_data.select(train_idx.tolist())\n        #val_split = full_data.select(val_idx.tolist())\n\n        # 4. Tokenizar novamente usando sua função existente\n    #train_data, valid_data = nerdataset.create_data(train_split, val_split)\n\n\n        # Setup training arguments\n    training_args = TrainingArguments(\n            #output_dir= f\'./ettin-decoder-150m_parser\',\n            eval_strategy=evaluation_strategy,\n            learning_rate=learning_rate,\n            num_train_epochs=num_train_epochs,\n            weight_decay=weight_decay,\n            logging_dir=logging_dir,\n            label_names=label_names,\n            max_grad_norm=max_grad_norm,\n            lr_scheduler_type=lr_scheduler_type,\n            warmup_ratio=warmup_ratio,\n            logging_strategy=logging_strategy,\n            save_strategy=save_strategy,\n            save_total_limit=save_total_limit,\n            #load_best_model_at_end=load_best_model_at_end,\n            metric_for_best_model=metric_for_best_model,\n            greater_is_better=greater_is_better,\n            label_smoothing_factor=label_smoothing_factor,\n            #report_to=report_to,\n            #per_device_train_batch_size=per_device_batch_size,\n            gradient_checkpointing=gradient_checkpointing,\n            remove_unused_columns=remove_unused_columns,\n        )\n\n        \n        # Inicializa o Trainer\n    trainer = Trainer(\n            model=model,\n            args=training_args,\n            train_dataset=train_data,  # Limitando o treinamento para 10 exemplos\n            eval_dataset=valid_data,   # Limitando a avaliação para 10 exemplos\n            #tokenizer=tokenizer,          # opcional\n            compute_metrics=compute_metrics,\n            data_collator=data_collator,  # opcional\n            # callbacks=[early_stop_callback]  # se você quiser usar callbacks\n        )\n\n\n    trainer.train()\n    eval_result = trainer.evaluate()\n    print(eval_result)\n    result_dict = {\n            "name": name_model,\n            "Fold": optuna_count,\n            "trial_number": trial.number,\n            "hyperparameters": {\n                "learning_rate": learning_rate,\n                "num_train_epochs": num_train_epochs,\n            },\n            "las": eval_result["eval_las"],\n        }\n\n    save_result_to_json(result_dict)\n    print(f"Optuna {optuna_count + 1} metrics:", eval_result)\n    '

In [40]:
# Crear estudio y optimizar
study = optuna.create_study(direction="maximize")

[I 2026-06-15 09:26:27,864] A new study created in memory with name: no-name-f948ef1c-e3cb-4d92-94f2-6fd7d07c7d35

In [41]:
'''#Decoder
import torch
import gc

def limpar_gpu():
    gc.collect()                                # Limpa lixo da CPU
    torch.cuda.empty_cache()                    # Libera cache da GPU
    torch.cuda.ipc_collect()                    # Coleta memória interprocessos
    torch.cuda.reset_peak_memory_stats()        # Reseta estatísticas de memória
    torch.cuda.synchronize()                    # Garante execução sincronizada

# Exemplo de uso antes do treinamento
if torch.cuda.is_available():
    limpar_gpu()'''

'#Decoder\nimport torch\nimport gc\n\ndef limpar_gpu():\n    gc.collect()                                # Limpa lixo da CPU\n    torch.cuda.empty_cache()                    # Libera cache da GPU\n    torch.cuda.ipc_collect()                    # Coleta memória interprocessos\n    torch.cuda.reset_peak_memory_stats()        # Reseta estatísticas de memória\n    torch.cuda.synchronize()                    # Garante execução sincronizada\n\n# Exemplo de uso antes do treinamento\nif torch.cuda.is_available():\n    limpar_gpu()'

In [42]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [43]:
'''models_decoder = ["maritaca-ai/sabia-7b" , "nicholasKluge/TeenyTinyLlama-460m", "TucanoBR/Tucano-630m", "https://huggingface.co/adalbertojunior/bart-base-portuguese"]


for model_name in models_decoder:
# Otimização
    study.optimize(
        lambda trial: objective(trial, MultiTaskSentencePrediction.from_pretrained(
        model_name,
        config=config,
        num_deprel_labels=len(DEPREL_LABELS),
        num_upos_labels=len(UPOS_LABELS)
    ).to(device), train_data, valid_data,  data_collator),
        n_trials=5
    )'''

'models_decoder = ["maritaca-ai/sabia-7b" , "nicholasKluge/TeenyTinyLlama-460m", "TucanoBR/Tucano-630m", "https://huggingface.co/adalbertojunior/bart-base-portuguese"]\n\n\nfor model_name in models_decoder:\n# Otimização\n    study.optimize(\n        lambda trial: objective(trial, MultiTaskSentencePrediction.from_pretrained(\n        model_name,\n        config=config,\n        num_deprel_labels=len(DEPREL_LABELS),\n        num_upos_labels=len(UPOS_LABELS)\n    ).to(device), train_data, valid_data,  data_collator),\n        n_trials=5\n    )'

In [44]:
from transformers import AutoModel, AutoConfig
from transformers import BertConfig


def build_model(model_name, num_deprel_labels, num_upos_labels):

    config = AutoConfig.from_pretrained(model_name)
    
    model = MultiTaskSentencePrediction.from_pretrained(
    model_name,
    config=config,
    num_deprel_labels=len(DEPREL_LABELS),
    num_upos_labels=len(UPOS_LABELS)
)

    return model

In [45]:
!pip install numpy==1.24.2

Requirement already satisfied: numpy==1.24.2 in ./.venv/lib/python3.10/site-packages (1.24.2)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [46]:
!pip install protobuf==3.20.3

Collecting protobuf==3.20.3
  Using cached protobuf-3.20.3-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (679 bytes)
Using cached protobuf-3.20.3-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)

Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 7.35.0
    Uninstalling protobuf-7.35.0:
      Successfully uninstalled protobuf-7.35.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wandb 0.27.2 requires protobuf!=5.28.0,!=5.29.0,<8,>4.21.0, but you have protobuf 3.20.3 which is incompatible.
Successfully installed protobuf-3.20.3

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [47]:
!export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

In [48]:
!export WANDB_NOTEBOOK_NAME="optuna_models"

In [49]:
!pip install --upgrade wandb

Requirement already satisfied: wandb in ./.venv/lib/python3.10/site-packages (0.27.2)

Requirement already satisfied: click>=8.2.0 in ./.venv/lib/python3.10/site-packages (from wandb) (8.3.3)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in ./.venv/lib/python3.10/site-packages (from wandb) (3.1.47)
Requirement already satisfied: packaging in ./.venv/lib/python3.10/site-packages (from wandb) (26.2)
Requirement already satisfied: platformdirs in ./.venv/lib/python3.10/site-packages (from wandb) (4.9.6)

Collecting protobuf!=5.28.0,!=5.29.0,<8,>4.21.0 (from wandb)

  Using cached protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: pydantic<3,>=2.6 in ./.venv/lib/python3.10/site-packages (from wandb) (2.13.3)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.10/site-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in ./.venv/lib/python3.10/site-packages (from wandb) (2.33.1)
Requirement already satisfied: sentry-sdk>=2.0.0 in ./.venv/lib/python3.10/site-packages (from wandb) (2.58.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in ./.venv/lib/python3.10/site-packages (from wandb) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.10/site-packages (from pydantic<3,>=2.6->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in ./.venv/lib/python3.10/site-packages (from pydantic<3,>=2.6->wandb) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.10/site-packages (from pydantic<3,>=2.6->wandb) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2026.4.22)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.venv/lib/python3.10/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in ./.venv/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.3)
Using cached protobuf-7.35.1-cp310-abi3-manylinux2014_x86_64.whl (327 kB)

Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:

      Successfully uninstalled protobuf-3.20.3

Successfully installed protobuf-7.35.1

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [50]:
from transformers import set_seed

set_seed(42)

In [51]:
import os
import random
import numpy as np
import torch

def seed_everything(seed: int = 42):
    # Python
    random.seed(seed)
    
    # Numpy
    np.random.seed(seed)
    
    # PyTorch (CPU)
    torch.manual_seed(seed)
    
    # PyTorch (GPU)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Determinismo (importante!)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    
    # Algumas libs usam isso
    os.environ["PYTHONHASHSEED"] = str(seed)
    
    # Para transformers (às vezes ajuda)
    os.environ["TOKENIZERS_PARALLELISM"] = "false"

    print(f"Seed definida como {seed}")

# Uso
seed_everything(42)

Seed definida como 42

In [52]:
#models_encoder = ["neuralmind/bert-base-portuguese-cased", "google-bert/bert-base-multilingual-cased", "neuralmind/bert-large-portuguese-cased"]
models_encoder = ["amadeusai/modernJabuticaBERT-Base-1k"]
#models_encoder = ["google-bert/bert-base-multilingual-cased"] #, "neuralmind/bert-large-portuguese-cased"]
#models_encoder = ["google-bert/bert-base-multilingual-cased", "neuralmind/bert-large-portuguese-cased" , "distilbert/distilbert-base-uncased", "google-bert/bert-large-uncased"]

optuna_count = 0
#print(len(train_data))

#train_data = train_data.shuffle(seed=42).select(range(1000))
#valid_data = valid_data.shuffle(seed=42).select(range(1000))
for model_name in models_encoder:   

    study = optuna.create_study(direction="maximize")

    print("="*50)
    print(f'Modelo: {model_name}')
    print("="*50)

    study.optimize(
        lambda trial: objective(
            trial,
            model_name,
            train_data,
            valid_data,
            data_collator,
            #optuna_count=optuna_count  # Passando o valor atual de optuna_count
        ),
        n_trials=10
    )

    # Incrementar optuna_count após a execução de cada trial
    optuna_count += 1

[I 2026-06-15 09:26:31,715] A new study created in memory with name: no-name-71851516-8f8b-4d1e-a0a5-fa484b8b25e7

==================================================
Modelo: amadeusai/modernJabuticaBERT-Base-1k
==================================================

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.

wandb: Currently logged in as: gdlima (gdlima-universidade-federal-de-pelotas) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_092633-voh8ps4j
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/voh8ps4j

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 11385.33it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1874.87 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2538.42 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2815.69 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 3002.59 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3022.13 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3062.30 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2853.63 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1954.43 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2236.97 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2149.12 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.37s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.37s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.06s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.06s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.05s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Fold 1 metrics: {'eval_loss': 1.623014211654663, 'eval_uas': 0.7512677420176846, 'eval_las': 0.7292255943735189, 'eval_upos_accuracy': 0.9786458731493515}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading history steps 77-79, summary, console lines 56-58; uploading wandb-summary.json; uploading config.yaml; uploading output.log

wandb: uploading data

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇▇▇███████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▁▃▇▄▃▅▆▄▆▅▆▅▆▅▆▅█▅▅▆▆▅▇▅▅▅▆▅▆▅▇▇▇▅▇▆▆▅▇▅
wandb: eval/samples_per_second █▆▂▅▆▃▃▅▃▄▃▄▃▄▃▄▁▄▄▃▃▄▂▄▄▄▃▄▃▄▂▂▂▄▂▃▃▄▂▄
wandb:   eval/steps_per_second █▆▂▅▆▃▃▅▃▄▃▄▃▄▃▄▁▄▄▃▃▄▂▄▄▄▃▃▃▄▂▂▂▄▂▃▂▄▂▄
wandb:                eval/uas ▁▂▂▂▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇▇▇█▇█████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▆▆▆▇▇▇▇██
wandb:       train/global_step ▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇██
wandb:         train/grad_norm █▂▂▂▃▂▃▂▂▂▃▄▄▃▄▃▃▅▂▂▃▃▃▄▃▂▁▁▁▂▂▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.72923
wandb:               eval/loss 1.62301
wandb:            eval/runtime 7.3679
wandb: eval/samples_per_second 182.82
wandb:   eval/steps_per_second 5.836
wandb:                eval/uas 0.75127
wandb:      eval/upos_accuracy 0.97865
wandb:              total_flos 7.135095905162035e+16
wandb:             train/epoch 39
wandb:       train/global_step 13143
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/voh8ps4j
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_092633-voh8ps4j/logs

wandb: setting up run rck8k1hc

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_102619-rck8k1hc
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/rck8k1hc

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 6472.84it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1938.10 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2615.20 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2914.69 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 3156.70 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3165.64 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3229.64 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2986.70 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 2057.01 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2294.61 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Fold 2 metrics: {'eval_loss': 1.6989049911499023, 'eval_uas': 0.7434647196977433, 'eval_las': 0.7229909118758296, 'eval_upos_accuracy': 0.9793219646686409}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading config.yaml

wandb: uploading history steps 81-81, summary, console lines 58-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▆▆▇▇▇▇▇█████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▂▅▁▃▃▆▄▄▁▅▄▅▃▇▆█▄▆▁▃▂▇▇▅▅▄▃▆▅▅▅▄▂▃▄▆▃▄▂
wandb: eval/samples_per_second ▄▇▄█▆▆▃▅▅█▄▅▄▆▂▃▁▅▃█▆▇▂▂▄▄▅▆▃▄▄▄▅▇▆▅▃▆▅▇
wandb:   eval/steps_per_second ▄▇▄█▆▆▃▅▅█▄▅▄▆▂▃▁▅▃█▆▇▂▂▄▄▅▆▃▄▄▄▅▇▆▅▃▆▅▇
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇█████████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇███
wandb:       train/global_step ▁▁▁▁▂▂▂▂▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇██████
wandb:         train/grad_norm ▅▃▃▃▃▃▃▃▇▅▄▅██▅▇▇▄▆▃▃▄▄▅▄▄▃▅▄▅█▅▂▁▂▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.72299
wandb:               eval/loss 1.6989
wandb:            eval/runtime 7.3848
wandb: eval/samples_per_second 182.402
wandb:   eval/steps_per_second 5.823
wandb:                eval/uas 0.74346
wandb:      eval/upos_accuracy 0.97932
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/rck8k1hc
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_102619-rck8k1hc/logs

wandb: setting up run b1ualcw7

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_112738-b1ualcw7
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/b1ualcw7

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10567.18it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1985.66 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2692.23 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2978.69 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 3214.11 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3302.83 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3341.12 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3077.82 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 2050.96 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2289.63 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Fold 3 metrics: {'eval_loss': 1.4769848585128784, 'eval_uas': 0.7648001628208716, 'eval_las': 0.7434553641844964, 'eval_upos_accuracy': 0.979774594855878}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 71-73, summary, console lines 53-55

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇███████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▄▇▃▅▆▃▂▆▄▆▅█▆▆▅▅▄▆▄▆▃▆▂▅▁▅▅▄▆▂▄▅▇▅▃▃
wandb: eval/samples_per_second ▃▅▂▆▄▃▆▇▃▅▃▄▁▃▃▄▄▅▃▅▃▆▃▇▄█▄▄▅▃▇▅▄▂▄▆▆
wandb:   eval/steps_per_second ▃▅▂▆▄▃▆▇▃▅▃▄▁▃▃▄▄▅▃▅▃▆▃▆▄█▄▄▅▃▇▅▄▂▃▆▆
wandb:                eval/uas ▁▂▂▂▃▃▄▅▅▅▆▆▆▇▇▇▇▇▇██████████████████
wandb:      eval/upos_accuracy ▁▆▇██████████████████████████████████
wandb:             train/epoch ▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇████
wandb:       train/global_step ▁▁▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇███
wandb:         train/grad_norm ▂▂▂▂▂▂▂▃▂▂▃▄▃▃▃▂▂▂▂▃▂█▂▂▁▄▂▂▁▂▂▂▁▁▂▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.74346
wandb:               eval/loss 1.47698
wandb:            eval/runtime 7.3908
wandb: eval/samples_per_second 182.255
wandb:   eval/steps_per_second 5.818
wandb:                eval/uas 0.7648
wandb:      eval/upos_accuracy 0.97977
wandb:              total_flos 6.586242373995725e+16
wandb:             train/epoch 36
wandb:       train/global_step 12132
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/b1ualcw7
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_112738-b1ualcw7/logs

wandb: setting up run coen4el7

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_122253-coen4el7
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/coen4el7

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 11497.59it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1949.88 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2641.59 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2943.20 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 3171.92 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3226.29 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3269.96 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3020.55 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 2008.47 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2245.38 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Fold 4 metrics: {'eval_loss': 1.578057885169983, 'eval_uas': 0.7477107753866673, 'eval_las': 0.724164465078103, 'eval_upos_accuracy': 0.9777361684664119}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading history steps 73-75, summary, console lines 54-56

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇███████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▂▄▄▅▃▅▅▅▃▂▄▂▃▂▄▁▄▄▅▃▄▂▅▂▂▅█▃▄▄▃▄▂▅▄▅▁
wandb: eval/samples_per_second ▄▇▅▅▄▆▄▄▄▆▇▅▇▆▇▅█▅▅▄▆▅▇▄▇▇▄▁▆▅▅▆▅▇▄▅▄█
wandb:   eval/steps_per_second ▄▇▅▅▄▆▄▄▄▆▇▅▇▆▇▅█▅▅▄▆▅▇▄▇▇▄▁▆▅▅▆▅▇▄▅▄█
wandb:                eval/uas ▁▁▂▂▃▃▄▄▅▅▆▆▆▇▇▇▇▇▇███████████████████
wandb:      eval/upos_accuracy ▁▅▇███████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:       train/global_step ▁▁▂▂▂▂▂▂▃▃▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▇▇▇▇███
wandb:         train/grad_norm ▅▃▄▃▄▃▆▄▇▅▄▃█▄█▅▄▅▃▄▇▆▅▃▅▄▃▂▆▁▃▂▁▁▂▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.72416
wandb:               eval/loss 1.57806
wandb:            eval/runtime 7.369
wandb: eval/samples_per_second 182.793
wandb:   eval/steps_per_second 5.835
wandb:                eval/uas 0.74771
wandb:      eval/upos_accuracy 0.97774
wandb:              total_flos 6.769193551051162e+16
wandb:             train/epoch 37
wandb:       train/global_step 12469
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/coen4el7
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_122253-coen4el7/logs

wandb: setting up run 2phtfe4y

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_131938-2phtfe4y
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/2phtfe4y

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10146.90it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1952.07 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2649.62 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2935.41 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 3146.42 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3234.76 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3273.73 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3019.67 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 2011.07 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2336.62 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2239.68 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

[W 2026-06-15 14:17:53,633] Trial 0 failed with parameters: {'learning_rate': 2.2076272493378065e-05, 'weight_decay': 0.22724207286292505, 'warmup_ratio': 0.35998885257401414, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-15 14:17:53,634] Trial 0 failed with value None.

Fold 5 metrics: {'eval_loss': 1.6326066255569458, 'eval_uas': 0.7325197378605707, 'eval_las': 0.7122142525414108, 'eval_upos_accuracy': 0.9800815315547758}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading history steps 75-77, summary, console lines 55-59; uploading wandb-summary.json; uploading config.yaml; uploading output.log

wandb: uploading wandb-summary.json; uploading output.log

wandb: uploading data

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▇▇▇▇▇▇▇████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▂▃▂█▃▄▄▄▄▃▃▃▅▃▃▅▃▃▄▃▄▅▂▁▄▄▃▄▆▃▃▅▅▃▄▃▃▅▂
wandb: eval/samples_per_second ▇▆▇▁▆▅▅▅▅▆▆▆▄▆▆▄▆▆▅▆▅▄▇█▅▅▆▅▃▆▆▄▄▆▅▆▆▄▇
wandb:   eval/steps_per_second ▇▆▇▁▆▅▅▅▅▆▆▆▄▆▆▄▆▆▅▆▅▄██▅▅▆▅▃▆▆▄▄▆▅▆▆▄▇
wandb:                eval/uas ▁▂▂▂▃▃▄▅▅▆▆▆▇▇▇▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▅▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▂▂▃▃▃▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇████
wandb:         train/grad_norm ▄▄▄▄▄▄▃▆▄▅▄▇▄▅▅▄█▆▇▄▅▅▃▃▇▅▆▄▄▆▂▃▃▂▂▂▂▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.71221
wandb:               eval/loss 1.63261
wandb:            eval/runtime 7.3737
wandb: eval/samples_per_second 182.676
wandb:   eval/steps_per_second 5.832
wandb:                eval/uas 0.73252
wandb:      eval/upos_accuracy 0.98008
wandb:              total_flos 6.952144728106598e+16
wandb:             train/epoch 38
wandb:       train/global_step 12806
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial0_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/2phtfe4y
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_131938-2phtfe4y/logs

wandb: setting up run s30b6qww

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_141755-s30b6qww
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/s30b6qww

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 11692.29it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1956.19 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2567.35 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2806.51 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2979.09 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3050.08 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3047.90 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2860.43 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1979.38 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2226.78 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2149.60 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Fold 1 metrics: {'eval_loss': 1.4655752182006836, 'eval_uas': 0.8436154218586754, 'eval_las': 0.8238921591111791, 'eval_upos_accuracy': 0.9819330836072675}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 80-81, summary, console lines 58-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▅▅▆▆▆▇▆▇▇▇▇▇▇██▇██████████████████
wandb:               eval/loss █▅▄▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▄▄▁▅▇▇▅▆▄▄▅▅▃▃▆▇▇▄▄▆▅▄▃▆▄▁▃█▄▃▆▄▇▅▃▃▁▂▂▂
wandb: eval/samples_per_second ▅▅█▄▂▂▄▃▅▅▄▄▆▆▃▂▂▅▅▃▄▅▆▃▅█▆▁▅▆▃▅▂▄▆▆█▇▇▇
wandb:   eval/steps_per_second ▅▅█▄▂▂▄▃▅▅▄▄▆▆▃▂▂▅▅▃▄▅▆▃▅█▆▁▅▆▃▅▂▄▆▆█▇▇▇
wandb:                eval/uas ▁▂▂▃▄▄▅▅▆▆▆▇▆▆▆▇▇▇▇██▇██████████████████
wandb:      eval/upos_accuracy ▁▇▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▇▇▇▇▇▇███
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇██
wandb:         train/grad_norm ▃▃▃▃▃▄▃▇▄▅▄▄█▂▅▄▄▂▂▄▃▁▃▂▄▁▃▂▂▁▂▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.82389
wandb:               eval/loss 1.46558
wandb:            eval/runtime 7.3823
wandb: eval/samples_per_second 182.463
wandb:   eval/steps_per_second 5.825
wandb:                eval/uas 0.84362
wandb:      eval/upos_accuracy 0.98193
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/s30b6qww
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_141755-s30b6qww/logs

wandb: setting up run 6heauhgm

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_151922-6heauhgm
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/6heauhgm

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 7542.50it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1909.06 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2526.46 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2821.10 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2981.78 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3050.99 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3010.16 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2835.71 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 2001.11 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2208.60 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2140.49 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Fold 2 metrics: {'eval_loss': 1.409995436668396, 'eval_uas': 0.8322271009905035, 'eval_las': 0.8120851628714388, 'eval_upos_accuracy': 0.9834065148575513}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading wandb-summary.json; uploading config.yaml; uploading output.log

wandb: uploading history steps 79-81, summary, console lines 57-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▅▆▆▅▆▇▇▇▇▇▇▇██▇███████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▂▄▆▅▇▇▄▃▂▄▄▂▆▄▆▄▁▅▆▆▅▄▁▃▄█▇▅▆▄▄▅▅█▃▇▆▆▇▂
wandb: eval/samples_per_second ▇▅▃▄▂▂▅▆▇▅▅▇▃▅▃▅█▄▃▃▄▅█▆▅▁▂▄▃▅▅▄▄▁▆▂▃▃▂▇
wandb:   eval/steps_per_second ▇▅▃▄▂▂▅▆▇▅▅▆▃▄▃▅█▄▃▃▄▅█▆▅▁▂▄▃▅▄▄▄▁▆▂▃▃▂▇
wandb:                eval/uas ▁▂▂▃▃▄▅▆▆▅▆▇▇▇▇▇▇▇██▇███████████████████
wandb:      eval/upos_accuracy ▁▇▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇▇███
wandb:       train/global_step ▁▁▁▁▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇▇███
wandb:         train/grad_norm ▃▂▃▃▃▃▅▃▃▄▃▃▄▂▄▄▄▆▃▃█▃▂▂▂▂▂▃▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.81209
wandb:               eval/loss 1.41
wandb:            eval/runtime 7.3784
wandb: eval/samples_per_second 182.559
wandb:   eval/steps_per_second 5.828
wandb:                eval/uas 0.83223
wandb:      eval/upos_accuracy 0.98341
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/6heauhgm
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_151922-6heauhgm/logs

wandb: setting up run qdmhk5kf

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_162051-qdmhk5kf
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/qdmhk5kf

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8743.71it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1892.19 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2503.39 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2788.75 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2933.45 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3028.81 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2981.35 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2808.58 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1986.97 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2207.90 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2125.80 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Fold 3 metrics: {'eval_loss': 1.3639689683914185, 'eval_uas': 0.8433612333681024, 'eval_las': 0.823288472791106, 'eval_upos_accuracy': 0.9827257231536367}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading history steps 79-81, summary, console lines 57-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▅▅▆▆▆▇▇▇▇▇▇▇▇█████████████████████
wandb:               eval/loss █▅▄▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▃▄▃▄▄▃▂▂▄▅▅▃▄▄▃▄▄▄▃▅▅▇▄▄█▃▂▃▂▂▅▃▅▃▄▆▆▇▁
wandb: eval/samples_per_second ▄▆▄▆▅▅▆▇▇▅▄▄▆▅▅▆▅▅▅▆▄▄▂▅▅▁▆▇▆▇▇▄▆▄▆▅▃▃▂█
wandb:   eval/steps_per_second ▄▆▄▆▅▅▆▇▇▅▄▄▆▅▅▆▅▅▅▆▄▄▂▅▅▁▆▇▆▇▇▄▆▄▆▅▃▃▂█
wandb:                eval/uas ▁▂▂▃▃▄▅▅▆▆▆▇▇▇▇▇▇▇▇█████████████████████
wandb:      eval/upos_accuracy ▁▇▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▁▂▂▂▂▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇███
wandb:         train/grad_norm ▆▅▅▅▆██▅▇▇██▆▆▄▇█▇▅▄▃▄▂▇▃▂▃▂▁▂▂▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.82329
wandb:               eval/loss 1.36397
wandb:            eval/runtime 7.3797
wandb: eval/samples_per_second 182.528
wandb:   eval/steps_per_second 5.827
wandb:                eval/uas 0.84336
wandb:      eval/upos_accuracy 0.98273
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/qdmhk5kf
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_162051-qdmhk5kf/logs

wandb: setting up run pg5exk05

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_172222-pg5exk05
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/pg5exk05

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9698.48it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1872.50 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2490.11 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2717.44 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2880.76 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2923.91 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2918.06 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2751.07 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1932.30 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2177.72 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2099.07 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Fold 4 metrics: {'eval_loss': 1.2470134496688843, 'eval_uas': 0.8489752994587939, 'eval_las': 0.830866699156129, 'eval_upos_accuracy': 0.9837638187088004}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 75-75, summary, console lines 55-56

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▅▆▆▆▆▆▆▆▇▇▇▇▇███▇███████████████
wandb:               eval/loss █▅▄▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▅▅▄▃▆▅▄▄▅▃▂▂█▅▄▅▅▄▃▅▄▄▅█▄▃▄▃▃▅▆▄▂▄▄▅▁
wandb: eval/samples_per_second ▄▄▄▅▆▃▄▅▅▄▆▇▇▁▄▅▄▄▅▆▄▅▅▄▁▅▆▅▆▆▄▃▅▇▅▅▄█
wandb:   eval/steps_per_second ▄▄▄▅▆▃▄▅▅▄▆▇▇▁▄▅▄▄▅▆▄▅▅▄▁▅▆▅▆▆▄▃▅▇▅▅▄█
wandb:                eval/uas ▁▂▂▃▄▄▅▅▆▆▆▆▆▆▇▇▇▇▇███▇███████████████
wandb:      eval/upos_accuracy ▁▇▇███████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▅▅▆▆▆▆▆▇▇▇▇██████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇████
wandb:         train/grad_norm ▄▄▄▆▇▅▄▆▇▅▆▆██▄▆▃▃▃▃▃▃▆▂▂▂▂▂▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.83087
wandb:               eval/loss 1.24701
wandb:            eval/runtime 7.3801
wandb: eval/samples_per_second 182.517
wandb:   eval/steps_per_second 5.826
wandb:                eval/uas 0.84898
wandb:      eval/upos_accuracy 0.98376
wandb:              total_flos 6.769193551051162e+16
wandb:             train/epoch 37
wandb:       train/global_step 12469
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/pg5exk05
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_172222-pg5exk05/logs

wandb: setting up run c7zkj6to

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_181917-c7zkj6to
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/c7zkj6to

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 11627.46it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1928.07 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2553.27 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2805.17 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2972.52 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3051.27 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3045.13 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2849.56 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1983.46 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2239.07 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2149.08 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

[W 2026-06-15 19:20:45,811] Trial 1 failed with parameters: {'learning_rate': 4.624074284210462e-05, 'weight_decay': 0.2749016191911278, 'warmup_ratio': 0.3462195571042849, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-15 19:20:45,812] Trial 1 failed with value None.

Fold 5 metrics: {'eval_loss': 1.491784930229187, 'eval_uas': 0.8185922906238712, 'eval_las': 0.8002734919242479, 'eval_upos_accuracy': 0.9836678879199133}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▅▆▆▆▆▇▇▇▇▇▇▇██████████████████████
wandb:               eval/loss █▅▄▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▂▃▃▂▄▅▁▂▆▂▃▄▇▇▆▅▅▂▅▄▃▄▂▅▂█▆▂█▄▃▄▅▅▇▆▂▇▂
wandb: eval/samples_per_second ▆▇▆▆▇▅▄█▇▃▇▆▅▂▂▃▄▄▇▄▅▆▅▇▄▇▁▃▇▁▅▆▅▄▄▂▃▇▂▇
wandb:   eval/steps_per_second ▆▇▆▆▇▅▄█▇▃▇▆▅▂▂▃▄▄▇▄▅▆▅▇▄▇▁▃▇▁▅▆▅▄▄▂▃▇▂▇
wandb:                eval/uas ▁▂▂▃▄▄▅▅▆▆▆▇▇▇▇▇▇▇██████████████████████
wandb:      eval/upos_accuracy ▁▇▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇██
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇████
wandb:         train/grad_norm ▃▄▃▄▄▃▄▄▄██▄▅▄▆▃▄▃▄▇▃▂▂▂▂▂▂▁▁▃▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.80027
wandb:               eval/loss 1.49178
wandb:            eval/runtime 7.3978
wandb: eval/samples_per_second 182.082
wandb:   eval/steps_per_second 5.813
wandb:                eval/uas 0.81859
wandb:      eval/upos_accuracy 0.98367
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial1_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/c7zkj6to
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_181917-c7zkj6to/logs

wandb: setting up run 0r6a8fcz

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_192047-0r6a8fcz
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/0r6a8fcz

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10437.27it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1919.53 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2538.42 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2789.89 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2945.93 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3017.01 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3002.10 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2825.67 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1935.21 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2188.80 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2106.75 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Fold 1 metrics: {'eval_loss': 1.4934067726135254, 'eval_uas': 0.801773564712178, 'eval_las': 0.7799352750809061, 'eval_upos_accuracy': 0.9792319649364217}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading config.yaml; uploading output.log

wandb: uploading history steps 73-73, summary, console lines 54-55

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▅▅▆▆▆▇▇▇▇▇▇████████████████████
wandb:               eval/loss █▅▄▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▁▂▄▆▅▃▃▄▆▄▄▆▄▆▃▃▄▆▃▃▆▃▂▆█▃▄▃▄▅▃▆▅▅▅▂
wandb: eval/samples_per_second ▄█▇▅▃▄▆▆▅▃▅▅▃▅▃▆▆▅▃▆▆▃▆▇▃▁▆▅▆▅▄▆▃▄▄▄▇
wandb:   eval/steps_per_second ▄█▇▅▃▄▆▆▅▃▅▅▃▅▃▆▆▅▃▆▆▃▆▇▃▁▆▅▆▅▄▆▃▄▄▄▇
wandb:                eval/uas ▁▂▂▃▃▄▅▅▅▆▆▆▇▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▆▇██████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇██
wandb:       train/global_step ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▆▆▇█████
wandb:         train/grad_norm █▂▂▂▂▂▂▃▂▂▂▂▂▃▂▂▃▂▁▃▁▂▁▁▂▁▁▂▁▁▁▁▂▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.77994
wandb:               eval/loss 1.49341
wandb:            eval/runtime 7.3945
wandb: eval/samples_per_second 182.162
wandb:   eval/steps_per_second 5.815
wandb:                eval/uas 0.80177
wandb:      eval/upos_accuracy 0.97923
wandb:              total_flos 6.586242373995725e+16
wandb:             train/epoch 36
wandb:       train/global_step 12132
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/0r6a8fcz
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_192047-0r6a8fcz/logs

wandb: setting up run 0z7swgd6

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_201609-0z7swgd6
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/0z7swgd6

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9111.84it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1872.83 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2480.03 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2756.24 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2905.33 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2977.61 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2944.62 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2772.92 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1940.53 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2149.02 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2080.31 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Fold 2 metrics: {'eval_loss': 1.5574744939804077, 'eval_uas': 0.7828295721433677, 'eval_las': 0.7617686102317982, 'eval_upos_accuracy': 0.9802154600224651}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 76-77, summary, console lines 56-57

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▇▆▇▇▇▇▇████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▅▆▂▅▂▁▄▆▄▆▆▆▆▆█▅▆▅▇▄▃▇▁▇▅▆▄▅▄▄▂▅▆▇▅▂█▃
wandb: eval/samples_per_second ▄▄▃▇▄▇█▅▃▅▃▃▃▃▃▁▄▃▄▂▅▆▂█▂▄▃▅▄▅▅▇▄▃▂▄▇▁▆
wandb:   eval/steps_per_second ▄▄▃▇▄▇█▅▃▅▃▃▃▃▃▁▄▃▄▂▅▆▂█▂▄▃▅▄▅▅▇▄▃▂▄▇▁▆
wandb:                eval/uas ▁▁▂▂▃▄▄▅▄▆▆▆▇▆▇▇▇▇▇█▇██████████████████
wandb:      eval/upos_accuracy ▁▅▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▆▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▃▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇█████
wandb:         train/grad_norm ▃▃▃▃▃▃▄▄▄▆▃▆▅▅▄█▄█▃▄▅▄▃▃▃▃▂▂▂▂▁▁▁▂▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.76177
wandb:               eval/loss 1.55747
wandb:            eval/runtime 7.4076
wandb: eval/samples_per_second 181.841
wandb:   eval/steps_per_second 5.805
wandb:                eval/uas 0.78283
wandb:      eval/upos_accuracy 0.98022
wandb:              total_flos 6.952144728106598e+16
wandb:             train/epoch 38
wandb:       train/global_step 12806
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/0z7swgd6
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_201609-0z7swgd6/logs

wandb: setting up run 8x8auysz

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_211435-8x8auysz
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/8x8auysz

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 7049.43it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1876.36 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2471.87 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2755.57 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2904.77 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3001.81 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2945.17 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2777.65 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1907.74 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2113.00 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2047.25 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Fold 3 metrics: {'eval_loss': 1.2939239740371704, 'eval_uas': 0.789961075635383, 'eval_las': 0.7653344188058107, 'eval_upos_accuracy': 0.9810720736764444}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading history steps 61-61, summary, console lines 48-49

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▆▆▆▆▇▇▇▇▇▇▇████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▃▇█▃▅▆█▆▄▂▄▃▄▅█▇▆▃▅▃▇▆▆▃▁▄▅▂▅▄
wandb: eval/samples_per_second ▃▆▂▁▆▄▃▁▂▅▇▅▆▅▄▁▂▃▆▄▆▂▃▃▆█▅▄▇▄▅
wandb:   eval/steps_per_second ▃▆▂▁▆▄▃▁▂▅▇▅▆▅▄▁▂▃▆▄▆▂▃▃▆█▅▄▇▄▅
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▆▇▇▇▇▇▇▇████████████
wandb:      eval/upos_accuracy ▁▆▇████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▇▇▇▇██████
wandb:       train/global_step ▁▁▁▁▁▂▂▂▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇█████
wandb:         train/grad_norm ▄▃▂▃▄▄▃▄▄▅▄█▅█▅▅▄▅▄▂▂▃▁▂▆▃▂▃▂▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.76533
wandb:               eval/loss 1.29392
wandb:            eval/runtime 7.4129
wandb: eval/samples_per_second 181.711
wandb:   eval/steps_per_second 5.801
wandb:                eval/uas 0.78996
wandb:      eval/upos_accuracy 0.98107
wandb:              total_flos 5.488535311663104e+16
wandb:             train/epoch 30
wandb:       train/global_step 10110
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/8x8auysz
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_211435-8x8auysz/logs

wandb: setting up run 9my8ruzy

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_220044-9my8ruzy
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/9my8ruzy

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 6084.23it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1897.60 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2508.77 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2789.37 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2951.33 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3017.99 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2964.82 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2804.20 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1976.65 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2174.53 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2106.70 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Fold 4 metrics: {'eval_loss': 1.78946852684021, 'eval_uas': 0.7381178341498448, 'eval_las': 0.717136481391233, 'eval_upos_accuracy': 0.9789929976658887}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading wandb-summary.json

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▇▇▇▇▇█▇█████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▆▆▄▃▅▃▅▅▄▃▅▅▅▄█▃▂▄▂▅▄▅▆▆▁▄▃▄▁█▇▇▆▃▅▄▆▂▁
wandb: eval/samples_per_second ▆▃▃▅▆▄▆▄▄▅▆▄▃▄▅▁▆▇▅▇▄▅▄▃▃█▅▆▅█▁▂▂▃▆▄▅▃▇█
wandb:   eval/steps_per_second ▆▃▃▅▆▄▆▄▄▅▆▄▃▄▅▁▆▇▅▇▄▅▄▃▃█▅▆▅█▁▂▂▃▆▄▅▃▇█
wandb:                eval/uas ▁▁▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇█▇█████████████████████
wandb:      eval/upos_accuracy ▁▅▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▂▂▂▂▃▃▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇███
wandb:         train/grad_norm ▅▅▅▅▅▅█▆▇▆▅▅▅▅▆▇▆▆▄▇▃▇▃▃▆▃▄▃▃▂▅▄▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.71714
wandb:               eval/loss 1.78947
wandb:            eval/runtime 7.3968
wandb: eval/samples_per_second 182.106
wandb:   eval/steps_per_second 5.813
wandb:                eval/uas 0.73812
wandb:      eval/upos_accuracy 0.97899
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/9my8ruzy
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_220044-9my8ruzy/logs

wandb: setting up run oxrere0y

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_230215-oxrere0y
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/oxrere0y

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9568.70it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1867.05 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2473.94 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2750.62 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2890.39 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2987.60 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2934.33 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2768.38 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1928.75 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2138.68 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2069.41 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

[W 2026-06-15 23:50:01,974] Trial 2 failed with parameters: {'learning_rate': 2.9298928229012235e-05, 'weight_decay': 0.12482567857675334, 'warmup_ratio': 0.35495811617135953, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-15 23:50:01,975] Trial 2 failed with value None.

Fold 5 metrics: {'eval_loss': 1.2421302795410156, 'eval_uas': 0.7994736570514475, 'eval_las': 0.7767944682388153, 'eval_upos_accuracy': 0.9806491563032148}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: uploading history steps 61-63, summary, console lines 48-51; updating run metadata

wandb: uploading wandb-summary.json; uploading config.yaml; uploading output.log

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▇▇▇▇▇▇▇▇█████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▁▅▄▇▅▄▆▆▅▅▆█▃▆▆▆▆▄▄▅▅█▂█▅▆▅▃▆▅▃
wandb: eval/samples_per_second ▃█▄▅▂▄▅▃▃▄▃▃▁▆▃▃▃▃▅▅▄▄▁▇▁▄▃▄▆▃▄▆
wandb:   eval/steps_per_second ▃█▄▅▂▄▅▃▃▄▄▃▁▆▃▃▃▃▅▅▄▅▁▇▁▄▃▄▆▃▄▆
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▇▇▇▇▇▇▇▇█████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇████
wandb:         train/grad_norm ▂▂▂▃▂▂▃▄▃▄▃▃▆▅▃▄▃▇▆▂█▂▂▂▃▁▃▂▁▃▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.77679
wandb:               eval/loss 1.24213
wandb:            eval/runtime 7.4051
wandb: eval/samples_per_second 181.902
wandb:   eval/steps_per_second 5.807
wandb:                eval/uas 0.79947
wandb:      eval/upos_accuracy 0.98065
wandb:              total_flos 5.671486488718541e+16
wandb:             train/epoch 31
wandb:       train/global_step 10447
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial2_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/oxrere0y
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_230215-oxrere0y/logs

wandb: setting up run 37mhmoci

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260615_235003-37mhmoci
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/37mhmoci

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10424.69it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1899.52 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2486.79 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2754.65 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2900.20 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3012.18 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2952.99 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2785.77 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1958.11 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2161.01 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2092.83 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Fold 1 metrics: {'eval_loss': 1.5090349912643433, 'eval_uas': 0.8262874907626838, 'eval_las': 0.8080167163570573, 'eval_upos_accuracy': 0.9826720689040084}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 79-81, summary, console lines 57-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇▇██▇██████████████████
wandb:               eval/loss █▅▄▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▄▆▅▂▃▄█▃▃▅▅▂▅▇▄▂▆▄▄▃▆▃▄▅▄▃▄▅▃▁▂▃▇▄▅▂▂▇▃▁
wandb: eval/samples_per_second ▅▃▄▇▆▅▁▆▆▄▄▇▄▂▅▇▃▅▅▆▃▆▅▄▅▆▅▄▆█▇▆▂▅▄▇▇▂▆█
wandb:   eval/steps_per_second ▅▃▄▇▆▅▁▆▆▄▄▇▄▂▅▇▃▅▅▆▃▅▅▄▅▆▅▄▆█▇▆▂▅▄▇▇▂▆█
wandb:                eval/uas ▁▁▂▃▃▄▅▅▅▆▆▆▆▇▆▇▇▇▇██▇██████████████████
wandb:      eval/upos_accuracy ▁▇▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▇▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:         train/grad_norm █▂▂▂▂▂▂▃▂▂▂▃▂▂▂▂▂▂▂▁▁▁▁▁▂▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.80802
wandb:               eval/loss 1.50903
wandb:            eval/runtime 7.3995
wandb: eval/samples_per_second 182.04
wandb:   eval/steps_per_second 5.811
wandb:                eval/uas 0.82629
wandb:      eval/upos_accuracy 0.98267
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/37mhmoci
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260615_235003-37mhmoci/logs

wandb: setting up run u4uz5xkz

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_005135-u4uz5xkz
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/u4uz5xkz

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9235.06it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1912.59 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2489.63 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2754.64 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2906.39 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2987.43 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2949.72 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2780.30 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1950.94 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2149.22 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2082.40 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Fold 2 metrics: {'eval_loss': 1.314781665802002, 'eval_uas': 0.8383794547125498, 'eval_las': 0.8190544266312673, 'eval_upos_accuracy': 0.9843000102113755}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading config.yaml

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▅▅▆▆▆▆▆▆▇▇▇▇▇█▇██████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▇▅▂▅▅▆▂▄▃▃▅▃▅▄▅▄▅▇▄▅▁▂█▅▇▂▇▅▅█▇▄▇▃▄▁▆▂
wandb: eval/samples_per_second ▆▂▄▇▄▄▃▇▅▆▆▄▆▄▅▄▅▄▂▅▄█▇▁▄▂▇▂▄▄▁▂▅▂▆▅█▃▇
wandb:   eval/steps_per_second ▆▂▄▇▄▄▃▇▅▆▆▄▅▄▅▄▅▄▂▅▄█▇▁▄▂▇▂▄▄▁▂▅▂▆▅█▃▇
wandb:                eval/uas ▁▂▂▃▃▄▅▅▆▆▆▆▆▆▇▇▇▇▇█▇███▇██████████████
wandb:      eval/upos_accuracy ▁▆▇▇███████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇██████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▄▅▅▆▆▆▆▆▆▇▇▇▇▇▇███
wandb:         train/grad_norm ▄▃▃▃▄▄▇▄▅▃▅█▄██▄█▃▃▄▄▃▂▂▂▂▁▂▂▂▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.81905
wandb:               eval/loss 1.31478
wandb:            eval/runtime 7.3908
wandb: eval/samples_per_second 182.255
wandb:   eval/steps_per_second 5.818
wandb:                eval/uas 0.83838
wandb:      eval/upos_accuracy 0.9843
wandb:              total_flos 6.952144728106598e+16
wandb:             train/epoch 38
wandb:       train/global_step 12806
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/u4uz5xkz
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_005135-u4uz5xkz/logs

wandb: setting up run 8ydlnw25

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_015000-8ydlnw25
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/8ydlnw25

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9647.04it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1898.90 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2507.81 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2773.37 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2944.04 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3034.42 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3012.35 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2818.28 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1958.78 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2197.11 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2119.46 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Fold 3 metrics: {'eval_loss': 1.3432097434997559, 'eval_uas': 0.8543516422011347, 'eval_las': 0.8329814028035719, 'eval_upos_accuracy': 0.983310860660951}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading wandb-summary.json

wandb: uploading output.log

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▄▅▆▆▆▆▆▆▇▇▇▇▇▇▇███████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▃▃▆▅▄█▅▄▆▆▄▂▅▅▂▄▄▆▄▃▄▄▆▄▄▄▇▄▄▄▆▄▃▆▃▄▆▆▁
wandb: eval/samples_per_second ▄▆▆▃▄▅▁▄▅▃▃▅▇▄▄▇▅▅▃▅▆▄▅▃▅▅▅▂▅▅▅▃▅▆▃▆▅▃▃█
wandb:   eval/steps_per_second ▄▆▆▃▄▅▁▄▅▃▃▅▇▄▄▇▅▅▃▅▆▄▅▃▅▅▅▂▅▅▅▃▅▆▃▆▅▃▃█
wandb:                eval/uas ▁▂▂▃▃▄▄▅▆▆▆▆▆▆▇▇▇▇▇▇▇███████████████████
wandb:      eval/upos_accuracy ▁▇▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇█
wandb:       train/global_step ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:         train/grad_norm ▃▃▃▃▃▄▅▇▃▃▅▇▃█▅▅▆▅▄▅▆▃▃▂▂▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.83298
wandb:               eval/loss 1.34321
wandb:            eval/runtime 7.3661
wandb: eval/samples_per_second 182.864
wandb:   eval/steps_per_second 5.838
wandb:                eval/uas 0.85435
wandb:      eval/upos_accuracy 0.98331
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/8ydlnw25
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_015000-8ydlnw25/logs

wandb: setting up run akr2n4pf

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_025128-akr2n4pf
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/akr2n4pf

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8803.97it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1880.73 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2493.74 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2746.18 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2922.19 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2961.19 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2947.21 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2777.15 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1972.66 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2210.05 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2132.88 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Fold 4 metrics: {'eval_loss': 1.261884093284607, 'eval_uas': 0.8494882909687844, 'eval_las': 0.8297124682586503, 'eval_upos_accuracy': 0.9842511606432913}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading wandb-summary.json

wandb: uploading output.log

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▅▅▆▆▆▆▇▇▇▆▇▇▇█████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▅▃▄▅█▁▆▁▇▅▅▁▅▆▆▄▅▇▅▃▅▃▄▅▅▄▄▄▇▄▃▄▄▆▃█▆▅▅
wandb: eval/samples_per_second ▆▄▆▅▄▁█▃█▂▄▄█▄▃▃▅▄▂▄▆▄▆▅▄▄▅▅▅▂▅▆▅▅▃▆▁▃▄▄
wandb:   eval/steps_per_second ▆▄▆▅▄▁█▃█▂▄▄█▄▃▃▅▄▂▄▆▄▆▅▄▄▅▅▅▂▅▆▅▅▃▆▁▃▄▄
wandb:                eval/uas ▁▁▂▃▃▄▅▅▆▆▆▆▆▇▇▆▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:         train/grad_norm ▄▃▃▅▄▄▄▄▆▆▅▃█▅▃▇▅▄▄▃▆▃▃▂▂▂▄▅▄▂▁▂▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.82971
wandb:               eval/loss 1.26188
wandb:            eval/runtime 7.423
wandb: eval/samples_per_second 181.462
wandb:   eval/steps_per_second 5.793
wandb:                eval/uas 0.84949
wandb:      eval/upos_accuracy 0.98425
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/akr2n4pf
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_025128-akr2n4pf/logs

wandb: setting up run o03rmi7a

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_035257-o03rmi7a
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/o03rmi7a

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9720.79it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1892.73 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2496.85 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2741.83 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2898.43 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2991.13 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2971.75 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2788.23 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1939.50 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2184.62 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2106.54 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

[W 2026-06-16 04:54:24,278] Trial 3 failed with parameters: {'learning_rate': 4.9263783534529467e-05, 'weight_decay': 0.1496766408078372, 'warmup_ratio': 0.43543301938527523, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-16 04:54:24,279] Trial 3 failed with value None.

Fold 5 metrics: {'eval_loss': 1.251396894454956, 'eval_uas': 0.8562877341452088, 'eval_las': 0.8385365601940244, 'eval_upos_accuracy': 0.9848031374167914}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading config.yaml; uploading output.log

wandb: uploading config.yaml

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇▇▇████████████████████
wandb:               eval/loss █▅▄▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▄▆▃▃▂▆▄▃▅▄▇▃▅▅▅▄▅▄▄▅▃▄▄▅▅▂▆▆▄▅▁▆▄█▅▅▇▅▂
wandb: eval/samples_per_second ▄▅▃▆▆▇▃▅▆▄▅▂▆▄▄▄▅▄▅▅▄▆▅▅▄▄▇▃▃▅▄█▃▅▁▄▄▂▄▇
wandb:   eval/steps_per_second ▄▅▃▆▆▇▄▅▆▄▅▂▆▄▄▄▅▄▅▅▄▆▅▅▄▄▇▃▃▅▄█▃▅▁▄▄▂▄▇
wandb:                eval/uas ▁▂▂▃▃▄▅▅▅▆▆▆▆▇▇▇▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇████
wandb:       train/global_step ▁▁▁▂▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇█████
wandb:         train/grad_norm ▃▃▂▃▃▃▄▃▆▄▂▇█▅▆▆▃▃▅▂▂▂▁▃▁▂▁▂▂▁▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.83854
wandb:               eval/loss 1.2514
wandb:            eval/runtime 7.3802
wandb: eval/samples_per_second 182.515
wandb:   eval/steps_per_second 5.826
wandb:                eval/uas 0.85629
wandb:      eval/upos_accuracy 0.9848
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial3_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/o03rmi7a
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_035257-o03rmi7a/logs

wandb: setting up run 093qyzyj

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_045425-093qyzyj
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/093qyzyj

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9653.17it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1895.05 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2515.12 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2759.80 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2933.36 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3004.60 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2988.47 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2806.32 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1912.11 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2158.86 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2079.30 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Fold 1 metrics: {'eval_loss': 1.4991174936294556, 'eval_uas': 0.8317916571108223, 'eval_las': 0.8112529623117498, 'eval_upos_accuracy': 0.9815508498330913}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading wandb-summary.json

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▅▅▅▆▆▆▇▇▇▆▇▇▇▇████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▃▃▆▄▆▃▄▂▅▇▅▄▄▃▃▅▆▂▅▂▄▄▄▅▅█▁▄▄▂▆▃▂▆▅▇▄▆▃
wandb: eval/samples_per_second ▆▆▆▃▅▃▆▅▇▄▂▄▅▅▆▆▄▃▇▄▇▅▅▅▄▄▁█▅▅▇▃▆▇▃▄▂▅▃▆
wandb:   eval/steps_per_second ▆▆▆▃▅▃▆▅▇▄▂▄▅▅▆▆▄▃▇▄▇▅▅▅▄▄▁█▅▅▇▃▆▇▃▄▂▅▃▆
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▆▇▇▇▆▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▇▇▇▇▇▇███
wandb:       train/global_step ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇██
wandb:         train/grad_norm █▂▂▂▂▂▂▂▂▂▂▂▂▃▂▄▂▃▂▃▂▁▂▁▁▂▁▂▁▂▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.81125
wandb:               eval/loss 1.49912
wandb:            eval/runtime 7.41
wandb: eval/samples_per_second 181.782
wandb:   eval/steps_per_second 5.803
wandb:                eval/uas 0.83179
wandb:      eval/upos_accuracy 0.98155
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/093qyzyj
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_045425-093qyzyj/logs

wandb: setting up run chr03efr

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_055557-chr03efr
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/chr03efr

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8643.53it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1913.18 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2515.71 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2803.12 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2950.74 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3026.53 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2979.56 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2814.93 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 2000.69 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2238.55 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2160.17 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Fold 2 metrics: {'eval_loss': 1.341741919517517, 'eval_uas': 0.8323292147452261, 'eval_las': 0.8130807719799857, 'eval_upos_accuracy': 0.9837128561217195}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading wandb-summary.json; uploading config.yaml; uploading output.log

wandb: uploading wandb-summary.json; uploading output.log

wandb: uploading history steps 80-81, summary, console lines 57-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▆▇▆▇▇▇█▇██████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▇▃▃▄▆▅▅▄▄▃▆▆▇▇▆▄▄▅▆▆▅▄▅▅▄▅▆▆▇▃▆▅▇▄▅█▁▇▄▄
wandb: eval/samples_per_second ▂▆▆▅▃▄▄▅▅▆▃▃▂▂▃▅▅▄▃▃▄▅▄▄▅▄▃▃▂▆▃▄▂▅▄▁█▂▅▅
wandb:   eval/steps_per_second ▂▆▆▅▃▄▄▅▅▆▃▃▂▂▃▅▅▄▃▃▄▅▄▄▅▄▃▃▂▆▃▄▂▅▄▁█▂▅▅
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▆▇▆▇▇▇█▇█▇████████████████
wandb:      eval/upos_accuracy ▁▆▇▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:       train/global_step ▁▁▁▁▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇▇███
wandb:         train/grad_norm ▃▂▂▂▃▃▄▃▃▃▂▄▃▃▃▆█▆▄▃▃▄▂▄▃▂▂▂▃▁▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.81308
wandb:               eval/loss 1.34174
wandb:            eval/runtime 7.4191
wandb: eval/samples_per_second 181.558
wandb:   eval/steps_per_second 5.796
wandb:                eval/uas 0.83233
wandb:      eval/upos_accuracy 0.98371
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/chr03efr
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_055557-chr03efr/logs

wandb: setting up run 3f7udctm

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_065724-3f7udctm
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/3f7udctm

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 7699.45it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1887.45 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2494.44 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2779.40 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2931.56 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3031.15 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2979.80 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2801.75 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1965.66 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2212.60 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2131.70 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Fold 3 metrics: {'eval_loss': 1.3874285221099854, 'eval_uas': 0.8300048337446256, 'eval_las': 0.8101101584959421, 'eval_upos_accuracy': 0.9823695524970107}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 79-81, summary, console lines 57-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇▇▇████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▁▄▃▂▅▃▄▂▆▆▅▂▃▄▇▃▆▅▅▅▅▅▄▄▃▃▃▄▄▅▇▃▇▆▄▆▃█▂▁
wandb: eval/samples_per_second █▅▆▇▄▆▅▇▃▃▄▇▆▅▂▆▃▄▄▄▃▄▅▅▆▆▆▅▅▄▂▆▂▃▅▃▆▁▇█
wandb:   eval/steps_per_second █▅▆▇▄▆▅▇▃▃▄▇▆▅▂▆▃▄▄▄▃▄▅▅▆▆▆▅▅▄▂▆▂▃▅▃▆▁▇▇
wandb:                eval/uas ▁▁▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:       train/global_step ▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇████
wandb:         train/grad_norm ▃▃▃▃▃▄▄▆▃▄▅▃▆▅▆█▃▅▄▃▃▂▃▃▄▅▄▂▁▁▂▂▂▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.81011
wandb:               eval/loss 1.38743
wandb:            eval/runtime 7.384
wandb: eval/samples_per_second 182.423
wandb:   eval/steps_per_second 5.823
wandb:                eval/uas 0.83
wandb:      eval/upos_accuracy 0.98237
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/3f7udctm
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_065724-3f7udctm/logs

wandb: setting up run xno8wt4g

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_075853-xno8wt4g
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/xno8wt4g

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10170.03it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1867.60 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2484.25 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2744.11 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2924.02 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2973.85 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2965.20 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2783.59 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1929.97 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2177.04 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2099.38 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Fold 4 metrics: {'eval_loss': 1.3211052417755127, 'eval_uas': 0.8437684356323902, 'eval_las': 0.8244543052812476, 'eval_upos_accuracy': 0.9830969297458128}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading config.yaml

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▇▇▇▇▇▇▇▇▇▇██████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▄▅▇▄▂▃▇▂▄▇▄▅▇▃▄▇▆▅▄▆▁▅▇▄▄▆█▅▆▃▆▄▇▅▄▃▃▄▁
wandb: eval/samples_per_second ▄▅▄▂▅▇▆▂▇▅▂▅▄▂▆▅▂▃▄▅▃█▄▂▅▅▃▁▄▃▆▃▅▂▃▅▆▆▅█
wandb:   eval/steps_per_second ▄▅▄▂▅▇▆▂▇▅▂▅▄▂▆▅▂▃▄▅▃█▄▂▅▅▃▁▄▃▆▃▅▂▄▅▆▆▅█
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇▇▇▇▇██████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇██
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▇▇▇▇▇▇██
wandb:         train/grad_norm ▅▃▃▅▃▄▅▅▅▄▇█▄▆▆▆▄█▆▄▃▇▃▂▂▂▂▃▃▃▂▂▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.82445
wandb:               eval/loss 1.32111
wandb:            eval/runtime 7.384
wandb: eval/samples_per_second 182.421
wandb:   eval/steps_per_second 5.823
wandb:                eval/uas 0.84377
wandb:      eval/upos_accuracy 0.9831
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/xno8wt4g
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_075853-xno8wt4g/logs

wandb: setting up run et1ptll0

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_090021-et1ptll0
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/et1ptll0

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9671.78it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1888.21 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2488.36 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2765.68 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2915.47 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3022.49 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2981.21 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2796.06 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1940.77 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2149.65 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2081.34 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

[W 2026-06-16 10:01:47,107] Trial 4 failed with parameters: {'learning_rate': 4.124688270504709e-05, 'weight_decay': 0.18557957448046303, 'warmup_ratio': 0.4834143045897379, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-16 10:01:47,108] Trial 4 failed with value None.

Fold 5 metrics: {'eval_loss': 1.3011103868484497, 'eval_uas': 0.8394395995665411, 'eval_las': 0.8211208008669177, 'eval_upos_accuracy': 0.98348728004541}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 80-81, summary, console lines 58-61

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▇▆▇▇▆▇▇▇▇█▇█████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▄▅▅▄▅▄▂▃▅█▅▆▆▆▄▅▅▄▅▄▁▅▆▄▅▅▅█▇▅▅█▃▅▄▅▅▄▅▃
wandb: eval/samples_per_second ▅▄▄▅▄▅▇▆▄▁▄▃▃▃▅▄▄▅▄▅█▄▃▅▄▄▄▁▂▄▄▁▆▄▅▄▄▅▄▆
wandb:   eval/steps_per_second ▅▄▄▅▄▅▇▆▄▁▄▃▃▃▅▄▄▅▄▅█▄▃▄▄▄▄▁▂▄▄▁▆▄▅▄▄▅▄▆
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▅▆▆▇▆▇▇▆▇▇▇▇█▇█████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▂▂▃▃▃▃▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇█████
wandb:       train/global_step ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:         train/grad_norm ▃▃▂▃▃▃▄▃▃▃▇▃▅▅▇▇█▃▅▆▇▂▄▂▂▃▂▂▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.82112
wandb:               eval/loss 1.30111
wandb:            eval/runtime 7.3931
wandb: eval/samples_per_second 182.197
wandb:   eval/steps_per_second 5.816
wandb:                eval/uas 0.83944
wandb:      eval/upos_accuracy 0.98349
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial4_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/et1ptll0
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_090021-et1ptll0/logs

wandb: setting up run ymxqun33

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_100148-ymxqun33
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/ymxqun33

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10467.99it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1918.39 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2513.18 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2751.49 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2906.81 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2977.75 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2972.76 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2794.17 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1929.94 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2173.75 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2094.17 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Fold 1 metrics: {'eval_loss': 1.6967101097106934, 'eval_uas': 0.6553525469510486, 'eval_las': 0.6325204495069184, 'eval_upos_accuracy': 0.9714853604464491}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▄▄▄▅▅▅▆▆▇▇▇▇▇██████████████████
wandb:               eval/loss █▆▄▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▇▄▆▃▄▄▃▃▅▃▃▃▃▄▄█▆▃▄▂▄▂▇▄▆▃▅▁▃▅▆▇▄▅▆▁
wandb: eval/samples_per_second ▄▂▅▃▆▅▅▆▆▄▆▆▆▆▅▅▁▃▆▅▇▅▇▂▅▃▆▄█▆▄▃▂▅▄▃█
wandb:   eval/steps_per_second ▄▂▅▃▆▅▅▆▆▄▆▆▆▆▅▅▁▃▆▅▇▅▇▂▅▃▆▄█▆▄▃▂▅▄▃█
wandb:                eval/uas ▁▂▂▃▃▃▄▄▄▅▅▆▆▆▇▇▇▇▇██████████████████
wandb:      eval/upos_accuracy ▁▅▆▇█████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:         train/grad_norm ▅▃▂▂▃▂▂▃▂▂▃▃▅▄▅▅▃▅▃▂█▃▃▃▄▃▄▃▂▃▃▄▁▂▂▃
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.63252
wandb:               eval/loss 1.69671
wandb:            eval/runtime 7.3838
wandb: eval/samples_per_second 182.426
wandb:   eval/steps_per_second 5.824
wandb:                eval/uas 0.65535
wandb:      eval/upos_accuracy 0.97149
wandb:              total_flos 6.586242373995725e+16
wandb:             train/epoch 36
wandb:       train/global_step 12132
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/ymxqun33
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_100148-ymxqun33/logs

wandb: setting up run dgrk56b5

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_105710-dgrk56b5
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/dgrk56b5

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9323.15it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1860.75 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2447.04 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2725.80 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2872.60 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2955.56 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2923.39 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2750.92 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1946.73 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2148.62 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2082.38 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Fold 2 metrics: {'eval_loss': 1.780327320098877, 'eval_uas': 0.6404829980598387, 'eval_las': 0.6175584601245788, 'eval_upos_accuracy': 0.9735014806494435}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading history steps 79-81, summary, console lines 57-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▆▆▇▇▇▇▇▇████████████████████
wandb:               eval/loss █▆▅▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▄▁▅█▄▅▃▄▆▄▆█▆▅▄▄▆▅▅▅▅▇█▅▅▇▆▅▆▂▁▆▃▄▅▄▄▃▄
wandb: eval/samples_per_second ▃▅█▄▁▅▃▆▅▃▅▃▁▃▄▅▅▃▄▄▄▄▂▁▄▄▂▃▄▃▇█▃▆▅▄▅▅▆▅
wandb:   eval/steps_per_second ▃▅█▄▁▅▃▆▅▃▅▃▁▃▄▅▅▃▄▄▄▄▂▁▄▅▂▃▄▃▇█▃▆▅▄▅▅▆▅
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▇▇▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▄▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇████
wandb:       train/global_step ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇███
wandb:         train/grad_norm ▄▂▂▂▂▂▂▂▃▃▃▂▂▄▃▄▆█▃▂▄▃▃▄▇▃▄▃▂▂▂▄▃▄▁▆▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.61756
wandb:               eval/loss 1.78033
wandb:            eval/runtime 7.4061
wandb: eval/samples_per_second 181.878
wandb:   eval/steps_per_second 5.806
wandb:                eval/uas 0.64048
wandb:      eval/upos_accuracy 0.9735
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/dgrk56b5
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_105710-dgrk56b5/logs

wandb: setting up run 6e5dk2nl

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_115840-6e5dk2nl
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/6e5dk2nl

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 11878.62it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1904.42 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2524.74 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2795.65 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2966.62 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3032.01 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3022.80 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2833.92 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1924.48 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2186.87 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2093.79 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Fold 3 metrics: {'eval_loss': 1.6620501279830933, 'eval_uas': 0.6659882463683313, 'eval_las': 0.6438802248963289, 'eval_upos_accuracy': 0.9746101203348004}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▄▄▄▅▅▆▆▆▆▇▇▇▇▇███████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▂▃▄▆▅▃▃▆▆▆▄▆▂▄▃▃▅▅▆▆▂▆▇▅▂▆█▃▂▅▄▄▆▆▃▅▅▃▁
wandb: eval/samples_per_second ▇▆▅▃▄▆▆▃▃▃▅▃▇▅▆▆▄▄▃▃▇▃▂▄▇▃▁▆▇▄▅▅▃▃▆▄▄▆█
wandb:   eval/steps_per_second ▇▆▅▃▄▆▇▃▃▃▅▃▇▅▆▅▄▄▃▃▇▃▂▄▇▃▁▅▇▃▅▅▃▃▆▄▄▆█
wandb:                eval/uas ▁▂▂▂▃▃▄▄▄▅▅▆▆▆▆▇▇▇▇▇███████████████████
wandb:      eval/upos_accuracy ▁▅▆▇███████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇████
wandb:       train/global_step ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇███
wandb:         train/grad_norm ▄▃▂▂▃▂▂▃▂▂▂▄▂▅▂▃▄█▃▃▃▆▅▂▅▅▃▂▄▂▄▂▁▁▄▂▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.64388
wandb:               eval/loss 1.66205
wandb:            eval/runtime 7.3919
wandb: eval/samples_per_second 182.226
wandb:   eval/steps_per_second 5.817
wandb:                eval/uas 0.66599
wandb:      eval/upos_accuracy 0.97461
wandb:              total_flos 6.952144728106598e+16
wandb:             train/epoch 38
wandb:       train/global_step 12806
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/6e5dk2nl
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_115840-6e5dk2nl/logs

wandb: setting up run 24zxum7a

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_125710-24zxum7a
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/24zxum7a

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8492.80it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1846.04 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2446.05 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2708.75 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2885.72 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2939.63 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2923.67 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2745.05 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1961.32 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2196.36 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2122.50 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Fold 4 metrics: {'eval_loss': 1.6332993507385254, 'eval_uas': 0.6644009541642086, 'eval_las': 0.6399569087131608, 'eval_upos_accuracy': 0.9728370995460025}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading history steps 79-79, summary, console lines 57-58

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▆▆▇▇▇▇▇▇▇███████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▃▃▄▃▄▃▄▄▄▆▅▅▆▄▇▃▄▂▄▅▄▇▄▅▄▃▄▃▇▃▆▂▅█▄▃▁▃▂
wandb: eval/samples_per_second ▆▆▆▅▆▅▆▅▅▅▃▄▄▃▅▂▆▅▇▅▄▅▂▅▄▅▆▅▅▂▆▃▇▄▁▅▆█▆▇
wandb:   eval/steps_per_second ▅▆▆▅▆▅▆▅▅▅▃▄▄▃▅▂▆▅▇▅▄▅▂▅▄▅▆▅▅▂▆▃▇▄▁▄▆█▆▇
wandb:                eval/uas ▁▂▂▃▃▃▄▄▄▅▅▅▆▆▇▇▇▇▇▇▇███████████████████
wandb:      eval/upos_accuracy ▁▄▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▇▇▇███
wandb:       train/global_step ▁▁▂▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:         train/grad_norm ▃▂▂▂▂▂▂▂▂▂▂▂▂▃▃▃▃▃▂▃█▂▅▂▃▃▂▂▂▂▂▂▂▁▂▁▂▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.63996
wandb:               eval/loss 1.6333
wandb:            eval/runtime 7.4092
wandb: eval/samples_per_second 181.802
wandb:   eval/steps_per_second 5.804
wandb:                eval/uas 0.6644
wandb:      eval/upos_accuracy 0.97284
wandb:              total_flos 7.135095905162035e+16
wandb:             train/epoch 39
wandb:       train/global_step 13143
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/24zxum7a
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_125710-24zxum7a/logs

wandb: setting up run kq57pmox

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_135715-kq57pmox
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/kq57pmox

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10123.14it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1910.72 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2526.87 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2774.92 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2946.07 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3024.05 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3008.85 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2823.10 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1956.58 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2202.15 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2123.69 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.08it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

[W 2026-06-16 14:58:46,219] Trial 5 failed with parameters: {'learning_rate': 1.006470981383726e-05, 'weight_decay': 0.20528269695941193, 'warmup_ratio': 0.35200608677168876, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-16 14:58:46,221] Trial 5 failed with value None.

Fold 5 metrics: {'eval_loss': 1.6341437101364136, 'eval_uas': 0.6601217813096651, 'eval_las': 0.6390164611177047, 'eval_upos_accuracy': 0.9749987099437536}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 79-81, summary, console lines 57-61

wandb: uploading data

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▄▄▄▅▅▅▆▆▇▇▇▇▇▇████████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▄▇▅▁▅▄▅█▄▇▄▃▆▄▆▄▃▃▄▅▃▃▅▁▆▆▄▄▄▅▃▅▅▅▆▅▇▃▃
wandb: eval/samples_per_second ▃▅▂▄█▄▅▄▁▅▂▅▆▃▅▃▅▆▆▅▄▆▆▄█▃▃▅▅▅▄▆▄▄▄▃▄▂▅▆
wandb:   eval/steps_per_second ▃▅▂▄█▄▅▄▁▅▂▅▆▃▅▃▅▆▆▅▃▆▆▄█▃▃▅▅▅▃▆▄▄▄▃▄▂▅▆
wandb:                eval/uas ▁▂▂▃▃▃▄▄▄▅▅▅▆▆▇▇▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▅▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▇▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇██
wandb:         train/grad_norm ▄▂▂▂▃▂▂▂▂▂▄▄▂▆▆▅▅▄█▄▃▃▂▇▄▂▄▇▂▄▁▃▄▆▃▂▂▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.63902
wandb:               eval/loss 1.63414
wandb:            eval/runtime 7.4072
wandb: eval/samples_per_second 181.85
wandb:   eval/steps_per_second 5.805
wandb:                eval/uas 0.66012
wandb:      eval/upos_accuracy 0.975
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial5_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/kq57pmox
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_135715-kq57pmox/logs

wandb: setting up run jics9sfp

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_145847-jics9sfp
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/jics9sfp

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 11364.61it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1915.74 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2522.08 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2760.08 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2924.76 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2989.25 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2973.29 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2800.46 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1908.89 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2152.97 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2073.27 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Fold 1 metrics: {'eval_loss': 1.57682204246521, 'eval_uas': 0.7241801085543919, 'eval_las': 0.7018831383941085, 'eval_upos_accuracy': 0.9751038401753179}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 74-75, summary, console lines 55-56

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇▇▇███████████████
wandb:               eval/loss █▆▄▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▁▁▃▅▄▂▂▄▄▂▅▄▇▄▄▆▁▁▂▂▄▅▆▄▄█▃▄▁▅▇▄▂▅▃▃▂
wandb: eval/samples_per_second ▆██▆▄▅▇▇▅▅▇▄▅▂▅▅▃██▇▇▅▄▃▅▅▁▆▅█▄▂▅▇▄▆▆▇
wandb:   eval/steps_per_second ▆██▆▄▅▇▇▆▅▇▄▅▂▅▆▃███▇▅▄▃▅▅▁▆▅█▄▂▅▇▄▆▆▇
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇▇▇███████████████
wandb:      eval/upos_accuracy ▁▅▆▇██████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇███
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▅▅▆▆▇▇▇▇▇▇█
wandb:         train/grad_norm ▅▂▂▂▂▂▂▂▂▂▂▂▃▃▃▅▂▃█▂▄▃█▇▂▅▁▃▂▂▃▂▂▂▁▂▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.70188
wandb:               eval/loss 1.57682
wandb:            eval/runtime 7.4116
wandb: eval/samples_per_second 181.741
wandb:   eval/steps_per_second 5.802
wandb:                eval/uas 0.72418
wandb:      eval/upos_accuracy 0.9751
wandb:              total_flos 6.769193551051162e+16
wandb:             train/epoch 37
wandb:       train/global_step 12469
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/jics9sfp
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_145847-jics9sfp/logs

wandb: setting up run jca5vu0p

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_155544-jca5vu0p
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/jca5vu0p

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10369.11it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1867.56 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2492.55 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2737.95 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2917.73 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2958.51 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2948.74 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2773.59 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1926.97 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2163.70 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2088.47 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Fold 2 metrics: {'eval_loss': 1.7673689126968384, 'eval_uas': 0.6700704584907587, 'eval_las': 0.6461758398856325, 'eval_upos_accuracy': 0.9755948126212601}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 81-81, summary, console lines 58-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▅▆▆▇▇▇▇▇▇███████████████████
wandb:               eval/loss █▆▅▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▁█▄▅▆▇▃▅▇▅▂▆▅▅▃█▅▃▂▃▄▅▆▅▂▅▄█▆▆▂▆▃▅▇▄█▆▂
wandb: eval/samples_per_second ▂█▁▅▄▃▂▆▄▂▄▇▃▄▄▆▁▄▆▇▆▅▄▃▄▇▄▅▁▃▃▇▃▆▄▂▅▁▃▇
wandb:   eval/steps_per_second ▂█▁▅▄▃▂▆▄▂▄▇▃▄▄▆▁▄▆▇▆▅▄▃▄▇▄▅▁▃▃▇▃▆▄▂▅▁▂▇
wandb:                eval/uas ▁▁▂▂▂▃▃▄▄▄▅▅▅▆▆▇▇▇▇▇▇███████████████████
wandb:      eval/upos_accuracy ▁▄▆▇▇███████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▇▇▇▇▇▇▇██
wandb:         train/grad_norm ▄▃▄▃▃▄▃▃▃▄▆▃▅▄▅▅▆▅▇█▆▅▄▃▄▄▄▅▃▃▅█▆▁▂▂▂▂▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.64618
wandb:               eval/loss 1.76737
wandb:            eval/runtime 7.4116
wandb: eval/samples_per_second 181.742
wandb:   eval/steps_per_second 5.802
wandb:                eval/uas 0.67007
wandb:      eval/upos_accuracy 0.97559
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/jca5vu0p
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_155544-jca5vu0p/logs

wandb: setting up run ucseyr5u

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_165717-ucseyr5u
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/ucseyr5u

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 7670.45it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1920.26 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2520.00 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2810.41 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2961.68 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3068.19 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3003.93 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2832.17 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1974.03 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2180.08 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2112.69 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.04s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Fold 3 metrics: {'eval_loss': 1.6044450998306274, 'eval_uas': 0.7145801002365991, 'eval_las': 0.6926501640929097, 'eval_upos_accuracy': 0.9771033149311827}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 75-77, summary, console lines 55-57

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇▇█████████████████
wandb:               eval/loss █▆▄▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▄▅▂▄▂▄▄▄▆▅▇▄▃▆▆▆▆▆▇█▆▅▅▆▁▂▇▆▅▄▆▆▇▇▅▅▄▃▄
wandb: eval/samples_per_second ▅▄▇▅▇▅▅▅▃▄▂▅▆▃▃▃▃▃▂▁▃▄▄▃█▇▂▃▄▅▃▃▂▂▄▄▅▆▅
wandb:   eval/steps_per_second ▅▄▇▅▇▅▅▅▄▄▂▅▆▃▃▃▃▃▂▁▃▄▄▃█▇▂▃▄▅▃▃▂▂▄▄▅▆▅
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇▇█████████████████
wandb:      eval/upos_accuracy ▁▅▆▇███████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇▇█████
wandb:         train/grad_norm ▄▂▂▂▃▃▂▃▂▂▂▆▃▄▃▃▄▃▃▆▃█▂▄▄▂▂▄▃▆▂▂▃▂▂▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.69265
wandb:               eval/loss 1.60445
wandb:            eval/runtime 7.4089
wandb: eval/samples_per_second 181.808
wandb:   eval/steps_per_second 5.804
wandb:                eval/uas 0.71458
wandb:      eval/upos_accuracy 0.9771
wandb:              total_flos 6.952144728106598e+16
wandb:             train/epoch 38
wandb:       train/global_step 12806
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/ucseyr5u
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_165717-ucseyr5u/logs

wandb: setting up run vkr5vxbz

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_175546-vkr5vxbz
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/vkr5vxbz

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 11170.14it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1883.66 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2486.81 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2757.88 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2903.67 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2972.26 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2917.48 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2765.77 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1952.06 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2158.04 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2089.24 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Fold 4 metrics: {'eval_loss': 1.5673577785491943, 'eval_uas': 0.7280119014030317, 'eval_las': 0.702541872932003, 'eval_upos_accuracy': 0.9757611511529484}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading history steps 81-81, summary, console lines 58-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▆▅▆▆▇▇▇▇▇▇█▇████████████████
wandb:               eval/loss █▅▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▄▃▆▃▅▃▂▄█▃▅█▅▅▇▅▄▁▃▆▆▅▅▂▆▅▄▄▅▆▄▆▆▆▆█▁▁▃
wandb: eval/samples_per_second ▄▅▆▃▆▄▆▇▅▁▆▄▁▄▄▂▄▅█▆▃▃▄▄▇▃▄▅▅▄▃▅▃▃▃▃▁██▆
wandb:   eval/steps_per_second ▄▅▆▃▆▄▆▇▅▁▆▅▁▄▄▃▄▅█▆▃▃▄▄▇▃▄▅▅▄▃▅▃▃▃▃▁██▆
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▆▅▆▆▇▇▇▇▇▇█▇████████████████
wandb:      eval/upos_accuracy ▁▄▆▇████████████████████████████████████
wandb:             train/epoch ▁▂▂▂▂▂▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇███
wandb:         train/grad_norm ▃▂▃▂▂▂▂▃▃▂▂▂▃▄▄▃▃▇▃█▇▂▄▅▃▂▄▄▂▆▃▂▂▂▂▂▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.70254
wandb:               eval/loss 1.56736
wandb:            eval/runtime 7.4207
wandb: eval/samples_per_second 181.52
wandb:   eval/steps_per_second 5.795
wandb:                eval/uas 0.72801
wandb:      eval/upos_accuracy 0.97576
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/vkr5vxbz
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_175546-vkr5vxbz/logs

wandb: setting up run o684c4kn

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_185721-o684c4kn
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/o684c4kn

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8428.74it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1904.89 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2499.17 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2775.66 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2914.03 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3018.40 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2964.30 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2797.68 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1970.07 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2174.88 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2105.33 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

[W 2026-06-16 19:58:56,073] Trial 6 failed with parameters: {'learning_rate': 1.506971134306202e-05, 'weight_decay': 0.2627497594404126, 'warmup_ratio': 0.48497288713311265, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-16 19:58:56,075] Trial 6 failed with value None.

Fold 5 metrics: {'eval_loss': 1.5731602907180786, 'eval_uas': 0.7281593477475617, 'eval_las': 0.7070282264306724, 'eval_upos_accuracy': 0.9778884359358068}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading wandb-summary.json; uploading config.yaml; uploading output.log

wandb: uploading history steps 81-81, summary, console lines 58-61

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇▇█▇████████████████
wandb:               eval/loss █▆▄▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▇▅▃▄▆▃▂▄▅▄▄▄▆▄▅▇▃▅▆▁▄█▅▅▄▅▃▅▃▄▆▄▇▃▄▇▄▇▅▄
wandb: eval/samples_per_second ▂▄▆▅▃▆▇▅▄▅▅▅▃▅▄▂▆▄▃█▅▁▄▄▅▄▆▄▆▅▃▅▂▅▅▂▅▂▄▅
wandb:   eval/steps_per_second ▂▄▆▅▃▆▇▅▄▅▅▅▃▅▄▂▆▄▃█▅▁▄▄▅▅▆▄▆▅▃▅▂▅▅▂▅▂▄▅
wandb:                eval/uas ▁▂▂▂▃▃▄▄▄▅▅▅▆▆▆▇▇▇▇▇▇▇█▇████████████████
wandb:      eval/upos_accuracy ▁▅▇▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇▇██
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇█████
wandb:         train/grad_norm ▄▄▃▃▃▃▃▃▃▄▄▅▄▄▅▄▅▆█▄▅▄▅█▄▃▄▆▂▆▂▂▅▃▂▂▂▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.70703
wandb:               eval/loss 1.57316
wandb:            eval/runtime 7.4199
wandb: eval/samples_per_second 181.54
wandb:   eval/steps_per_second 5.795
wandb:                eval/uas 0.72816
wandb:      eval/upos_accuracy 0.97789
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial6_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/o684c4kn
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_185721-o684c4kn/logs

wandb: setting up run wkpndxxh

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_195857-wkpndxxh
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/wkpndxxh

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10673.75it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1919.71 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2518.19 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2759.47 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2917.83 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3004.54 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2977.81 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2802.59 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1911.40 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2151.15 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2071.84 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Fold 1 metrics: {'eval_loss': 1.5340880155563354, 'eval_uas': 0.800219147363861, 'eval_las': 0.7797059348164004, 'eval_upos_accuracy': 0.9803277017557271}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 79-81, summary, console lines 57-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▇▇▇▇▇▇▇██▇██████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▄▄▁▃▅▁▃▃▄▂▅▅▅▅▇▆▃▅▅▅▂▃▁▆▂█▃▄▆▅▆▅▅▂▅▇▃▆▇▂
wandb: eval/samples_per_second ▅▅█▆▄█▆▆▅▇▄▄▄▄▂▃▆▄▄▄▇▆█▃▇▁▆▅▂▄▃▃▄▇▄▂▆▃▂▇
wandb:   eval/steps_per_second ▅▅█▆▄█▆▆▅▇▄▄▄▄▂▃▆▄▄▄▇▆█▃▇▁▆▅▂▄▃▄▄▇▄▂▆▃▂▇
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▆▇▇▇▇▇▇▇██▇██████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇██
wandb:       train/global_step ▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇█████
wandb:         train/grad_norm █▁▁▁▂▁▁▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.77971
wandb:               eval/loss 1.53409
wandb:            eval/runtime 7.4063
wandb: eval/samples_per_second 181.871
wandb:   eval/steps_per_second 5.806
wandb:                eval/uas 0.80022
wandb:      eval/upos_accuracy 0.98033
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/wkpndxxh
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_195857-wkpndxxh/logs

wandb: setting up run 2ddfcdxx

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_210028-2ddfcdxx
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/2ddfcdxx

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 6929.91it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1854.12 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2442.16 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2722.74 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2883.97 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2956.57 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2907.75 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2744.43 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1941.41 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2176.60 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2100.35 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Fold 2 metrics: {'eval_loss': 1.473970651626587, 'eval_uas': 0.7899520065352803, 'eval_las': 0.7700398243643419, 'eval_upos_accuracy': 0.9817216379046257}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading wandb-summary.json

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇▇█▇▇████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▄▅▅▇▁▄▇▆▅▆▅▆▅▃▅▇█▆▅▅▅▅▆▇▆▂█▃█▇▇▅▆▆▆▆▇▅
wandb: eval/samples_per_second ▅▄▄▂█▅▂▂▄▃▄▃▄▆▄▂▁▃▄▄▄▄▃▂▃▇▁▅▁▂▂▄▃▃▃▃▂▄
wandb:   eval/steps_per_second ▅▄▄▂█▅▂▃▄▃▄▃▄▆▄▂▁▃▄▄▄▄▃▂▃▇▁▆▁▂▂▄▃▃▃▃▂▄
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇▇█▇▇████████████████
wandb:      eval/upos_accuracy ▁▆▇▇██████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇▇███
wandb:       train/global_step ▁▁▁▂▂▂▂▃▃▃▃▃▃▃▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇█████
wandb:         train/grad_norm ▄▃▃▃▃▃▅▃▄▃▃▆▅▄▅▅█▃▃▆▃▂▃▃▃▃▃▂▂▁▂▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.77004
wandb:               eval/loss 1.47397
wandb:            eval/runtime 7.4271
wandb: eval/samples_per_second 181.363
wandb:   eval/steps_per_second 5.79
wandb:                eval/uas 0.78995
wandb:      eval/upos_accuracy 0.98172
wandb:              total_flos 6.769193551051162e+16
wandb:             train/epoch 37
wandb:       train/global_step 12469
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/2ddfcdxx
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_210028-2ddfcdxx/logs

wandb: setting up run oq213m9z

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_215725-oq213m9z
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/oq213m9z

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8973.35it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1859.19 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2475.36 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2730.38 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2905.78 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2991.68 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2968.65 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2780.38 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1911.08 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2149.43 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2074.50 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Fold 3 metrics: {'eval_loss': 1.7736746072769165, 'eval_uas': 0.7481364642430102, 'eval_las': 0.7276312107258249, 'eval_upos_accuracy': 0.978349912229374}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 77-79, summary, console lines 56-58

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇██████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▂▃▆▃▅▅▄▆▅▅▆▆▅▄▇▇█▃█▆▅▇▄▆▄▄▆▅█▇▆▅▅▄▆▆▇▇▄▁
wandb: eval/samples_per_second ▇▆▃▆▄▄▅▃▄▄▃▃▄▅▂▂▁▆▁▃▄▂▅▃▅▅▃▄▁▂▃▄▄▅▃▃▂▂▅█
wandb:   eval/steps_per_second ▇▆▃▆▄▄▅▃▄▄▃▃▄▅▂▂▁▅▁▃▄▂▅▃▅▅▃▄▁▂▃▄▄▅▃▃▂▂▅█
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇██████████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇▇██
wandb:       train/global_step ▁▁▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:         train/grad_norm ▅▃▃▃▄▄▄▇▃▃▄▆▄▇▅▃▅▆▃▃▃▄█▄▃▅▂▂▂▁▂▂▁▁▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.72763
wandb:               eval/loss 1.77367
wandb:            eval/runtime 7.3821
wandb: eval/samples_per_second 182.469
wandb:   eval/steps_per_second 5.825
wandb:                eval/uas 0.74814
wandb:      eval/upos_accuracy 0.97835
wandb:              total_flos 7.135095905162035e+16
wandb:             train/epoch 39
wandb:       train/global_step 13143
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/oq213m9z
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_215725-oq213m9z/logs

wandb: setting up run xuztebvs

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_225727-xuztebvs
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/xuztebvs

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8832.47it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1923.68 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2519.77 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2800.83 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2949.58 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3021.83 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2985.88 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2818.72 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1998.67 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2207.02 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2137.88 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Fold 4 metrics: {'eval_loss': 1.4197397232055664, 'eval_uas': 0.7921871393028446, 'eval_las': 0.7707697437607408, 'eval_upos_accuracy': 0.980916715828353}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 77-79, summary, console lines 56-58

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇▇▇████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▅▃▃▅▅▂▄▄▄▂▄▄▄▅▄▂▄▄▅▁▅▅▃▃▄▅▆▃▆▅▅▅▆█▁▁▄▄▁
wandb: eval/samples_per_second ▆▄▆▆▄▄▇▅▅▅▇▅▅▅▄▅▇▅▅▄█▄▄▆▆▅▄▃▆▃▄▄▄▃▁██▅▅█
wandb:   eval/steps_per_second ▆▄▆▆▄▄▇▅▅▅▇▅▅▅▄▅▇▅▅▄▇▅▄▆▆▅▅▃▆▃▄▄▄▃▁▇█▅▅█
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▆▆▆▆▇▇▇▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇███
wandb:       train/global_step ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▅▅▆▆▆▇▇▇▇▇███
wandb:         train/grad_norm ▃▃▃▃▃▃▃▄▃▃▃▄█▄▃▅▆▄▃▃▃▃▄▄▂▃▂▂▄▁▁▂▁▂▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.77077
wandb:               eval/loss 1.41974
wandb:            eval/runtime 7.4039
wandb: eval/samples_per_second 181.93
wandb:   eval/steps_per_second 5.808
wandb:                eval/uas 0.79219
wandb:      eval/upos_accuracy 0.98092
wandb:              total_flos 7.135095905162035e+16
wandb:             train/epoch 39
wandb:       train/global_step 13143
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/xuztebvs
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_225727-xuztebvs/logs

wandb: setting up run vbvf2u7i

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260616_235727-vbvf2u7i
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/vbvf2u7i

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10486.54it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1857.33 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2475.57 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2718.87 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2893.46 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2971.05 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2958.88 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2770.97 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1913.17 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2154.45 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2078.76 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

[W 2026-06-17 00:58:59,655] Trial 7 failed with parameters: {'learning_rate': 2.92792088888223e-05, 'weight_decay': 0.24058260978065765, 'warmup_ratio': 0.38855679476646726, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-17 00:58:59,656] Trial 7 failed with value None.

Fold 5 metrics: {'eval_loss': 1.4110653400421143, 'eval_uas': 0.7964033231848908, 'eval_las': 0.7756592187419371, 'eval_upos_accuracy': 0.981810206925022}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading summary, console lines 61-61

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▄▄▅▅▅▆▆▆▇▇▆▇▇█▇█▇██████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▅▄▄▅▄▃▄▆▆▄▅▇▃▆▆▆▅▅▅▄▇▇█▇▃▄▆▂▆▃▄▇▄▄▄▃▆▄▁
wandb: eval/samples_per_second ▃▄▅▅▃▅▆▅▃▃▅▄▂▆▃▃▃▄▄▄▅▂▂▁▂▆▅▃▇▃▆▅▂▅▄▅▆▃▅█
wandb:   eval/steps_per_second ▃▄▅▅▄▅▆▅▃▃▅▄▂▆▃▃▃▄▄▄▅▂▂▁▂▆▅▃▇▃▆▅▂▅▅▅▆▃▅█
wandb:                eval/uas ▁▂▂▃▃▄▄▅▅▅▅▆▆▇▇▆▇▇█▇█▇██████████████████
wandb:      eval/upos_accuracy ▁▆▇█████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇███
wandb:       train/global_step ▁▁▂▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▆▆▆▆▇▇▇▇▇▇████
wandb:         train/grad_norm ▂▃▂▂▂▂▃▃▃▃▅▄▄▃▃▇▃▃▂▃▂█▄▄▆▂▃▂▁▂▂▁▁▂▂▁▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.77566
wandb:               eval/loss 1.41107
wandb:            eval/runtime 7.3939
wandb: eval/samples_per_second 182.176
wandb:   eval/steps_per_second 5.816
wandb:                eval/uas 0.7964
wandb:      eval/upos_accuracy 0.98181
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial7_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/vbvf2u7i
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260616_235727-vbvf2u7i/logs

wandb: setting up run 48y6gso6

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_005901-48y6gso6
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/48y6gso6

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10264.39it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1935.64 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2552.55 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2793.42 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2963.43 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3035.14 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3011.73 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2837.71 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1962.74 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2214.79 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2136.13 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Fold 1 metrics: {'eval_loss': 1.7515891790390015, 'eval_uas': 0.6931427260912775, 'eval_las': 0.6708202736793824, 'eval_upos_accuracy': 0.9740845501108478}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 81-81, summary, console lines 58-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇▇██████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▇▅▆▅▃▄▅▅▃▆▅█▁▄▆▅▃█▆▇▇▃▅▄▂▅▆▅▄▂▄▅▄█▄▇▇▂▂
wandb: eval/samples_per_second ▃▂▄▃▄▆▅▄▄▆▃▄▁█▅▃▄▆▁▃▂▂▆▄▅▇▄▃▄▅▇▅▄▅▁▅▂▂▇▇
wandb:   eval/steps_per_second ▃▂▄▃▄▆▅▄▄▆▃▄▁█▅▃▄▆▁▃▂▂▆▄▅▇▄▃▄▅▇▅▄▅▁▅▂▂▇▇
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇▇██████████████████
wandb:      eval/upos_accuracy ▁▅▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇███
wandb:         train/grad_norm ▆▃▃▃▃▃▃▃▃▃▄▄▄▅█▅▃▅▃▃▄▃▂▃▄▆█▄▃█▃▂▂▂▃▂▂▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.67082
wandb:               eval/loss 1.75159
wandb:            eval/runtime 7.3999
wandb: eval/samples_per_second 182.03
wandb:   eval/steps_per_second 5.811
wandb:                eval/uas 0.69314
wandb:      eval/upos_accuracy 0.97408
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/48y6gso6
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_005901-48y6gso6/logs

wandb: setting up run 2xjfoxra

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_020035-2xjfoxra
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/2xjfoxra

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9706.35it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1919.30 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2514.28 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2790.96 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2929.06 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3008.62 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2977.64 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2804.09 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1989.12 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2182.81 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2115.87 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Fold 2 metrics: {'eval_loss': 1.7169063091278076, 'eval_uas': 0.6893189012559992, 'eval_las': 0.6658837945471255, 'eval_upos_accuracy': 0.9747523741447973}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▅▆▆▆▇▇▇▇▇▇██████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▆▄▄▅▃▃▅▇▆▆▅▃▄▄▆▆▆▆▅▅▆▅▆▄▄▆▇█▄▆▆▇▁▇▆▅▅▆▃
wandb: eval/samples_per_second ▆▃▅▅▄▆▆▄▂▃▃▄▆▅▅▃▃▃▃▄▄▃▄▃▅▅▃▂▁▅▃▃▂█▂▃▄▄▃▆
wandb:   eval/steps_per_second ▆▂▅▅▄▆▆▄▂▃▃▄▆▅▅▃▃▃▃▄▄▃▄▃▅▅▃▂▁▅▃▃▂█▂▃▄▄▃▆
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▅▆▆▆▇▇▇▇▇▇██████████████████
wandb:      eval/upos_accuracy ▁▅▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇███
wandb:       train/global_step ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▆▆▆▇▇▇▇▇▇█████
wandb:         train/grad_norm ▄▃▂▃▂▂▂▂▃▂▂▃▃▃▃▂▇▃▃▄▆▄▄▄▅▃█▂▃▅▄▂▂▁▄▂▁▂▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.66588
wandb:               eval/loss 1.71691
wandb:            eval/runtime 7.4142
wandb: eval/samples_per_second 181.678
wandb:   eval/steps_per_second 5.8
wandb:                eval/uas 0.68932
wandb:      eval/upos_accuracy 0.97475
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/2xjfoxra
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_020035-2xjfoxra/logs

wandb: setting up run w2i2pz3y

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_030207-w2i2pz3y
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/w2i2pz3y

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 9742.87it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1880.89 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2467.18 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2742.43 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2886.62 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2994.48 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2939.77 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2770.36 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1947.77 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2155.67 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2084.72 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Fold 3 metrics: {'eval_loss': 1.7198596000671387, 'eval_uas': 0.6959829038084819, 'eval_las': 0.6732134225456026, 'eval_upos_accuracy': 0.9750680540361768}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading wandb-summary.json

wandb: uploading output.log

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇▇██████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▃▃▅▄▂▆▃█▆▅▃▄▆▆▅█▄█▄▅▃▄▆▃▄▄▂▇▄▂▃▅▄▄▄▃▆█▇▁
wandb: eval/samples_per_second ▆▆▄▅▇▃▆▁▃▄▅▅▃▃▄▁▅▁▅▄▆▅▃▆▄▅▇▂▅▇▆▄▅▅▅▆▃▁▂█
wandb:   eval/steps_per_second ▆▆▄▅▇▃▆▁▃▄▅▅▃▃▄▁▅▁▅▄▆▅▃▆▄▅▇▂▅▇▆▄▅▅▅▆▃▁▂█
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇▇██████████████████
wandb:      eval/upos_accuracy ▁▅▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▂▂▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇███
wandb:         train/grad_norm ▄▃▂▂▃▃▂▃▂▂▃▆▃▆▃▆▆▃▅▃▄▆▃▄▄▃█▇▅▄▃▃▅▂▁▁▁▁▂▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.67321
wandb:               eval/loss 1.71986
wandb:            eval/runtime 7.3852
wandb: eval/samples_per_second 182.392
wandb:   eval/steps_per_second 5.822
wandb:                eval/uas 0.69598
wandb:      eval/upos_accuracy 0.97507
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/w2i2pz3y
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_030207-w2i2pz3y/logs

wandb: setting up run s04yp95e

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_040339-s04yp95e
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/s04yp95e

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 11709.34it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1862.57 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2490.55 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2758.67 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2923.07 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 2974.66 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2955.09 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2780.76 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1942.86 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2180.81 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2099.65 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Fold 4 metrics: {'eval_loss': 1.5904117822647095, 'eval_uas': 0.7056454715674455, 'eval_las': 0.6822017595608793, 'eval_upos_accuracy': 0.9756842024264498}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading history steps 79-81, summary, console lines 57-59

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading data

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇███████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▄▄▄▄▇▃▆▄▄▅▆▄▄▅▇▄▅▄▅▄▅▆▆▆▅█▅▅▆▅▄▄▄▆▅▂▆▅█▁
wandb: eval/samples_per_second ▅▅▅▅▂▆▃▅▅▄▃▅▄▄▂▅▄▅▄▅▄▃▃▃▄▁▄▃▃▄▅▅▅▃▄▇▃▄▁█
wandb:   eval/steps_per_second ▅▅▅▅▂▆▃▅▅▄▃▅▄▄▂▅▄▅▄▅▄▃▃▃▄▁▄▃▃▃▅▅▄▃▄▇▃▄▁█
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▆▇▇▇▇▇███████████████████
wandb:      eval/upos_accuracy ▁▅▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇██
wandb:         train/grad_norm ▃▂▂▂▂▂▂▂▃▂▂▃▂▂▄▅▅▃▂█▂▂▃▂▃▃▂▂▂▂▃▅▂▂▂▂▁▂▂▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.6822
wandb:               eval/loss 1.59041
wandb:            eval/runtime 7.3774
wandb: eval/samples_per_second 182.584
wandb:   eval/steps_per_second 5.829
wandb:                eval/uas 0.70565
wandb:      eval/upos_accuracy 0.97568
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/s04yp95e
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_040339-s04yp95e/logs

wandb: setting up run ockrqanh

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_050511-ockrqanh
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/ockrqanh

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 14771.39it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1834.55 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2434.01 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2729.26 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2894.21 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3000.08 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2944.88 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2762.45 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1930.57 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2119.77 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2054.78 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

[W 2026-06-17 06:06:46,570] Trial 8 failed with parameters: {'learning_rate': 1.2696106442806853e-05, 'weight_decay': 0.19878446104757272, 'warmup_ratio': 0.45159834669161075, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-17 06:06:46,572] Trial 8 failed with value None.

Fold 5 metrics: {'eval_loss': 1.6034220457077026, 'eval_uas': 0.7059445791836524, 'eval_las': 0.6850456679911244, 'eval_upos_accuracy': 0.9769853965632902}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading config.yaml

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇██▇████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▂▄▅▃▅▆▅▂▅▂▄▅▅▁▇▃█▅▆▃▆▄▅▇▂▅▇▅▆▆▅▃▆█▆▃▅▃▂▁
wandb: eval/samples_per_second ▇▅▄▆▄▃▄▇▄▇▅▄▄█▂▆▁▄▃▆▃▅▄▂▇▄▂▄▃▃▄▆▃▁▃▆▄▆▇█
wandb:   eval/steps_per_second ▇▅▄▆▄▃▄▇▄▇▅▄▄█▂▆▁▄▃▅▃▅▄▂▇▄▂▄▃▃▄▆▃▁▃▆▄▆▇█
wandb:                eval/uas ▁▂▂▂▃▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇▇██▇████████████████
wandb:      eval/upos_accuracy ▁▅▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▂▃▃▄▄▄▄▅▅▅▅▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▁▂▂▂▂▂▃▃▃▃▄▄▄▄▄▄▄▅▅▅▅▆▆▆▆▇▇▇▇▇▇█████
wandb:         train/grad_norm ▅▆▃▃▃▂▂▂▃▃▃▄▃▃▇▄▄▄▅▅▃▄▄█▄▃▅▄▄▃▂▂▂▂▃▄▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.68505
wandb:               eval/loss 1.60342
wandb:            eval/runtime 7.3987
wandb: eval/samples_per_second 182.059
wandb:   eval/steps_per_second 5.812
wandb:                eval/uas 0.70594
wandb:      eval/upos_accuracy 0.97699
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial8_fold4 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/ockrqanh
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_050511-ockrqanh/logs

wandb: setting up run 3ptcx2ux

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_060647-3ptcx2ux
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold0

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/3ptcx2ux

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 13372.28it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 1 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1945.98 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2555.79 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2795.40 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2966.54 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3032.70 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3017.58 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2840.52 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1973.87 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2214.36 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2134.51 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Fold 1 metrics: {'eval_loss': 1.6434974670410156, 'eval_uas': 0.6987997859490864, 'eval_las': 0.6768595673113676, 'eval_upos_accuracy': 0.9750528756720944}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading history steps 72-73, summary, console lines 54-55

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▃▃▃▄▄▅▅▆▆▆▇▇▇▇▇▇██████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▆▁▇▂▆▃▆▆█▇▃▇▅▅▆▅▅▄▅▇▅▇▆▃▅▇▃▆▆▄▇▅▆▄▅▂
wandb: eval/samples_per_second ▃▃█▂▇▃▆▃▃▁▂▆▂▄▃▃▄▄▅▄▂▄▂▃▆▄▂▆▃▃▅▂▄▃▅▄▇
wandb:   eval/steps_per_second ▃▃█▂▇▃▆▃▃▁▂▆▁▄▃▃▄▄▅▃▂▄▂▃▆▄▂▆▃▃▅▂▄▃▅▄▇
wandb:                eval/uas ▁▂▂▂▃▃▄▄▅▅▆▆▆▇▇▇▇▇▇██████████████████
wandb:      eval/upos_accuracy ▁▅▇▇█████████████████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇▇██
wandb:         train/grad_norm ▇▃▃▂▃▃▃▃▂▂▃▃▅▄▄▆▃▃█▄▅▄▅▅▃▄▄▃▃▃▂▂▂▄▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.67686
wandb:               eval/loss 1.6435
wandb:            eval/runtime 7.3971
wandb: eval/samples_per_second 182.097
wandb:   eval/steps_per_second 5.813
wandb:                eval/uas 0.6988
wandb:      eval/upos_accuracy 0.97505
wandb:              total_flos 6.586242373995725e+16
wandb:             train/epoch 36
wandb:       train/global_step 12132
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold0 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/3ptcx2ux
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_060647-3ptcx2ux/logs

wandb: setting up run php5vl3r

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_070215-php5vl3r
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold1

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/php5vl3r

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8931.43it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 2 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1894.20 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2494.68 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2783.47 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2943.06 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3010.17 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2969.08 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2798.43 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1995.31 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2187.84 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2121.77 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Fold 2 metrics: {'eval_loss': 1.7791091203689575, 'eval_uas': 0.6719085060757684, 'eval_las': 0.649111610333912, 'eval_upos_accuracy': 0.9750331869702848}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading history steps 77-79, summary, console lines 56-58

wandb: uploading history steps 77-79, summary, console lines 56-58

wandb: uploading data

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▄▄▄▅▅▆▆▆▇▇▇▇▇▇████████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▂▆▅▃▄▃▅▅▃▅▂▆▇▄▃▄▅▂▁▄▄▆▄▄█▄▅▇▂▁▃▄▃▁▁▂▅▆▄
wandb: eval/samples_per_second ▄▇▃▄▆▅▆▄▄▆▄▇▃▂▅▆▅▄▇█▅▅▃▅▅▁▅▄▂▇█▆▅▆██▇▄▃▅
wandb:   eval/steps_per_second ▄▇▃▄▆▅▅▄▄▆▄▇▃▂▅▆▅▄▇█▅▅▃▅▅▁▅▄▂▇█▆▅▆██▇▄▃▅
wandb:                eval/uas ▁▁▂▂▃▃▃▄▄▅▅▅▆▆▇▇▇▇▇▇████████████████████
wandb:      eval/upos_accuracy ▁▄▆▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▂▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▂▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇▇███
wandb:         train/grad_norm ▃▂▂▂▂▂▂▃▄▃▄▃▃▆▄▃▅▅▄▂▃▂▄▄▃█▃▃▂▃▂▂▄▁▂▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.64911
wandb:               eval/loss 1.77911
wandb:            eval/runtime 7.4379
wandb: eval/samples_per_second 181.098
wandb:   eval/steps_per_second 5.781
wandb:                eval/uas 0.67191
wandb:      eval/upos_accuracy 0.97503
wandb:              total_flos 7.135095905162035e+16
wandb:             train/epoch 39
wandb:       train/global_step 13143
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold1 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/php5vl3r
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_070215-php5vl3r/logs

wandb: setting up run kqmhl57r

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_080216-kqmhl57r
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold2

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/kqmhl57r

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 7836.32it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 3 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1915.25 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2549.54 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2819.05 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2988.37 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3068.19 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3040.02 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2855.62 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1951.84 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2188.42 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2098.05 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Fold 3 metrics: {'eval_loss': 1.6127926111221313, 'eval_uas': 0.7211183758618058, 'eval_las': 0.6973312641514234, 'eval_upos_accuracy': 0.977205077975933}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: updating run metadata

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading output.log; uploading wandb-summary.json

wandb: uploading history steps 81-81, summary, console lines 58-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▁▂▂▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇█████████████████████
wandb:               eval/loss █▆▄▄▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▅▃▅▃▇▁▅▃▁▃▅▃▂▄▅▄█▃▅▆▇▃▃▅▄▄▆▅▂▆▄▃▄▄▃▅▅▄▄▄
wandb: eval/samples_per_second ▄▆▃▆▂█▄▆█▆▄▆▆▅▄▅▁▆▄▃▂▆▆▄▅▅▃▄▇▃▅▆▅▅▆▄▄▅▅▅
wandb:   eval/steps_per_second ▄▆▄▆▃▇▄▆█▆▄▆▆▅▄▅▁▆▄▃▂▆▆▄▅▅▃▄▇▃▅▆▅▅▆▄▄▅▅▅
wandb:                eval/uas ▁▁▂▂▃▃▄▄▅▅▅▆▆▆▇▇▇▇▇█████████████████████
wandb:      eval/upos_accuracy ▁▄▇▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▅▅▅▆▆▆▇▇▇▇▇██
wandb:         train/grad_norm ▄▂▂▂▃▂▂▃▂▂▄▂▂▆▄▃█▆▄▃▃▇▃▄▃▂▃▃▃▂▂▃▂▂▂▁▂▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.69733
wandb:               eval/loss 1.61279
wandb:            eval/runtime 7.428
wandb: eval/samples_per_second 181.341
wandb:   eval/steps_per_second 5.789
wandb:                eval/uas 0.72112
wandb:      eval/upos_accuracy 0.97721
wandb:              total_flos 7.318047082217472e+16
wandb:             train/epoch 40
wandb:       train/global_step 13480
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold2 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/kqmhl57r
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_080216-kqmhl57r/logs

wandb: setting up run oltetgre

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_090353-oltetgre
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold3

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/oltetgre

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 8569.98it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 4 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1909.46 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2540.25 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2795.46 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2969.49 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3015.29 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3000.35 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2826.22 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1987.28 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2234.86 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2147.42 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.06it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.07it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Fold 4 metrics: {'eval_loss': 1.5774933099746704, 'eval_uas': 0.7049016338779593, 'eval_las': 0.6829455972503655, 'eval_upos_accuracy': 0.975889399030446}

wandb: Finishing previous runs because reinit is set to 'default'.

wandb: uploading history steps 77-78, summary, console lines 56-56; updating run metadata

wandb: uploading history steps 77-78, summary, console lines 56-56

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 79-79, summary, console lines 57-58

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▂▂▃▃▄▄▅▅▅▆▆▇▆▇▇▇▇▇█▇██████████████████
wandb:               eval/loss █▅▄▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▆▂▃▄▃▁▄▄▄▄▃▄▃▂▃▅▇▄▅▄▅▄▅▇▃▅▄▅█▂▄▅▇▃▇▅█▃▃▁
wandb: eval/samples_per_second ▃▇▆▅▆█▅▅▅▅▆▅▆▇▆▄▂▅▄▅▄▅▄▂▆▄▅▄▁▇▅▄▂▆▂▄▁▆▆█
wandb:   eval/steps_per_second ▃▇▆▅▆█▅▅▅▅▆▅▆▇▆▄▂▅▄▅▄▅▄▂▆▄▅▄▁▇▅▄▂▆▂▄▁▆▆█
wandb:                eval/uas ▁▂▂▂▃▃▄▄▅▅▅▆▆▇▆▇▇▇▇▇█▇██████████████████
wandb:      eval/upos_accuracy ▁▅▇▇████████████████████████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▂▂▂▂▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇███
wandb:         train/grad_norm ▄▂▂▂▂▃▂▃▂▂▃▂▃▄▇▆▅▃▅▇▄█▇▃█▃▃▂▂▂▃▂▃▂▂▁▁▁▁
wandb:                      +2 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.68295
wandb:               eval/loss 1.57749
wandb:            eval/runtime 7.4057
wandb: eval/samples_per_second 181.886
wandb:   eval/steps_per_second 5.806
wandb:                eval/uas 0.7049
wandb:      eval/upos_accuracy 0.97589
wandb:              total_flos 7.135095905162035e+16
wandb:             train/epoch 39
wandb:       train/global_step 13143
wandb:                      +7 ...
wandb:

wandb: 🚀 View run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold3 at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/oltetgre
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260617_090353-oltetgre/logs

wandb: setting up run hfrkzfx4

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260617_100357-hfrkzfx4
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run linear_amadeusai/modernJabuticaBERT-Base-1k_trial9_fold4

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/hfrkzfx4

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 134/134 [00:00<00:00, 7383.95it/s]

[transformers] MultiTaskSentencePredictionEncoder LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
upos_classifier.weight   | MISSING |
head_classifier.weight   | MISSING |
head_classifier.bias     | MISSING |
deprel_classifier.weight | MISSING |
deprel_classifier.bias   | MISSING |
upos_classifier.bias     | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== Fold 5 / 5 =====

Map:   0%|                                      | 0/5388 [00:00<?, ? examples/s]

Map:  19%|████▋                    | 1000/5388 [00:00<00:02, 1886.83 examples/s]

Map:  37%|█████████▎               | 2000/5388 [00:00<00:01, 2521.42 examples/s]

Map:  56%|█████████████▉           | 3000/5388 [00:01<00:00, 2774.30 examples/s]

Map:  74%|██████████████████▌      | 4000/5388 [00:01<00:00, 2949.11 examples/s]

Map:  93%|███████████████████████▏ | 5000/5388 [00:01<00:00, 3029.23 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 3007.80 examples/s]

Map: 100%|█████████████████████████| 5388/5388 [00:01<00:00, 2820.80 examples/s]

Map:   0%|                                      | 0/1347 [00:00<?, ? examples/s]

Map:  74%|██████████████████▌      | 1000/1347 [00:00<00:00, 1926.93 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2174.13 examples/s]

Map: 100%|█████████████████████████| 1347/1347 [00:00<00:00, 2094.29 examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.03s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.02s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.00it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.00s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

[W 2026-06-17 10:56:25,753] Trial 9 failed with parameters: {'learning_rate': 1.3162609676636067e-05, 'weight_decay': 0.1633941432427773, 'warmup_ratio': 0.35628848630322457, 'num_train_epochs': 40} because of the following error: The value None could not be cast to float..

[W 2026-06-17 10:56:25,755] Trial 9 failed with value None.

Fold 5 metrics: {'eval_loss': 1.4945924282073975, 'eval_uas': 0.692502193095619, 'eval_las': 0.670493833531142, 'eval_upos_accuracy': 0.9770111976882192}

In [53]:
#print("Melhor Modelo:", study.best_value)
#print("Melhor Hiperparametros:", study.best_params)

# K-Folds

In [54]:
'''from sklearn.model_selection import KFold
import numpy as np
from datasets import concatenate_datasets
# Suponha que seus dados estejam assim:
# data = {'train': list de exemplos, 'val': list de exemplos}

# 1. Juntar tudo em um único data
full_data = concatenate_datasets([data['train'], data['val']])
# 2. Criar os índices para K-Fold
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Converter para numpy array só para facilitar a indexação
indices = np.arange(len(full_data))

for fold, (train_idx, val_idx) in enumerate(kf.split(full_data)):
    print(f"\n===== Fold {fold + 1} / {k} =====")

    # 3. Selecionar os dados (Dataset, não list)
    train_split = full_data.select(train_idx.tolist())
    val_split = full_data.select(val_idx.tolist())

    # 4. Tokenizar novamente usando sua função existente
    train_data, valid_data = nerdataset.create_data(train_split, val_split)

    # 5. (Re)criar o modelo (importante para que cada fold comece do zero)
    #model = model_init()  # define essa função para criar um novo modelo
    model = MultiTaskSentencePrediction.from_pretrained(
    PRETRAINED_MODEL_NAME,
    config=config,
    num_deprel_labels=len(DEPREL_LABELS), num_upos_labels=len(UPOS_LABELS), num_head_labels=100
    )
    # 6. Criar o Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=valid_data,
        compute_metrics=compute_metrics,
        data_collator=data_collator,
        # tokenizer=tokenizer,  # se necessário
        # callbacks=[early_stop_callback]  # se estiver usando
    )

    # 7. Treinar
    trainer.train()

    # 8. Avaliar
    metrics = trainer.evaluate()
    print(f"Fold {fold + 1} metrics:", metrics)
'''

'from sklearn.model_selection import KFold\nimport numpy as np\nfrom datasets import concatenate_datasets\n# Suponha que seus dados estejam assim:\n# data = {\'train\': list de exemplos, \'val\': list de exemplos}\n\n# 1. Juntar tudo em um único data\nfull_data = concatenate_datasets([data[\'train\'], data[\'val\']])\n# 2. Criar os índices para K-Fold\nk = 5\nkf = KFold(n_splits=k, shuffle=True, random_state=42)\n\n# Converter para numpy array só para facilitar a indexação\nindices = np.arange(len(full_data))\n\nfor fold, (train_idx, val_idx) in enumerate(kf.split(full_data)):\n    print(f"\n===== Fold {fold + 1} / {k} =====")\n\n    # 3. Selecionar os dados (Dataset, não list)\n    train_split = full_data.select(train_idx.tolist())\n    val_split = full_data.select(val_idx.tolist())\n\n    # 4. Tokenizar novamente usando sua função existente\n    train_data, valid_data = nerdataset.create_data(train_split, val_split)\n\n    # 5. (Re)criar o modelo (importante para que cada fold comece do zero)\n    #model = model_init()  # define essa função para criar um novo modelo\n    model = MultiTaskSentencePrediction.from_pretrained(\n    PRETRAINED_MODEL_NAME,\n    config=config,\n    num_deprel_labels=len(DEPREL_LABELS), num_upos_labels=len(UPOS_LABELS), num_head_labels=100\n    )\n    # 6. Criar o Trainer\n    trainer = Trainer(\n        model=model,\n        args=training_args,\n        train_dataset=train_data,\n        eval_dataset=valid_data,\n        compute_metrics=compute_metrics,\n        data_collator=data_collator,\n        # tokenizer=tokenizer,  # se necessário\n        # callbacks=[early_stop_callback]  # se estiver usando\n    )\n\n    # 7. Treinar\n    trainer.train()\n\n    # 8. Avaliar\n    metrics = trainer.evaluate()\n    print(f"Fold {fold + 1} metrics:", metrics)\n'

# Treinamento Modelo

In [55]:
# Setup training arguments
"""training_args = TrainingArguments(
    #output_dir= f'./ettin-decoder-150m_parser',
    eval_strategy=evaluation_strategy,
    learning_rate=4.350420087020882e-05,
    num_train_epochs=40,
    weight_decay=0.23448065843551166,
    logging_dir=logging_dir,
    label_names=label_names,
    max_grad_norm=max_grad_norm,
    lr_scheduler_type=lr_scheduler_type,
    warmup_ratio=0.4962097355105568,
    logging_strategy=logging_strategy,
    save_strategy=save_strategy,
    save_total_limit=save_total_limit,
    load_best_model_at_end=load_best_model_at_end,
    metric_for_best_model=metric_for_best_model,
    greater_is_better=greater_is_better,
    label_smoothing_factor=label_smoothing_factor,
    #report_to=report_to,
    gradient_checkpointing=gradient_checkpointing
)

#early_stop_callback = EarlyStoppingCallback(3)"""

"training_args = TrainingArguments(\n    #output_dir= f'./ettin-decoder-150m_parser',\n    eval_strategy=evaluation_strategy,\n    learning_rate=4.350420087020882e-05,\n    num_train_epochs=40,\n    weight_decay=0.23448065843551166,\n    logging_dir=logging_dir,\n    label_names=label_names,\n    max_grad_norm=max_grad_norm,\n    lr_scheduler_type=lr_scheduler_type,\n    warmup_ratio=0.4962097355105568,\n    logging_strategy=logging_strategy,\n    save_strategy=save_strategy,\n    save_total_limit=save_total_limit,\n    load_best_model_at_end=load_best_model_at_end,\n    metric_for_best_model=metric_for_best_model,\n    greater_is_better=greater_is_better,\n    label_smoothing_factor=label_smoothing_factor,\n    #report_to=report_to,\n    gradient_checkpointing=gradient_checkpointing\n)\n\n#early_stop_callback = EarlyStoppingCallback(3)"

In [56]:
"""run = wandb.init(
        # Set the wandb entity where your project will be logged (generally your team name).
        entity="gdlima-universidade-federal-de-pelotas",
        name=f"modernJabutica-Selecionado",  # <- aqui define o nome do run
        # Set the wandb project where this run will be logged.
        project="hf-optuna",
        # Track hyperparameters and run metadata.
        config={
            "learning_rate": 4.350420087020882e-05,
            "architecture": "modernJabutica-Selecionado",
            "epochs": 40,
            "weight_decay": 0.23448065843551166,
            "warmup_ratio": 0.4962097355105568,
        },
    )"""

'run = wandb.init(\n        # Set the wandb entity where your project will be logged (generally your team name).\n        entity="gdlima-universidade-federal-de-pelotas",\n        name=f"modernJabutica-Selecionado",  # <- aqui define o nome do run\n        # Set the wandb project where this run will be logged.\n        project="hf-optuna",\n        # Track hyperparameters and run metadata.\n        config={\n            "learning_rate": 4.350420087020882e-05,\n            "architecture": "modernJabutica-Selecionado",\n            "epochs": 40,\n            "weight_decay": 0.23448065843551166,\n            "warmup_ratio": 0.4962097355105568,\n        },\n    )'

In [57]:
#model

In [58]:
"""# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_data,
    eval_dataset=valid_data,
    # tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    data_collator=data_collator,
    
    #callbacks=[early_stop_callback]
)"""

'# Initialize the Trainer\ntrainer = Trainer(\n    model=model,\n    args=training_args,\n    train_dataset=train_data,\n    eval_dataset=valid_data,\n    # tokenizer=tokenizer,\n    compute_metrics=compute_metrics,\n    data_collator=data_collator,\n    \n    #callbacks=[early_stop_callback]\n)'

In [59]:
#trainer.train()

In [60]:
#trainer.evaluate()

In [61]:
"""import json
import pandas as pd
from pathlib import Path

# ======================================================
# CAMINHO DO ARQUIVO JSONL
# (1 JSON por linha)
# ======================================================

json_file = "results_bertimbau_large.jsonl"

# ======================================================
# LEITURA DO ARQUIVO
# ======================================================

records = []

with open(json_file, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()

        # ignora linhas vazias
        if not line:
            continue

        obj = json.loads(line)

        row = {
            "model": obj["name"],
            "fold": obj["Fold"],
            "trial": obj["trial_number"],
            "las": obj["las"],
        }

        # adiciona hiperparâmetros
        row.update(obj["hyperparameters"])

        records.append(row)

# ======================================================
# DATAFRAME
# ======================================================

df = pd.DataFrame(records)

print("\n================ DADOS CARREGADOS ================\n")
print(df.head())

# ======================================================
# CROSS VALIDATION
# ======================================================

group_cols = [
    "model",
    "trial",
    "learning_rate",
    "num_train_epochs",
    "weight_decay",
    "warmup_ratio",
]

cv_results = (
    df.groupby(group_cols)
    .agg(
        mean_las=("las", "mean"),
        std_las=("las", "std"),
        min_las=("las", "min"),
        max_las=("las", "max"),
        folds=("las", "count"),
    )
    .reset_index()
)

# ordena pelo melhor LAS médio
cv_results = cv_results.sort_values(
    by="mean_las",
    ascending=False
)

# ======================================================
# MELHOR HIPERPARÂMETRO
# ======================================================

best = cv_results.iloc[0]

print("\n================ MELHOR HIPERPARÂMETRO ================\n")

print(f"Modelo: {best['model']}")
print(f"Trial: {best['trial']}")

print("\nHiperparâmetros:")
print(f"  learning_rate    = {best['learning_rate']}")
print(f"  num_train_epochs = {best['num_train_epochs']}")
print(f"  weight_decay     = {best['weight_decay']}")
print(f"  warmup_ratio     = {best['warmup_ratio']}")

print("\nResultados Cross Validation:")
print(f"  Mean LAS = {best['mean_las']:.6f}")
print(f"  Std LAS  = {best['std_las']:.6f}")
print(f"  Min LAS  = {best['min_las']:.6f}")
print(f"  Max LAS  = {best['max_las']:.6f}")
print(f"  Folds    = {best['folds']}")

# ======================================================
# SALVAR RANKING COMPLETO
# ======================================================

output_csv = "cv_results.csv"

cv_results.to_csv(output_csv, index=False)

print(f"\nRanking salvo em: {output_csv}")

# ======================================================
# TOP 10
# ======================================================

print("\n================ TOP 10 ================\n")

print(
    cv_results[
        [
            "model",
            "trial",
            "mean_las",
            "std_las",
            "learning_rate",
            "weight_decay",
            "warmup_ratio",
        ]
    ]
    .head(10)
    .to_string(index=False)
)"""

'import json\nimport pandas as pd\nfrom pathlib import Path\n\n# ======================================================\n# CAMINHO DO ARQUIVO JSONL\n# (1 JSON por linha)\n# ======================================================\n\njson_file = "results_bertimbau_large.jsonl"\n\n# ======================================================\n# LEITURA DO ARQUIVO\n# ======================================================\n\nrecords = []\n\nwith open(json_file, "r", encoding="utf-8") as f:\n    for line in f:\n        line = line.strip()\n\n        # ignora linhas vazias\n        if not line:\n            continue\n\n        obj = json.loads(line)\n\n        row = {\n            "model": obj["name"],\n            "fold": obj["Fold"],\n            "trial": obj["trial_number"],\n            "las": obj["las"],\n        }\n\n        # adiciona hiperparâmetros\n        row.update(obj["hyperparameters"])\n\n        records.append(row)\n\n# ======================================================\n# DATAFRAME\n# ======================================================\n\ndf = pd.DataFrame(records)\n\nprint("\n================ DADOS CARREGADOS ================\n")\nprint(df.head())\n\n# ======================================================\n# CROSS VALIDATION\n# ======================================================\n\ngroup_cols = [\n    "model",\n    "trial",\n    "learning_rate",\n    "num_train_epochs",\n    "weight_decay",\n    "warmup_ratio",\n]\n\ncv_results = (\n    df.groupby(group_cols)\n    .agg(\n        mean_las=("las", "mean"),\n        std_las=("las", "std"),\n        min_las=("las", "min"),\n        max_las=("las", "max"),\n        folds=("las", "count"),\n    )\n    .reset_index()\n)\n\n# ordena pelo melhor LAS médio\ncv_results = cv_results.sort_values(\n    by="mean_las",\n    ascending=False\n)\n\n# ======================================================\n# MELHOR HIPERPARÂMETRO\n# ======================================================\n\nbest = cv_results.iloc[0]\n\nprint("\n================ MELHOR HIPERPARÂMETRO ================\n")\n\nprint(f"Modelo: {best[\'model\']}")\nprint(f"Trial: {best[\'trial\']}")\n\nprint("\nHiperparâmetros:")\nprint(f"  learning_rate    = {best[\'learning_rate\']}")\nprint(f"  num_train_epochs = {best[\'num_train_epochs\']}")\nprint(f"  weight_decay     = {best[\'weight_decay\']}")\nprint(f"  warmup_ratio     = {best[\'warmup_ratio\']}")\n\nprint("\nResultados Cross Validation:")\nprint(f"  Mean LAS = {best[\'mean_las\']:.6f}")\nprint(f"  Std LAS  = {best[\'std_las\']:.6f}")\nprint(f"  Min LAS  = {best[\'min_las\']:.6f}")\nprint(f"  Max LAS  = {best[\'max_las\']:.6f}")\nprint(f"  Folds    = {best[\'folds\']}")\n\n# ======================================================\n# SALVAR RANKING COMPLETO\n# ======================================================\n\noutput_csv = "cv_results.csv"\n\ncv_results.to_csv(output_csv, index=False)\n\nprint(f"\nRanking salvo em: {output_csv}")\n\n# ======================================================\n# TOP 10\n# ======================================================\n\nprint("\n================ TOP 10 ================\n")\n\nprint(\n    cv_results[\n        [\n            "model",\n            "trial",\n            "mean_las",\n            "std_las",\n            "learning_rate",\n            "weight_decay",\n            "warmup_ratio",\n        ]\n    ]\n    .head(10)\n    .to_string(index=False)\n)'