# Ablação Linear — DEPREL + HEAD sem UPOS

Treina os 4 modelos com os melhores hiperparâmetros do Optuna (`cv_results_*_linear.csv`) mas **sem a cabeça de UPOS**, para avaliar o impacto do POS tagging auxiliar sobre UAS/LAS.

**Modelos:** mBERT · BERTimbau-Base · BERTimbau-Large · ModernJabuticaBERT

In [1]:
import os, random, numpy as np, torch

def seed_everything(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    os.environ["PYTHONHASHSEED"] = str(seed)
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    print(f"Seed definida como {seed}")

seed_everything(42)

Seed definida como 42

In [2]:
import numpy as np
import os, json, gc, shutil
from datetime import datetime
import pandas as pd
from tqdm import tqdm
import torch
import torch.nn as nn
from typing import Optional

import datasets
from datasets import Dataset, DatasetDict, load_from_disk

from transformers import (
    AutoTokenizer, AutoConfig, AutoModel,
    BertPreTrainedModel,
    Trainer, TrainingArguments, EarlyStoppingCallback,
)

/home/guilhermelima/msc/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Labels

In [3]:
DEPREL_LABELS = [
    'det', 'nsubj', 'root', 'obj', 'xcomp', 'punct', 'mark', 'advcl', 'case',
    'obl', 'amod', 'conj', 'cc', 'nmod', 'advmod', 'flat:name', 'ccomp', 'cop',
    'acl', 'nummod', 'acl:relcl', 'ccomp:speech', 'parataxis', 'csubj',
    'aux:pass', 'appos', 'fixed', 'nsubj:pass', 'aux', 'nsubj:outer',
    'obl:agent', 'expl:impers', 'expl', 'discourse', 'orphan', 'dislocated',
    'flat', 'flat:foreign', 'iobj', 'vocative', 'csubj:outer', 'list',
    'reparandum', 'csubj:pass',
]

DEPREL_LABELS_TO_IDX = {l: i for i, l in enumerate(DEPREL_LABELS)}
IDX_TO_DEPREL_LABELS = {i: l for l, i in DEPREL_LABELS_TO_IDX.items()}

print(f"DEPREL labels: {len(DEPREL_LABELS)}")

DEPREL labels: 44

## Melhores hiperparâmetros (Optuna linear)

In [4]:
# Linha 0 de cada cv_results_*_linear.csv = melhor média de LAS no k-fold
BEST_HPS_LINEAR = {
    "google-bert/bert-base-multilingual-cased": {
        "learning_rate":   3.625756168886472e-05,
        "weight_decay":    0.19673026818206146,
        "warmup_ratio":    0.42050513822312574,
        "num_train_epochs": 40,
    },
    "neuralmind/bert-base-portuguese-cased": {
        "learning_rate":   4.423627211584912e-05,
        "weight_decay":    0.2143062841617503,
        "warmup_ratio":    0.36745951295566587,
        "num_train_epochs": 40,
    },
    "neuralmind/bert-large-portuguese-cased": {
        "learning_rate":   3.755373147243102e-05,
        "weight_decay":    0.12615267832325944,
        "warmup_ratio":    0.4036975194086722,
        "num_train_epochs": 40,
    },
    "amadeusai/modernJabuticaBERT-Base-1k": {
        "learning_rate":   4.9263783534529467e-05,
        "weight_decay":    0.1496766408078372,
        "warmup_ratio":    0.43543301938527523,
        "num_train_epochs": 40,
    },
}

MODELS = list(BEST_HPS_LINEAR.keys())
print("Modelos:", MODELS)

Modelos: ['google-bert/bert-base-multilingual-cased', 'neuralmind/bert-base-portuguese-cased', 'neuralmind/bert-large-portuguese-cased', 'amadeusai/modernJabuticaBERT-Base-1k']

## Carregamento dos dados

In [5]:
import ast

def load_csv_as_hf_dataset(filepath):
    df = pd.read_csv(filepath)
    records = []
    for _, row in df.iterrows():
        records.append({
            'tokens':     ast.literal_eval(row['tokens']),
            'upos':       ast.literal_eval(row['upos']),
            'deprel':     ast.literal_eval(row['deprel']),
            'head_tags':  ast.literal_eval(str(row['head_tags'])),
            'deprel_tags':ast.literal_eval(str(row['deprel_tags'])),
            'upos_tags':  ast.literal_eval(str(row['upos_tags'])),
        })
    return Dataset.from_list(records)

data = DatasetDict({
    'train': load_csv_as_hf_dataset('/home/guilhermelima/msc/data_dois/train_outxpos.csv'),
    'val':   load_csv_as_hf_dataset('/home/guilhermelima/msc/data_dois/val_outxpos.csv'),
    'test':  load_csv_as_hf_dataset('/home/guilhermelima/msc/data_dois/test_outxpos.csv'),
})
data

DatasetDict({
    train: Dataset({
        features: ['tokens', 'upos', 'deprel', 'head_tags', 'deprel_tags', 'upos_tags'],
        num_rows: 5893
    })
    val: Dataset({
        features: ['tokens', 'upos', 'deprel', 'head_tags', 'deprel_tags', 'upos_tags'],
        num_rows: 842
    })
    test: Dataset({
        features: ['tokens', 'upos', 'deprel', 'head_tags', 'deprel_tags', 'upos_tags'],
        num_rows: 1683
    })
})

## Modelo — Linear sem UPOS

In [6]:
# Ablação: apenas DEPREL + HEAD, sem cabeça de UPOS
class MultiTaskSentencePredictionEncoderAblacao(BertPreTrainedModel):
    _tied_weights_keys = []
    all_tied_weights_keys = {}

    def __init__(self, config, num_deprel_labels, num_head_labels=200):
        super().__init__(config)
        self.num_deprel_labels = num_deprel_labels
        self.num_head_labels   = num_head_labels

        self.bert = AutoModel.from_config(config)

        self.deprel_classifier = nn.Linear(config.hidden_size, num_deprel_labels)
        self.head_classifier   = nn.Linear(config.hidden_size, num_head_labels)

        classifier_dropout = (
            getattr(config, 'classifier_dropout', None)
            or getattr(config, 'hidden_dropout_prob', 0.1)
        )
        self.dropout = nn.Dropout(classifier_dropout)
        self.init_weights()

    def forward(
        self,
        input_ids:      torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        token_type_ids: Optional[torch.Tensor] = None,
        deprel_label:   Optional[torch.Tensor] = None,
        head_label:     Optional[torch.Tensor] = None,
    ):
        try:
            outputs = self.bert(
                input_ids=input_ids,
                attention_mask=attention_mask,
                token_type_ids=token_type_ids,
            )
        except TypeError:
            outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)

        sequence_output = self.dropout(outputs[0])

        logits_deprel = self.deprel_classifier(sequence_output)
        logits_head   = self.head_classifier(sequence_output)

        loss = None
        if deprel_label is not None and head_label is not None:
            loss_fct = nn.CrossEntropyLoss(ignore_index=-100)
            loss = (
                loss_fct(logits_deprel.view(-1, self.num_deprel_labels), deprel_label.view(-1))
                + loss_fct(logits_head.view(-1, self.num_head_labels),   head_label.view(-1))
            )

        if loss is not None:
            return (loss, logits_deprel, logits_head)
        return (logits_deprel, logits_head)

## POSDataset — sem UPOS

In [7]:
class POSDataset:
    def __init__(self, tokenizer_ckpt):
        self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_ckpt)

    def align_labels_with_tokens(self, labels, word_ids):
        new_labels, current_word = [], None
        for word_id in word_ids:
            if word_id != current_word:
                current_word = word_id
                try:
                    label = -100 if word_id is None else labels[word_id]
                except Exception:
                    label = -100
                new_labels.append(label)
            elif word_id is None:
                new_labels.append(-100)
            else:
                new_labels.append(labels[word_id])
        return new_labels

    def preprocess_function(self, examples):
        tokenized_inputs = self.tokenizer(
            examples["tokens"],
            truncation=True,
            padding="max_length",
            is_split_into_words=True,
            max_length=512,
        )
        all_deprel = examples["deprel_tags"]
        all_head   = examples["head_tags"]
        new_deprel, new_head = [], []
        for i, (dep, head) in enumerate(zip(all_deprel, all_head)):
            word_ids = tokenized_inputs.word_ids(i)
            new_deprel.append(self.align_labels_with_tokens(dep,  word_ids))
            new_head.append(  self.align_labels_with_tokens(head, word_ids))
        tokenized_inputs["deprel_label"] = new_deprel
        tokenized_inputs["head_label"]   = new_head
        return tokenized_inputs

    def create_data(self, train, test):
        tkn_train = train.map(self.preprocess_function, batched=True, remove_columns=train.column_names)
        tkn_test  = test.map( self.preprocess_function, batched=True, remove_columns=test.column_names)
        return tkn_train, tkn_test

## Data Collator

In [8]:
def data_collator(batch):
    input_ids       = [item["input_ids"]       for item in batch]
    attention_masks = [item["attention_mask"]   for item in batch]
    deprel_label    = [item["deprel_label"]     for item in batch]
    head_label      = [item["head_label"]       for item in batch]

    max_len = max(len(ids) for ids in input_ids)
    PAD = 0

    return {
        "input_ids":      torch.tensor([ids + [PAD]  * (max_len - len(ids))  for ids  in input_ids]),
        "attention_mask": torch.tensor([m   + [0]    * (max_len - len(m))    for m    in attention_masks]),
        "deprel_label":   torch.tensor([l   + [-100] * (max_len - len(l))    for l    in deprel_label]),
        "head_label":     torch.tensor([l   + [-100] * (max_len - len(l))    for l    in head_label]),
    }

## Compute Metrics

In [9]:
import numpy as np
import json
import os

def softmax(x, axis=-1):
    e_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return e_x / e_x.sum(axis=axis, keepdims=True)


def compute_metrics(eval_pred, PRETRAINED_MODEL=None):
    save_path = f"epoch_predictions/{PRETRAINED_MODEL.split('/')[-1] if PRETRAINED_MODEL else 'unknown_model'}_predictions_ablacao_linear.json"
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    model_name = PRETRAINED_MODEL.split("/")[-1] if PRETRAINED_MODEL else "unknown_model"
    run_id = model_name

    logits, labels = eval_pred
    deprel_logits, head_logits = logits
    deprel_labels, head_labels = labels

    # ---------------- PROBABILIDADES ----------------
    deprel_probs = softmax(deprel_logits, axis=-1)
    head_probs   = softmax(head_logits,   axis=-1)

    # ---------------- PREDIÇÕES ----------------
    deprel_preds = np.argmax(deprel_logits, axis=-1)
    head_preds   = np.argmax(head_logits,   axis=-1)

    # ---------------- MASK DEPENDENCY ----------------
    valid_mask = (head_labels != -100) & (deprel_labels != -100)

    head_preds_masked    = head_preds[valid_mask]
    head_labels_masked   = head_labels[valid_mask]
    head_probs_masked    = head_probs[valid_mask]
    deprel_preds_masked  = deprel_preds[valid_mask]
    deprel_labels_masked = deprel_labels[valid_mask]
    deprel_probs_masked  = deprel_probs[valid_mask]

    # ---------------- MÉTRICAS PRINCIPAIS ----------------
    uas = (head_preds_masked == head_labels_masked).mean()
    las = (
        (head_preds_masked == head_labels_masked) &
        (deprel_preds_masked == deprel_labels_masked)
    ).mean()

    # ---------------- CARREGAR JSON ----------------
    if os.path.exists(save_path):
        with open(save_path, "r", encoding="utf-8") as f:
            all_data = json.load(f)
    else:
        all_data = {}

    if "META" not in all_data:
        all_data["META"] = {
            "model_name": model_name,
            "pretrained_model": PRETRAINED_MODEL,
            "run_id": run_id,
        }

    if "RANK_PREDICTIONS" not in all_data:
        all_data["RANK_PREDICTIONS"] = {"deprel": [], "head": []}

    def get_correct_rank(prob_vector, correct_label):
        sorted_indices = np.argsort(prob_vector)[::-1]
        return int(np.where(sorted_indices == correct_label)[0][0] + 1)

    # ---------------- DEPREL ----------------
    for i in range(len(deprel_preds_masked)):
        probs         = deprel_probs_masked[i]
        correct_label = int(deprel_labels_masked[i])
        pred_label    = int(deprel_preds_masked[i])
        all_data["RANK_PREDICTIONS"]["deprel"].append({
            "run_id":        run_id,
            "model":         model_name,
            "index":         i,
            "correct_label": correct_label,
            "pred_label":    pred_label,
            "correct_prob":  float(probs[correct_label]),
            "pred_prob":     float(probs[pred_label]),
            "correct_rank":  get_correct_rank(probs, correct_label),
        })

    # ---------------- HEAD ----------------
    for i in range(len(head_preds_masked)):
        probs         = head_probs_masked[i]
        correct_label = int(head_labels_masked[i])
        pred_label    = int(head_preds_masked[i])
        all_data["RANK_PREDICTIONS"]["head"].append({
            "run_id":        run_id,
            "model":         model_name,
            "index":         i,
            "correct_label": correct_label,
            "pred_label":    pred_label,
            "correct_prob":  float(probs[correct_label]),
            "pred_prob":     float(probs[pred_label]),
            "correct_rank":  get_correct_rank(probs, correct_label),
        })

    # ---------------- SALVAR ----------------
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(all_data, f, indent=2, ensure_ascii=False)

    return {"uas": float(uas), "las": float(las)}

## CUDA diagnóstico

In [10]:
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

if torch.cuda.is_available():
    t = torch.tensor([1.0], device="cuda")
    assert (t * 2).item() == 2.0
    del t
    torch.cuda.empty_cache()
    print("✓ Contexto CUDA limpo")
    print(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CPU mode")

✓ Contexto CUDA limpo
GPU: NVIDIA GeForce RTX 4090

## Wandb

In [11]:
os.environ["WANDB_API_KEY"] = "7499f50c2fffad3ce3e34b7b7b02152988a1742c"
import wandb

## Função de treino com HPs fixos (train/val original)

In [12]:
def train_ablacao_linear(name_model, best_hps, results_filename="ablacao_linear_results.jsonl"):
    learning_rate    = best_hps["learning_rate"]
    weight_decay     = best_hps["weight_decay"]
    warmup_ratio     = best_hps["warmup_ratio"]
    num_train_epochs = best_hps["num_train_epochs"]

    nerdataset = POSDataset(name_model)
    train_data, valid_data = nerdataset.create_data(data['train'], data['val'])

    print(f"\n{'='*55}")
    print(f"  {name_model}")
    print(f"{'='*55}")

    wandb.init(
        entity="gdlima-universidade-federal-de-pelotas",
        project="hf-optuna",
        name=f"ablacao_linear_{name_model.split('/')[-1]}",
        config={
            "learning_rate": learning_rate, "architecture": name_model,
            "epochs": num_train_epochs, "weight_decay": weight_decay,
            "warmup_ratio": warmup_ratio, "ablation": "sem_upos_linear",
        },
    )

    config = AutoConfig.from_pretrained(name_model)
    model  = MultiTaskSentencePredictionEncoderAblacao.from_pretrained(
        name_model, config=config,
        num_deprel_labels=len(DEPREL_LABELS),
        _fast_init=False,
    )

    for _n, _p in model.named_parameters():
        if _p.requires_grad and (torch.isnan(_p).any() or torch.isinf(_p).any()):
            raise RuntimeError(f"[CPU] Peso '{_n}' é NaN/Inf antes de mover para CUDA.")

    _device = "cuda" if torch.cuda.is_available() else "cpu"
    model   = model.to(_device)

    output_dir = f"./ablacao_linear_{name_model.replace('/','_')}"

    training_args = TrainingArguments(
        output_dir=output_dir,
        fp16=False, bf16=False,
        eval_strategy="epoch",
        learning_rate=learning_rate,
        num_train_epochs=num_train_epochs,
        weight_decay=weight_decay,
        warmup_ratio=warmup_ratio,
        max_grad_norm=1.0,
        lr_scheduler_type="linear",
        logging_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=1,
        save_only_model=True,
        load_best_model_at_end=True,
        metric_for_best_model="las",
        greater_is_better=True,
        label_smoothing_factor=0.0,
        gradient_checkpointing=False,
        remove_unused_columns=False,
        label_names=["deprel_label", "head_label"],
        report_to="wandb",
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,
        dataloader_num_workers=4,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_data,
        eval_dataset=valid_data,
        compute_metrics=lambda p: compute_metrics(p, PRETRAINED_MODEL=name_model),
        data_collator=data_collator,
        callbacks=[EarlyStoppingCallback(5)],
    )

    trainer.train()

    # --- salvar log por época ---
    train_logs = {
        int(e["epoch"]): e["loss"]
        for e in trainer.state.log_history
        if "loss" in e and "eval_loss" not in e
    }
    eval_logs = {
        int(e["epoch"]): e
        for e in trainer.state.log_history
        if "eval_loss" in e
    }
    epoch_rows = []
    for epoch in sorted(set(train_logs) | set(eval_logs)):
        epoch_rows.append({
            "Epoch":           epoch,
            "Training Loss":   train_logs.get(epoch, None),
            "Validation Loss": eval_logs[epoch]["eval_loss"] if epoch in eval_logs else None,
            "Uas":             eval_logs[epoch].get("eval_uas", None) if epoch in eval_logs else None,
            "Las":             eval_logs[epoch].get("eval_las", None) if epoch in eval_logs else None,
        })
    log_df = pd.DataFrame(epoch_rows)
    log_csv = f"training_log_ablacao_linear_{name_model.replace('/','_')}.csv"
    log_df.to_csv(log_csv, index=False)
    print(f"  Log por época salvo em: {log_csv}")
    # --- fim do log ---

    best_path = f"./best_models_ablacao_linear/{name_model.replace('/','_')}"
    trainer.save_model(best_path)
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)

    eval_result = trainer.evaluate()
    uas = eval_result.get("eval_uas", None)
    las = eval_result.get("eval_las", None)

    result_dict = {
        "name": name_model,
        "architecture": "linear_ablacao_sem_upos",
        "hyperparameters": best_hps,
        "uas": uas, "las": las,
    }

    with open(results_filename, "a", encoding="utf-8") as f:
        f.write(json.dumps(result_dict, ensure_ascii=False) + "\n")

    print(f"  UAS: {uas:.4f} | LAS: {las:.4f}")
    wandb.finish()
    return result_dict

## Treino — todos os modelos

In [13]:
all_results = {}

for model_name in MODELS:
    print(f"\n{'#'*60}")
    print(f"# ABLAÇÃO LINEAR (sem UPOS) — {model_name}")
    print(f"{'#'*60}")
    all_results[model_name] = train_ablacao_linear(model_name, BEST_HPS_LINEAR[model_name])

############################################################
# ABLAÇÃO LINEAR (sem UPOS) — google-bert/bert-base-multilingual-cased
############################################################

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Map:   0%|                                      | 0/5893 [00:00<?, ? examples/s]

Map:  17%|████▏                    | 1000/5893 [00:00<00:02, 2010.20 examples/s]

Map:  34%|████████▍                | 2000/5893 [00:00<00:01, 2808.09 examples/s]

Map:  51%|████████████▋            | 3000/5893 [00:01<00:00, 3170.95 examples/s]

Map:  68%|████████████████▉        | 4000/5893 [00:01<00:00, 3445.59 examples/s]

Map:  85%|█████████████████████▏   | 5000/5893 [00:01<00:00, 3654.21 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3747.43 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3370.95 examples/s]

Map:   0%|                                       | 0/842 [00:00<?, ? examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2059.09 examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2033.05 examples/s]

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.

=======================================================
  google-bert/bert-base-multilingual-cased
=======================================================

wandb: Currently logged in as: gdlima (gdlima-universidade-federal-de-pelotas) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: setting up run cgt8dlq4

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260619_194442-cgt8dlq4
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run ablacao_linear_bert-base-multilingual-cased

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/cgt8dlq4

Loading weights:   0%|                                  | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 199/199 [00:00<00:00, 11581.33it/s]

[transformers] MultiTaskSentencePredictionEncoderAblacao LOAD REPORT from: google-bert/bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
deprel_classifier.bias                     | MISSING    |
deprel_classifier.weight                   | MISSING    |
head_classifier.bias                       | MISSING    |
head_classifier.weight                     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.22s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.22s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.25s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.21s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.21s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.22s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.22s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.23s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.26s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.24s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.27s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.27s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.28s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.28s/it]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].

[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

  Log por época salvo em: training_log_ablacao_linear_google-bert_bert-base-multilingual-cased.csv

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.27s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.27s/it]

wandb: updating run metadata

  UAS: 0.9135 | LAS: 0.8946

wandb: uploading output.log; uploading wandb-summary.json; uploading config.yaml

wandb: uploading history steps 81-81, summary, console lines 64-64

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▃▃▄▅▆▅▆▆▇▇▇▇▇▇▇▇▇▇▇███████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇██
wandb: eval/samples_per_second █▇▆▆▅▅▅▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁
wandb:   eval/steps_per_second █▇▆▆▅▅▅▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁
wandb:                eval/uas ▁▂▂▃▄▅▅▅▆▆▇▇▇▇▇▇▇▇▇▇▇███████████████████
wandb:             train/epoch ▁▁▁▁▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▇▇▇▇▇▇▇████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇██
wandb:         train/grad_norm ▂▂▃▅▂▄▃▄▅▅▅█▃▆▄▄▅▃▃▄▂▅▂▄▂▃▂▁▃▁▃▂▃▂▂▂▁▂▁▁
wandb:     train/learning_rate ▁▂▂▃▃▄▄▄▅▅▆▆▆▇▇███▇▇▇▆▆▆▆▅▅▅▄▄▄▃▃▃▃▂▂▂▁▁
wandb:                      +1 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.89457
wandb:               eval/loss 0.88817
wandb:            eval/runtime 22.0029
wandb: eval/samples_per_second 38.268
wandb:   eval/steps_per_second 1.227
wandb:                eval/uas 0.91354
wandb:              total_flos 6.215529745661952e+16
wandb:             train/epoch 40
wandb:       train/global_step 14760
wandb:         train/grad_norm 2.58493
wandb:                      +6 ...
wandb:

wandb: 🚀 View run ablacao_linear_bert-base-multilingual-cased at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/cgt8dlq4
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260619_194442-cgt8dlq4/logs

############################################################
# ABLAÇÃO LINEAR (sem UPOS) — neuralmind/bert-base-portuguese-cased
############################################################

Map:   0%|                                      | 0/5893 [00:00<?, ? examples/s]

Map:  17%|████▏                    | 1000/5893 [00:00<00:02, 1883.31 examples/s]

Map:  34%|████████▍                | 2000/5893 [00:00<00:01, 2688.43 examples/s]

Map:  51%|████████████▋            | 3000/5893 [00:01<00:00, 3105.72 examples/s]

Map:  68%|████████████████▉        | 4000/5893 [00:01<00:00, 3396.13 examples/s]

Map:  85%|█████████████████████▏   | 5000/5893 [00:01<00:00, 3598.39 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3734.82 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3310.97 examples/s]

Map:   0%|                                       | 0/842 [00:00<?, ? examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2077.90 examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2049.76 examples/s]

=======================================================
  neuralmind/bert-base-portuguese-cased
=======================================================

wandb: setting up run sv5nido8

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260619_203917-sv5nido8
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run ablacao_linear_bert-base-portuguese-cased

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/sv5nido8

Loading weights:   0%|                                  | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 199/199 [00:00<00:00, 30614.23it/s]

[transformers] MultiTaskSentencePredictionEncoderAblacao LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
deprel_classifier.bias                     | MISSING    |
deprel_classifier.weight                   | MISSING    |
head_classifier.bias                       | MISSING    |
head_classifier.weight                     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.39it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.39it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.39it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.39it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.39it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.39it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.43it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.40it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.42it/s]

  Log por época salvo em: training_log_ablacao_linear_neuralmind_bert-base-portuguese-cased.csv

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.41it/s]

wandb: updating run metadata

  UAS: 0.9224 | LAS: 0.9081

wandb: uploading config.yaml; uploading output.log; uploading wandb-summary.json

wandb: uploading output.log; uploading wandb-summary.json

wandb: uploading history steps 73-73, summary, console lines 59-59

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▃▄▅▆▆▇▇▇▇▇▇▇█▇█████████████████████
wandb:               eval/loss █▅▄▃▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▁▁▁▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▆▆▆▆▆▆▆▇▇▇████
wandb: eval/samples_per_second █▇▇▆▅▅▅▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁
wandb:   eval/steps_per_second █▇▇▆▅▅▅▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁
wandb:                eval/uas ▁▂▃▄▅▆▆▇▇▇▇▇▇▇█▇█████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▂▂▂▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇█████
wandb:       train/global_step ▁▁▁▂▂▂▂▂▂▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇█████
wandb:         train/grad_norm ▂▂▂▂▂▃▄▃▇▆▄▄▃█▂▃▂▂▂▆▂▅▂▂▃▂▂▁▃▁▁▂▂▂▁▂
wandb:     train/learning_rate ▁▂▂▃▃▄▄▅▅▆▆▇▇███▇▇▇▆▆▆▆▅▅▅▄▄▄▃▃▃▃▂▂▂
wandb:                      +1 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.9081
wandb:               eval/loss 0.7101
wandb:            eval/runtime 18.4213
wandb: eval/samples_per_second 45.708
wandb:   eval/steps_per_second 1.466
wandb:                eval/uas 0.9224
wandb:              total_flos 5.593976771095757e+16
wandb:             train/epoch 36
wandb:       train/global_step 13284
wandb:         train/grad_norm 8.04685
wandb:                      +6 ...
wandb:

wandb: 🚀 View run ablacao_linear_bert-base-portuguese-cased at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/sv5nido8
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260619_203917-sv5nido8/logs

############################################################
# ABLAÇÃO LINEAR (sem UPOS) — neuralmind/bert-large-portuguese-cased
############################################################

Map:   0%|                                      | 0/5893 [00:00<?, ? examples/s]

Map:  17%|████▏                    | 1000/5893 [00:00<00:02, 2057.94 examples/s]

Map:  34%|████████▍                | 2000/5893 [00:00<00:01, 2899.09 examples/s]

Map:  51%|████████████▋            | 3000/5893 [00:00<00:00, 3332.57 examples/s]

Map:  68%|████████████████▉        | 4000/5893 [00:01<00:00, 3646.62 examples/s]

Map:  85%|█████████████████████▏   | 5000/5893 [00:01<00:00, 3810.39 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3929.37 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3523.76 examples/s]

Map:   0%|                                       | 0/842 [00:00<?, ? examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2175.07 examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2145.80 examples/s]

=======================================================
  neuralmind/bert-large-portuguese-cased
=======================================================

wandb: setting up run fj6tvg0f

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260619_212512-fj6tvg0f
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run ablacao_linear_bert-large-portuguese-cased

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/fj6tvg0f

Loading weights:   0%|                                  | 0/391 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 34102.87it/s]

[transformers] MultiTaskSentencePredictionEncoderAblacao LOAD REPORT from: neuralmind/bert-large-portuguese-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
head_classifier.weight                     | MISSING    |
deprel_classifier.weight                   | MISSING    |
head_classifier.bias                       | MISSING    |
deprel_classifier.bias                     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.80s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.80s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.78s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.78s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.78s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.78s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.78s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.97s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.97s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.79s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.80s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.80s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.76s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.77s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.78s/it]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

  Log por época salvo em: training_log_ablacao_linear_neuralmind_bert-large-portuguese-cased.csv

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.74s/it]

Writing model shards: 100%|███████████████████████| 1/1 [00:01<00:00,  1.75s/it]

wandb: updating run metadata

  UAS: 0.9491 | LAS: 0.9354

wandb: uploading history steps 81-81, summary, console lines 63-63; uploading wandb-summary.json; uploading config.yaml; uploading output.log

wandb: uploading data

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▃▄▅▅▇▇▇▇▇▇▇▇▇▇▇▇▇█████████████████████
wandb:               eval/loss █▅▃▃▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇███
wandb: eval/samples_per_second ██▇▇▆▆▆▅▅▅▅▄▄▄▄▄▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁
wandb:   eval/steps_per_second ██▇▇▆▆▆▅▅▅▅▄▄▄▄▄▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁
wandb:                eval/uas ▁▂▃▄▅▅▇▇▇▇▇▇▇▇▇▇▇▇▇█████████████████████
wandb:             train/epoch ▁▁▁▂▂▂▂▂▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇██
wandb:       train/global_step ▁▁▁▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇▇███
wandb:         train/grad_norm ▂▂▃▄▃▃▃▄▃▃█▆▅▇▄▄▂▂▂▃▂▂▂▂▂▂▂▁▂▂▁▁▁▁▁▂▁▁▁▁
wandb:     train/learning_rate ▁▂▂▃▃▄▄▄▅▅▆▆▇▇████▇▇▇▆▆▆▅▅▅▅▄▄▄▃▃▃▂▂▂▂▁▁
wandb:                      +1 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.93539
wandb:               eval/loss 0.65214
wandb:            eval/runtime 25.1453
wandb: eval/samples_per_second 33.485
wandb:   eval/steps_per_second 1.074
wandb:                eval/uas 0.94911
wandb:              total_flos 2.1985448186658816e+17
wandb:             train/epoch 40
wandb:       train/global_step 14760
wandb:         train/grad_norm 0.43579
wandb:                      +6 ...
wandb:

wandb: 🚀 View run ablacao_linear_bert-large-portuguese-cased at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/fj6tvg0f
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260619_212512-fj6tvg0f/logs

############################################################
# ABLAÇÃO LINEAR (sem UPOS) — amadeusai/modernJabuticaBERT-Base-1k
############################################################

Map:   0%|                                      | 0/5893 [00:00<?, ? examples/s]

Map:  17%|████▏                    | 1000/5893 [00:00<00:02, 2424.37 examples/s]

Map:  34%|████████▍                | 2000/5893 [00:00<00:01, 3206.54 examples/s]

Map:  51%|████████████▋            | 3000/5893 [00:00<00:00, 3556.21 examples/s]

Map:  68%|████████████████▉        | 4000/5893 [00:01<00:00, 3709.90 examples/s]

Map:  85%|█████████████████████▏   | 5000/5893 [00:01<00:00, 3836.76 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3914.37 examples/s]

Map: 100%|█████████████████████████| 5893/5893 [00:01<00:00, 3640.67 examples/s]

Map:   0%|                                       | 0/842 [00:00<?, ? examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2452.06 examples/s]

Map: 100%|███████████████████████████| 842/842 [00:00<00:00, 2415.56 examples/s]

=======================================================
  amadeusai/modernJabuticaBERT-Base-1k
=======================================================

wandb: setting up run qjl2rgac

wandb: Tracking run with wandb version 0.27.2

wandb: Run data is saved locally in /home/guilhermelima/msc/wandb/run-20260619_234149-qjl2rgac
wandb: Run `wandb offline` to turn off syncing.

wandb: Syncing run ablacao_linear_modernJabuticaBERT-Base-1k

wandb: ⭐️ View project at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna

wandb: 🚀 View run at https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/qjl2rgac

Loading weights:   0%|                                  | 0/134 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 134/134 [00:00<00:00, 10094.41it/s]

[transformers] MultiTaskSentencePredictionEncoderAblacao LOAD REPORT from: amadeusai/modernJabuticaBERT-Base-1k
Key                      | Status  |
-------------------------+---------+-
deprel_classifier.bias   | MISSING |
deprel_classifier.weight | MISSING |
head_classifier.bias     | MISSING |
head_classifier.weight   | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.05it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.02it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.01it/s]

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.04it/s]

  Log por época salvo em: training_log_ablacao_linear_amadeusai_modernJabuticaBERT-Base-1k.csv

Writing model shards:   0%|                               | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

Writing model shards: 100%|███████████████████████| 1/1 [00:00<00:00,  1.03it/s]

wandb: updating run metadata

  UAS: 0.8679 | LAS: 0.8469

wandb: uploading config.yaml; uploading output.log

wandb:
wandb: Run history:
wandb:                eval/las ▁▂▃▃▄▄▅▆▆▆▆▆▆▇▇▇▇▇▇█████████████████████
wandb:               eval/loss █▅▄▃▃▂▂▂▂▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            eval/runtime ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇█▇██
wandb: eval/samples_per_second █▇▇▆▆▅▅▅▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁
wandb:   eval/steps_per_second █▇▇▆▆▅▅▅▄▄▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁
wandb:                eval/uas ▁▂▃▃▄▄▅▆▆▆▆▆▆▆▇▇▇▇▇█████████████████████
wandb:             train/epoch ▁▁▁▁▁▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇▇████
wandb:       train/global_step ▁▁▁▁▂▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇███
wandb:         train/grad_norm ▄▄▄▅▄▄▅▄▇▄▅▄▄▆▃█▃▅█▄▂▄▅▄▁▂▃▁▂▁▁▁▁▁▁▁▁▁▁▁
wandb:     train/learning_rate ▁▂▂▃▃▃▄▄▅▅▆▆▆▇▇████▇▇▇▆▆▆▅▅▅▄▄▄▄▃▃▃▂▂▂▁▁
wandb:                      +1 ...
wandb:
wandb: Run summary:
wandb:                eval/las 0.84691
wandb:               eval/loss 1.16279
wandb:            eval/runtime 25.7022
wandb: eval/samples_per_second 32.76
wandb:   eval/steps_per_second 1.05
wandb:                eval/uas 0.86792
wandb:              total_flos 8.003053247840256e+16
wandb:             train/epoch 40
wandb:       train/global_step 14760
wandb:         train/grad_norm 0.03704
wandb:                      +6 ...
wandb:

wandb: 🚀 View run ablacao_linear_modernJabuticaBERT-Base-1k at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna/runs/qjl2rgac
wandb: ⭐️ View project at: https://wandb.ai/gdlima-universidade-federal-de-pelotas/hf-optuna
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)

wandb: Find logs at: ./wandb/run-20260619_234149-qjl2rgac/logs

## Inferência no conjunto de teste

In [14]:
dataset_test = load_from_disk('/home/guilhermelima/msc/data_dois/complaints_dataset_obj_outxpos')
test_dataset  = dataset_test['test']
test_sentences = test_dataset['tokens']
test_deprel    = test_dataset['deprel']
test_head      = test_dataset['head_tags']

print(f"Test set: {len(test_sentences)} sentenças")
print(f"Exemplo: {test_sentences[0]}")

Test set: 1683 sentenças
Exemplo: ['O', 'Capitão', 'América', 'também', 'bajulou', 'o', 'tucano', '.']

In [15]:
def get_predictions_on_dataframe(sentences, model, tokenizer, device="cuda"):
    predictions_deprel, predictions_head = [], []

    model.eval()
    model.to(device)

    for tokens in tqdm(sentences):
        inputs = tokenizer(
            tokens, is_split_into_words=True,
            return_tensors="pt", padding=True, truncation=True,
        ).to(device)

        with torch.no_grad():
            model_outputs = model(**inputs)

        logits_deprel = model_outputs[0]
        logits_head   = model_outputs[1]
        word_ids = inputs.word_ids(batch_index=0)

        sent_deprel, sent_head = [], []
        for token_idx in range(len(tokens)):
            sub_idxs = [i for i, w in enumerate(word_ids) if w == token_idx]
            if sub_idxs:
                first = sub_idxs[0]
                prob_d = torch.softmax(logits_deprel[0, first], dim=-1)
                prob_h = torch.softmax(logits_head[0, first],   dim=-1)
                sent_deprel.append(IDX_TO_DEPREL_LABELS[torch.argmax(prob_d).item()])
                sent_head.append(torch.argmax(prob_h).item())

        predictions_deprel.append(sent_deprel)
        predictions_head.append(sent_head)

    return pd.DataFrame({
        "tokens":             sentences,
        "deprel_predictions": predictions_deprel,
        "head_predictions":   predictions_head,
    })

In [16]:
def compute_dependency_metrics(test_sentences, test_deprel, test_head, predict_df):
    total = uas_correct = las_correct = skipped = 0

    for i in range(len(test_sentences)):
        gold_d = test_deprel[i]
        gold_h = test_head[i]
        pred_d = predict_df['deprel_predictions'].iloc[i]
        pred_h = predict_df['head_predictions'].iloc[i]

        for j in range(len(gold_h)):
            if j >= len(pred_h) or pred_h[j] is None or pred_d[j] is None:
                skipped += 1
                continue
            total += 1
            if pred_h[j] == gold_h[j]:
                uas_correct += 1
                if pred_d[j] == gold_d[j]:
                    las_correct += 1

    return {
        'uas':          uas_correct / total if total > 0 else 0,
        'las':          las_correct / total if total > 0 else 0,
        'total_tokens': total,
        'skipped':      skipped,
    }

In [17]:
_device = "cuda" if torch.cuda.is_available() else "cpu"
final_metrics = {}

for model_name in MODELS:
    print(f"\n{'='*50}")
    print(f"Inferência: {model_name}")

    best_model_path = f"./best_models_ablacao_linear/{model_name.replace('/','_')}"
    val_las = all_results[model_name]["las"]
    print(f"Modelo salvo em: {best_model_path} | LAS val = {val_las:.4f}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    config    = AutoConfig.from_pretrained(best_model_path)
    model     = MultiTaskSentencePredictionEncoderAblacao.from_pretrained(
        best_model_path, config=config,
        num_deprel_labels=len(DEPREL_LABELS),
    ).to(_device)

    predict_df = get_predictions_on_dataframe(test_sentences, model, tokenizer, device=_device)
    metrics    = compute_dependency_metrics(test_sentences, test_deprel, test_head, predict_df)
    final_metrics[model_name] = metrics

    print(f"  UAS: {metrics['uas']:.4f}")
    print(f"  LAS: {metrics['las']:.4f}")
    print(f"  Total tokens: {metrics['total_tokens']} | Ignorados: {metrics['skipped']}")

    out_csv = f"./predict_test_ablacao_linear_{model_name.replace('/','_')}.csv"
    predict_df.to_csv(out_csv, index=False)
    print(f"  Salvo em: {out_csv}")

==================================================
Inferência: google-bert/bert-base-multilingual-cased
Modelo salvo em: ./best_models_ablacao_linear/google-bert_bert-base-multilingual-cased | LAS val = 0.8946

Loading weights:   0%|                                  | 0/203 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 203/203 [00:00<00:00, 7439.76it/s]

  0%|                                                  | 0/1683 [00:00<?, ?it/s]

  1%|▎                                       | 11/1683 [00:00<00:15, 104.76it/s]

  1%|▌                                       | 25/1683 [00:00<00:13, 119.74it/s]

  2%|▉                                       | 39/1683 [00:00<00:13, 124.79it/s]

  3%|█▏                                      | 52/1683 [00:00<00:13, 123.72it/s]

  4%|█▌                                      | 65/1683 [00:00<00:12, 124.84it/s]

  5%|█▊                                      | 78/1683 [00:00<00:12, 126.39it/s]

  5%|██▏                                     | 91/1683 [00:00<00:12, 127.07it/s]

  6%|██▍                                    | 104/1683 [00:00<00:12, 126.60it/s]

  7%|██▋                                    | 117/1683 [00:00<00:12, 125.87it/s]

  8%|███                                    | 130/1683 [00:01<00:12, 125.85it/s]

  8%|███▎                                   | 143/1683 [00:01<00:12, 126.58it/s]

  9%|███▌                                   | 156/1683 [00:01<00:12, 127.18it/s]

 10%|███▉                                   | 169/1683 [00:01<00:11, 126.53it/s]

 11%|████▏                                  | 182/1683 [00:01<00:11, 127.15it/s]

 12%|████▌                                  | 195/1683 [00:01<00:11, 127.84it/s]

 12%|████▊                                  | 208/1683 [00:01<00:11, 127.05it/s]

 13%|█████                                  | 221/1683 [00:01<00:11, 124.86it/s]

 14%|█████▍                                 | 234/1683 [00:01<00:11, 124.21it/s]

 15%|█████▋                                 | 247/1683 [00:01<00:11, 125.41it/s]

 16%|██████                                 | 261/1683 [00:02<00:11, 127.59it/s]

 16%|██████▎                                | 274/1683 [00:02<00:11, 127.24it/s]

 17%|██████▋                                | 288/1683 [00:02<00:10, 128.36it/s]

 18%|██████▉                                | 301/1683 [00:02<00:10, 127.13it/s]

 19%|███████▎                               | 314/1683 [00:02<00:10, 126.79it/s]

 19%|███████▌                               | 328/1683 [00:02<00:10, 127.72it/s]

 20%|███████▉                               | 341/1683 [00:02<00:10, 127.50it/s]

 21%|████████▏                              | 355/1683 [00:02<00:10, 128.26it/s]

 22%|████████▌                              | 368/1683 [00:02<00:10, 125.81it/s]

 23%|████████▊                              | 381/1683 [00:03<00:10, 126.78it/s]

 23%|█████████▏                             | 394/1683 [00:03<00:10, 127.24it/s]

 24%|█████████▍                             | 408/1683 [00:03<00:09, 128.46it/s]

 25%|█████████▊                             | 421/1683 [00:03<00:09, 126.52it/s]

 26%|██████████                             | 434/1683 [00:03<00:09, 126.21it/s]

 27%|██████████▎                            | 447/1683 [00:03<00:09, 124.67it/s]

 27%|██████████▋                            | 460/1683 [00:03<00:09, 125.01it/s]

 28%|██████████▉                            | 473/1683 [00:03<00:09, 125.89it/s]

 29%|███████████▎                           | 486/1683 [00:03<00:09, 125.05it/s]

 30%|███████████▌                           | 499/1683 [00:03<00:09, 125.91it/s]

 30%|███████████▊                           | 512/1683 [00:04<00:09, 125.65it/s]

 31%|████████████▏                          | 525/1683 [00:04<00:09, 125.96it/s]

 32%|████████████▍                          | 538/1683 [00:04<00:09, 126.60it/s]

 33%|████████████▊                          | 551/1683 [00:04<00:08, 126.52it/s]

 34%|█████████████                          | 564/1683 [00:04<00:08, 126.51it/s]

 34%|█████████████▎                         | 577/1683 [00:04<00:08, 125.97it/s]

 35%|█████████████▋                         | 590/1683 [00:04<00:08, 125.17it/s]

 36%|█████████████▉                         | 603/1683 [00:04<00:08, 125.36it/s]

 37%|██████████████▎                        | 616/1683 [00:04<00:08, 126.13it/s]

 37%|██████████████▌                        | 629/1683 [00:04<00:08, 126.69it/s]

 38%|██████████████▉                        | 642/1683 [00:05<00:08, 125.70it/s]

 39%|███████████████▏                       | 655/1683 [00:05<00:08, 124.36it/s]

 40%|███████████████▍                       | 668/1683 [00:05<00:08, 124.57it/s]

 40%|███████████████▊                       | 681/1683 [00:05<00:08, 123.65it/s]

 41%|████████████████                       | 694/1683 [00:05<00:08, 123.22it/s]

 42%|████████████████▍                      | 707/1683 [00:05<00:07, 123.10it/s]

 43%|████████████████▋                      | 720/1683 [00:05<00:07, 124.34it/s]

 44%|████████████████▉                      | 733/1683 [00:05<00:07, 124.48it/s]

 44%|█████████████████▎                     | 746/1683 [00:05<00:07, 124.81it/s]

 45%|█████████████████▌                     | 759/1683 [00:06<00:07, 126.25it/s]

 46%|█████████████████▉                     | 772/1683 [00:06<00:07, 126.60it/s]

 47%|██████████████████▏                    | 785/1683 [00:06<00:07, 126.30it/s]

 47%|██████████████████▍                    | 798/1683 [00:06<00:07, 125.28it/s]

 48%|██████████████████▊                    | 811/1683 [00:06<00:06, 124.98it/s]

 49%|███████████████████                    | 824/1683 [00:06<00:06, 125.10it/s]

 50%|███████████████████▍                   | 837/1683 [00:06<00:06, 124.94it/s]

 51%|███████████████████▋                   | 850/1683 [00:06<00:06, 123.72it/s]

 51%|███████████████████▉                   | 863/1683 [00:06<00:06, 122.95it/s]

 52%|████████████████████▎                  | 876/1683 [00:06<00:06, 122.93it/s]

 53%|████████████████████▌                  | 889/1683 [00:07<00:06, 124.02it/s]

 54%|████████████████████▉                  | 902/1683 [00:07<00:06, 124.04it/s]

 54%|█████████████████████▏                 | 915/1683 [00:07<00:06, 124.91it/s]

 55%|█████████████████████▌                 | 929/1683 [00:07<00:05, 126.49it/s]

 56%|█████████████████████▊                 | 943/1683 [00:07<00:05, 128.23it/s]

 57%|██████████████████████▏                | 956/1683 [00:07<00:05, 127.24it/s]

 58%|██████████████████████▍                | 969/1683 [00:07<00:05, 126.82it/s]

 58%|██████████████████████▊                | 982/1683 [00:07<00:05, 126.32it/s]

 59%|███████████████████████                | 995/1683 [00:07<00:05, 125.73it/s]

 60%|██████████████████████▊               | 1009/1683 [00:08<00:05, 127.26it/s]

 61%|███████████████████████               | 1022/1683 [00:08<00:05, 127.23it/s]

 61%|███████████████████████▎              | 1035/1683 [00:08<00:05, 126.71it/s]

 62%|███████████████████████▋              | 1049/1683 [00:08<00:04, 127.85it/s]

 63%|███████████████████████▉              | 1062/1683 [00:08<00:04, 126.61it/s]

 64%|████████████████████████▎             | 1075/1683 [00:08<00:04, 125.98it/s]

 65%|████████████████████████▌             | 1088/1683 [00:08<00:04, 126.11it/s]

 65%|████████████████████████▊             | 1101/1683 [00:08<00:04, 126.08it/s]

 66%|█████████████████████████▏            | 1114/1683 [00:08<00:04, 124.99it/s]

 67%|█████████████████████████▍            | 1127/1683 [00:08<00:04, 122.86it/s]

 68%|█████████████████████████▋            | 1140/1683 [00:09<00:04, 122.84it/s]

 69%|██████████████████████████            | 1153/1683 [00:09<00:04, 124.58it/s]

 69%|██████████████████████████▎           | 1166/1683 [00:09<00:04, 125.36it/s]

 70%|██████████████████████████▌           | 1179/1683 [00:09<00:04, 123.63it/s]

 71%|██████████████████████████▉           | 1192/1683 [00:09<00:03, 124.28it/s]

 72%|███████████████████████████▏          | 1205/1683 [00:09<00:03, 123.65it/s]

 72%|███████████████████████████▌          | 1218/1683 [00:09<00:03, 122.61it/s]

 73%|███████████████████████████▊          | 1231/1683 [00:09<00:03, 122.96it/s]

 74%|████████████████████████████          | 1244/1683 [00:09<00:03, 121.49it/s]

 75%|████████████████████████████▍         | 1257/1683 [00:10<00:03, 123.75it/s]

 75%|████████████████████████████▋         | 1270/1683 [00:10<00:03, 122.89it/s]

 76%|████████████████████████████▉         | 1283/1683 [00:10<00:03, 123.48it/s]

 77%|█████████████████████████████▎        | 1296/1683 [00:10<00:03, 123.93it/s]

 78%|█████████████████████████████▌        | 1309/1683 [00:10<00:03, 124.29it/s]

 79%|█████████████████████████████▊        | 1322/1683 [00:10<00:02, 124.29it/s]

 79%|██████████████████████████████▏       | 1335/1683 [00:10<00:02, 123.83it/s]

 80%|██████████████████████████████▍       | 1348/1683 [00:10<00:02, 123.73it/s]

 81%|██████████████████████████████▋       | 1361/1683 [00:10<00:02, 122.94it/s]

 82%|███████████████████████████████       | 1374/1683 [00:10<00:02, 124.21it/s]

 82%|███████████████████████████████▎      | 1387/1683 [00:11<00:02, 124.44it/s]

 83%|███████████████████████████████▌      | 1400/1683 [00:11<00:02, 125.00it/s]

 84%|███████████████████████████████▉      | 1413/1683 [00:11<00:02, 124.87it/s]

 85%|████████████████████████████████▏     | 1426/1683 [00:11<00:02, 125.34it/s]

 86%|████████████████████████████████▍     | 1439/1683 [00:11<00:01, 124.84it/s]

 86%|████████████████████████████████▊     | 1452/1683 [00:11<00:01, 124.23it/s]

 87%|█████████████████████████████████     | 1465/1683 [00:11<00:01, 123.04it/s]

 88%|█████████████████████████████████▎    | 1478/1683 [00:11<00:01, 123.02it/s]

 89%|█████████████████████████████████▋    | 1491/1683 [00:11<00:01, 124.83it/s]

 89%|█████████████████████████████████▉    | 1504/1683 [00:12<00:01, 124.76it/s]

 90%|██████████████████████████████████▎   | 1517/1683 [00:12<00:01, 125.36it/s]

 91%|██████████████████████████████████▌   | 1530/1683 [00:12<00:01, 125.43it/s]

 92%|██████████████████████████████████▊   | 1543/1683 [00:12<00:01, 126.33it/s]

 92%|███████████████████████████████████▏  | 1556/1683 [00:12<00:01, 126.54it/s]

 93%|███████████████████████████████████▍  | 1569/1683 [00:12<00:00, 126.99it/s]

 94%|███████████████████████████████████▋  | 1582/1683 [00:12<00:00, 127.03it/s]

 95%|████████████████████████████████████  | 1595/1683 [00:12<00:00, 126.37it/s]

 96%|████████████████████████████████████▎ | 1608/1683 [00:12<00:00, 125.49it/s]

 96%|████████████████████████████████████▌ | 1621/1683 [00:12<00:00, 126.27it/s]

 97%|████████████████████████████████████▉ | 1635/1683 [00:13<00:00, 127.86it/s]

 98%|█████████████████████████████████████▏| 1648/1683 [00:13<00:00, 126.87it/s]

 99%|█████████████████████████████████████▌| 1661/1683 [00:13<00:00, 127.50it/s]

 99%|█████████████████████████████████████▊| 1674/1683 [00:13<00:00, 125.00it/s]

100%|██████████████████████████████████████| 1683/1683 [00:13<00:00, 125.41it/s]

  UAS: 0.9244
  LAS: 0.9081
  Total tokens: 33580 | Ignorados: 0
  Salvo em: ./predict_test_ablacao_linear_google-bert_bert-base-multilingual-cased.csv

==================================================
Inferência: neuralmind/bert-base-portuguese-cased
Modelo salvo em: ./best_models_ablacao_linear/neuralmind_bert-base-portuguese-cased | LAS val = 0.9081

Loading weights:   0%|                                  | 0/203 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 203/203 [00:00<00:00, 10852.64it/s]

  0%|                                                  | 0/1683 [00:00<?, ?it/s]

  1%|▎                                       | 13/1683 [00:00<00:12, 128.87it/s]

  2%|▋                                       | 27/1683 [00:00<00:12, 131.28it/s]

  2%|▉                                       | 41/1683 [00:00<00:12, 130.89it/s]

  3%|█▎                                      | 55/1683 [00:00<00:12, 127.17it/s]

  4%|█▌                                      | 68/1683 [00:00<00:12, 128.05it/s]

  5%|█▉                                      | 81/1683 [00:00<00:12, 128.61it/s]

  6%|██▏                                     | 94/1683 [00:00<00:12, 128.97it/s]

  6%|██▍                                    | 107/1683 [00:00<00:12, 126.63it/s]

  7%|██▊                                    | 120/1683 [00:00<00:12, 126.94it/s]

  8%|███                                    | 133/1683 [00:01<00:12, 126.95it/s]

  9%|███▍                                   | 146/1683 [00:01<00:12, 127.78it/s]

  9%|███▋                                   | 159/1683 [00:01<00:11, 128.23it/s]

 10%|███▉                                   | 172/1683 [00:01<00:11, 126.55it/s]

 11%|████▎                                  | 185/1683 [00:01<00:11, 127.36it/s]

 12%|████▌                                  | 198/1683 [00:01<00:11, 127.93it/s]

 13%|████▉                                  | 211/1683 [00:01<00:11, 127.18it/s]

 13%|█████▏                                 | 224/1683 [00:01<00:11, 123.96it/s]

 14%|█████▍                                 | 237/1683 [00:01<00:11, 124.51it/s]

 15%|█████▊                                 | 251/1683 [00:01<00:11, 126.13it/s]

 16%|██████                                 | 264/1683 [00:02<00:11, 127.12it/s]

 16%|██████▍                                | 277/1683 [00:02<00:11, 126.77it/s]

 17%|██████▋                                | 290/1683 [00:02<00:10, 127.18it/s]

 18%|███████                                | 303/1683 [00:02<00:11, 125.08it/s]

 19%|███████▎                               | 316/1683 [00:02<00:10, 125.48it/s]

 20%|███████▌                               | 329/1683 [00:02<00:10, 125.86it/s]

 20%|███████▉                               | 342/1683 [00:02<00:10, 125.99it/s]

 21%|████████▏                              | 355/1683 [00:02<00:10, 126.21it/s]

 22%|████████▌                              | 368/1683 [00:02<00:10, 123.61it/s]

 23%|████████▊                              | 381/1683 [00:03<00:10, 124.71it/s]

 23%|█████████▏                             | 394/1683 [00:03<00:10, 125.98it/s]

 24%|█████████▍                             | 408/1683 [00:03<00:09, 127.79it/s]

 25%|█████████▊                             | 421/1683 [00:03<00:10, 125.69it/s]

 26%|██████████                             | 434/1683 [00:03<00:09, 125.41it/s]

 27%|██████████▎                            | 447/1683 [00:03<00:09, 123.69it/s]

 27%|██████████▋                            | 460/1683 [00:03<00:09, 123.79it/s]

 28%|██████████▉                            | 473/1683 [00:03<00:09, 124.74it/s]

 29%|███████████▎                           | 486/1683 [00:03<00:09, 124.00it/s]

 30%|███████████▌                           | 499/1683 [00:03<00:09, 124.89it/s]

 30%|███████████▊                           | 512/1683 [00:04<00:09, 124.46it/s]

 31%|████████████▏                          | 525/1683 [00:04<00:09, 124.63it/s]

 32%|████████████▍                          | 538/1683 [00:04<00:09, 125.29it/s]

 33%|████████████▊                          | 551/1683 [00:04<00:09, 125.15it/s]

 34%|█████████████                          | 564/1683 [00:04<00:08, 125.31it/s]

 34%|█████████████▎                         | 577/1683 [00:04<00:08, 124.62it/s]

 35%|█████████████▋                         | 590/1683 [00:04<00:08, 123.82it/s]

 36%|█████████████▉                         | 603/1683 [00:04<00:08, 124.70it/s]

 37%|██████████████▎                        | 616/1683 [00:04<00:08, 126.17it/s]

 37%|██████████████▌                        | 629/1683 [00:04<00:08, 127.06it/s]

 38%|██████████████▉                        | 642/1683 [00:05<00:08, 126.35it/s]

 39%|███████████████▏                       | 655/1683 [00:05<00:08, 125.32it/s]

 40%|███████████████▍                       | 668/1683 [00:05<00:08, 125.45it/s]

 40%|███████████████▊                       | 681/1683 [00:05<00:08, 124.57it/s]

 41%|████████████████                       | 694/1683 [00:05<00:07, 124.22it/s]

 42%|████████████████▍                      | 707/1683 [00:05<00:07, 124.12it/s]

 43%|████████████████▋                      | 720/1683 [00:05<00:07, 125.28it/s]

 44%|████████████████▉                      | 733/1683 [00:05<00:07, 125.68it/s]

 44%|█████████████████▎                     | 746/1683 [00:05<00:07, 126.02it/s]

 45%|█████████████████▌                     | 760/1683 [00:06<00:07, 127.48it/s]

 46%|█████████████████▉                     | 773/1683 [00:06<00:07, 127.34it/s]

 47%|██████████████████▏                    | 786/1683 [00:06<00:07, 127.40it/s]

 47%|██████████████████▌                    | 799/1683 [00:06<00:06, 126.67it/s]

 48%|██████████████████▊                    | 812/1683 [00:06<00:06, 126.26it/s]

 49%|███████████████████                    | 825/1683 [00:06<00:06, 125.53it/s]

 50%|███████████████████▍                   | 838/1683 [00:06<00:06, 126.23it/s]

 51%|███████████████████▋                   | 851/1683 [00:06<00:06, 124.60it/s]

 51%|████████████████████                   | 864/1683 [00:06<00:06, 124.39it/s]

 52%|████████████████████▎                  | 877/1683 [00:06<00:06, 124.36it/s]

 53%|████████████████████▌                  | 890/1683 [00:07<00:06, 125.21it/s]

 54%|████████████████████▉                  | 903/1683 [00:07<00:06, 124.50it/s]

 54%|█████████████████████▏                 | 916/1683 [00:07<00:06, 125.14it/s]

 55%|█████████████████████▌                 | 929/1683 [00:07<00:05, 125.82it/s]

 56%|█████████████████████▊                 | 943/1683 [00:07<00:05, 127.16it/s]

 57%|██████████████████████▏                | 956/1683 [00:07<00:05, 125.90it/s]

 58%|██████████████████████▍                | 969/1683 [00:07<00:05, 125.54it/s]

 58%|██████████████████████▊                | 982/1683 [00:07<00:05, 124.94it/s]

 59%|███████████████████████                | 995/1683 [00:07<00:05, 124.48it/s]

 60%|██████████████████████▊               | 1009/1683 [00:08<00:05, 126.10it/s]

 61%|███████████████████████               | 1022/1683 [00:08<00:05, 125.72it/s]

 61%|███████████████████████▎              | 1035/1683 [00:08<00:05, 125.19it/s]

 62%|███████████████████████▋              | 1048/1683 [00:08<00:05, 126.24it/s]

 63%|███████████████████████▉              | 1061/1683 [00:08<00:04, 125.55it/s]

 64%|████████████████████████▏             | 1074/1683 [00:08<00:04, 124.59it/s]

 65%|████████████████████████▌             | 1087/1683 [00:08<00:04, 124.44it/s]

 65%|████████████████████████▊             | 1100/1683 [00:08<00:04, 125.13it/s]

 66%|█████████████████████████▏            | 1113/1683 [00:08<00:04, 125.13it/s]

 67%|█████████████████████████▍            | 1126/1683 [00:08<00:04, 123.24it/s]

 68%|█████████████████████████▋            | 1139/1683 [00:09<00:04, 123.50it/s]

 68%|██████████████████████████            | 1152/1683 [00:09<00:04, 125.25it/s]

 69%|██████████████████████████▎           | 1165/1683 [00:09<00:04, 126.10it/s]

 70%|██████████████████████████▌           | 1178/1683 [00:09<00:04, 124.94it/s]

 71%|██████████████████████████▉           | 1191/1683 [00:09<00:03, 125.49it/s]

 72%|███████████████████████████▏          | 1204/1683 [00:09<00:03, 125.02it/s]

 72%|███████████████████████████▍          | 1217/1683 [00:09<00:03, 123.65it/s]

 73%|███████████████████████████▊          | 1230/1683 [00:09<00:03, 124.23it/s]

 74%|████████████████████████████          | 1243/1683 [00:09<00:03, 123.01it/s]

 75%|████████████████████████████▎         | 1256/1683 [00:09<00:03, 124.40it/s]

 75%|████████████████████████████▋         | 1269/1683 [00:10<00:03, 123.79it/s]

 76%|████████████████████████████▉         | 1282/1683 [00:10<00:03, 124.90it/s]

 77%|█████████████████████████████▏        | 1295/1683 [00:10<00:03, 125.11it/s]

 78%|█████████████████████████████▌        | 1308/1683 [00:10<00:02, 125.47it/s]

 78%|█████████████████████████████▊        | 1321/1683 [00:10<00:02, 125.33it/s]

 79%|██████████████████████████████        | 1334/1683 [00:10<00:02, 124.85it/s]

 80%|██████████████████████████████▍       | 1347/1683 [00:10<00:02, 124.70it/s]

 81%|██████████████████████████████▋       | 1360/1683 [00:10<00:02, 124.38it/s]

 82%|███████████████████████████████       | 1373/1683 [00:10<00:02, 125.11it/s]

 82%|███████████████████████████████▎      | 1386/1683 [00:11<00:02, 125.67it/s]

 83%|███████████████████████████████▌      | 1399/1683 [00:11<00:02, 126.19it/s]

 84%|███████████████████████████████▉      | 1412/1683 [00:11<00:02, 126.43it/s]

 85%|████████████████████████████████▏     | 1425/1683 [00:11<00:02, 126.88it/s]

 85%|████████████████████████████████▍     | 1438/1683 [00:11<00:01, 126.09it/s]

 86%|████████████████████████████████▊     | 1451/1683 [00:11<00:01, 125.37it/s]

 87%|█████████████████████████████████     | 1464/1683 [00:11<00:01, 124.86it/s]

 88%|█████████████████████████████████▎    | 1477/1683 [00:11<00:01, 124.19it/s]

 89%|█████████████████████████████████▋    | 1491/1683 [00:11<00:01, 126.26it/s]

 89%|█████████████████████████████████▉    | 1504/1683 [00:11<00:01, 126.20it/s]

 90%|██████████████████████████████████▎   | 1517/1683 [00:12<00:01, 126.85it/s]

 91%|██████████████████████████████████▌   | 1530/1683 [00:12<00:01, 126.56it/s]

 92%|██████████████████████████████████▊   | 1543/1683 [00:12<00:01, 126.69it/s]

 92%|███████████████████████████████████▏  | 1556/1683 [00:12<00:01, 126.32it/s]

 93%|███████████████████████████████████▍  | 1569/1683 [00:12<00:00, 126.33it/s]

 94%|███████████████████████████████████▋  | 1582/1683 [00:12<00:00, 126.15it/s]

 95%|████████████████████████████████████  | 1595/1683 [00:12<00:00, 125.28it/s]

 96%|████████████████████████████████████▎ | 1608/1683 [00:12<00:00, 124.05it/s]

 96%|████████████████████████████████████▌ | 1621/1683 [00:12<00:00, 124.61it/s]

 97%|████████████████████████████████████▉ | 1634/1683 [00:13<00:00, 126.14it/s]

 98%|█████████████████████████████████████▏| 1647/1683 [00:13<00:00, 125.71it/s]

 99%|█████████████████████████████████████▍| 1660/1683 [00:13<00:00, 125.42it/s]

 99%|█████████████████████████████████████▊| 1673/1683 [00:13<00:00, 123.57it/s]

100%|██████████████████████████████████████| 1683/1683 [00:13<00:00, 125.57it/s]

  UAS: 0.9320
  LAS: 0.9191
  Total tokens: 33580 | Ignorados: 0
  Salvo em: ./predict_test_ablacao_linear_neuralmind_bert-base-portuguese-cased.csv

==================================================
Inferência: neuralmind/bert-large-portuguese-cased
Modelo salvo em: ./best_models_ablacao_linear/neuralmind_bert-large-portuguese-cased | LAS val = 0.9354

Loading weights:   0%|                                  | 0/395 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 395/395 [00:00<00:00, 7066.75it/s]

  0%|                                                  | 0/1683 [00:00<?, ?it/s]

  0%|▏                                         | 7/1683 [00:00<00:24, 68.66it/s]

  1%|▎                                        | 14/1683 [00:00<00:24, 67.59it/s]

  1%|▌                                        | 21/1683 [00:00<00:24, 68.52it/s]

  2%|▋                                        | 29/1683 [00:00<00:23, 69.19it/s]

  2%|▉                                        | 36/1683 [00:00<00:23, 69.13it/s]

  3%|█                                        | 43/1683 [00:00<00:23, 68.83it/s]

  3%|█▏                                       | 50/1683 [00:00<00:23, 68.21it/s]

  3%|█▍                                       | 57/1683 [00:00<00:24, 66.93it/s]

  4%|█▌                                       | 64/1683 [00:00<00:24, 67.43it/s]

  4%|█▋                                       | 71/1683 [00:01<00:23, 68.17it/s]

  5%|█▉                                       | 78/1683 [00:01<00:23, 67.94it/s]

  5%|██                                       | 86/1683 [00:01<00:23, 68.52it/s]

  6%|██▎                                      | 93/1683 [00:01<00:23, 68.16it/s]

  6%|██▍                                     | 100/1683 [00:01<00:23, 67.40it/s]

  6%|██▌                                     | 107/1683 [00:01<00:23, 67.14it/s]

  7%|██▋                                     | 114/1683 [00:01<00:23, 67.47it/s]

  7%|██▉                                     | 121/1683 [00:01<00:23, 67.08it/s]

  8%|███                                     | 128/1683 [00:01<00:23, 66.76it/s]

  8%|███▏                                    | 135/1683 [00:01<00:23, 66.59it/s]

  8%|███▎                                    | 142/1683 [00:02<00:22, 67.18it/s]

  9%|███▌                                    | 149/1683 [00:02<00:22, 66.88it/s]

  9%|███▋                                    | 156/1683 [00:02<00:22, 67.22it/s]

 10%|███▊                                    | 163/1683 [00:02<00:22, 67.48it/s]

 10%|████                                    | 170/1683 [00:02<00:22, 66.33it/s]

 11%|████▏                                   | 177/1683 [00:02<00:22, 66.25it/s]

 11%|████▎                                   | 184/1683 [00:02<00:22, 66.33it/s]

 11%|████▌                                   | 191/1683 [00:02<00:22, 66.66it/s]

 12%|████▋                                   | 198/1683 [00:02<00:22, 66.61it/s]

 12%|████▊                                   | 205/1683 [00:03<00:22, 66.75it/s]

 13%|█████                                   | 212/1683 [00:03<00:21, 66.91it/s]

 13%|█████▏                                  | 219/1683 [00:03<00:22, 66.30it/s]

 13%|█████▎                                  | 226/1683 [00:03<00:22, 65.84it/s]

 14%|█████▌                                  | 233/1683 [00:03<00:21, 66.26it/s]

 14%|█████▋                                  | 240/1683 [00:03<00:21, 66.82it/s]

 15%|█████▊                                  | 247/1683 [00:03<00:21, 67.10it/s]

 15%|██████                                  | 254/1683 [00:03<00:21, 67.64it/s]

 16%|██████▏                                 | 261/1683 [00:03<00:20, 68.00it/s]

 16%|██████▎                                 | 268/1683 [00:03<00:21, 67.19it/s]

 16%|██████▌                                 | 275/1683 [00:04<00:20, 67.21it/s]

 17%|██████▋                                 | 282/1683 [00:04<00:20, 67.12it/s]

 17%|██████▉                                 | 290/1683 [00:04<00:20, 68.01it/s]

 18%|███████                                 | 297/1683 [00:04<00:20, 67.53it/s]

 18%|███████▏                                | 304/1683 [00:04<00:20, 66.63it/s]

 18%|███████▍                                | 311/1683 [00:04<00:20, 66.67it/s]

 19%|███████▌                                | 318/1683 [00:04<00:20, 66.96it/s]

 19%|███████▋                                | 325/1683 [00:04<00:20, 67.21it/s]

 20%|███████▉                                | 332/1683 [00:04<00:20, 66.80it/s]

 20%|████████                                | 339/1683 [00:05<00:20, 67.17it/s]

 21%|████████▏                               | 346/1683 [00:05<00:19, 67.39it/s]

 21%|████████▍                               | 353/1683 [00:05<00:19, 67.17it/s]

 21%|████████▌                               | 360/1683 [00:05<00:19, 67.03it/s]

 22%|████████▋                               | 367/1683 [00:05<00:19, 66.34it/s]

 22%|████████▉                               | 374/1683 [00:05<00:19, 66.66it/s]

 23%|█████████                               | 381/1683 [00:05<00:19, 66.84it/s]

 23%|█████████▏                              | 388/1683 [00:05<00:19, 66.79it/s]

 24%|█████████▍                              | 396/1683 [00:05<00:18, 68.22it/s]

 24%|█████████▌                              | 403/1683 [00:05<00:18, 68.36it/s]

 24%|█████████▋                              | 410/1683 [00:06<00:18, 68.39it/s]

 25%|█████████▉                              | 417/1683 [00:06<00:18, 67.92it/s]

 25%|██████████                              | 424/1683 [00:06<00:18, 66.66it/s]

 26%|██████████▏                             | 431/1683 [00:06<00:18, 66.88it/s]

 26%|██████████▍                             | 438/1683 [00:06<00:18, 67.10it/s]

 26%|██████████▌                             | 445/1683 [00:06<00:18, 66.15it/s]

 27%|██████████▋                             | 452/1683 [00:06<00:18, 66.31it/s]

 27%|██████████▉                             | 459/1683 [00:06<00:18, 66.22it/s]

 28%|███████████                             | 466/1683 [00:06<00:18, 66.82it/s]

 28%|███████████▏                            | 473/1683 [00:07<00:18, 66.75it/s]

 29%|███████████▍                            | 480/1683 [00:07<00:18, 66.17it/s]

 29%|███████████▌                            | 487/1683 [00:07<00:18, 66.32it/s]

 29%|███████████▋                            | 494/1683 [00:07<00:17, 66.51it/s]

 30%|███████████▉                            | 501/1683 [00:07<00:17, 67.18it/s]

 30%|████████████                            | 508/1683 [00:07<00:17, 66.64it/s]

 31%|████████████▏                           | 515/1683 [00:07<00:17, 67.09it/s]

 31%|████████████▍                           | 522/1683 [00:07<00:17, 66.89it/s]

 31%|████████████▌                           | 529/1683 [00:07<00:17, 66.56it/s]

 32%|████████████▋                           | 536/1683 [00:07<00:17, 67.37it/s]

 32%|████████████▉                           | 543/1683 [00:08<00:17, 66.59it/s]

 33%|█████████████                           | 550/1683 [00:08<00:16, 67.57it/s]

 33%|█████████████▏                          | 557/1683 [00:08<00:16, 67.44it/s]

 34%|█████████████▍                          | 564/1683 [00:08<00:16, 67.33it/s]

 34%|█████████████▌                          | 571/1683 [00:08<00:16, 67.30it/s]

 34%|█████████████▋                          | 578/1683 [00:08<00:16, 66.43it/s]

 35%|█████████████▉                          | 585/1683 [00:08<00:16, 66.48it/s]

 35%|██████████████                          | 592/1683 [00:08<00:16, 66.20it/s]

 36%|██████████████▏                         | 599/1683 [00:08<00:16, 66.56it/s]

 36%|██████████████▍                         | 606/1683 [00:09<00:16, 66.66it/s]

 36%|██████████████▌                         | 613/1683 [00:09<00:15, 67.16it/s]

 37%|██████████████▋                         | 620/1683 [00:09<00:15, 67.52it/s]

 37%|██████████████▉                         | 627/1683 [00:09<00:15, 67.53it/s]

 38%|███████████████                         | 634/1683 [00:09<00:15, 67.94it/s]

 38%|███████████████▏                        | 641/1683 [00:09<00:15, 67.21it/s]

 39%|███████████████▍                        | 648/1683 [00:09<00:15, 67.50it/s]

 39%|███████████████▌                        | 655/1683 [00:09<00:15, 66.64it/s]

 39%|███████████████▋                        | 662/1683 [00:09<00:15, 66.70it/s]

 40%|███████████████▉                        | 669/1683 [00:09<00:15, 66.73it/s]

 40%|████████████████                        | 676/1683 [00:10<00:15, 66.42it/s]

 41%|████████████████▏                       | 683/1683 [00:10<00:15, 66.19it/s]

 41%|████████████████▍                       | 690/1683 [00:10<00:14, 66.57it/s]

 41%|████████████████▌                       | 697/1683 [00:10<00:14, 66.35it/s]

 42%|████████████████▋                       | 704/1683 [00:10<00:14, 66.22it/s]

 42%|████████████████▉                       | 711/1683 [00:10<00:14, 66.40it/s]

 43%|█████████████████                       | 718/1683 [00:10<00:14, 66.86it/s]

 43%|█████████████████▏                      | 725/1683 [00:10<00:14, 66.80it/s]

 43%|█████████████████▍                      | 732/1683 [00:10<00:14, 66.92it/s]

 44%|█████████████████▌                      | 739/1683 [00:11<00:14, 66.95it/s]

 44%|█████████████████▋                      | 746/1683 [00:11<00:13, 67.15it/s]

 45%|█████████████████▉                      | 753/1683 [00:11<00:13, 67.49it/s]

 45%|██████████████████                      | 760/1683 [00:11<00:13, 67.65it/s]

 46%|██████████████████▏                     | 767/1683 [00:11<00:13, 67.26it/s]

 46%|██████████████████▍                     | 774/1683 [00:11<00:13, 67.90it/s]

 46%|██████████████████▌                     | 781/1683 [00:11<00:13, 68.01it/s]

 47%|██████████████████▋                     | 788/1683 [00:11<00:13, 67.42it/s]

 47%|██████████████████▉                     | 795/1683 [00:11<00:13, 67.26it/s]

 48%|███████████████████                     | 802/1683 [00:11<00:13, 67.25it/s]

 48%|███████████████████▏                    | 809/1683 [00:12<00:13, 67.22it/s]

 48%|███████████████████▍                    | 816/1683 [00:12<00:12, 67.42it/s]

 49%|███████████████████▌                    | 823/1683 [00:12<00:12, 66.92it/s]

 49%|███████████████████▋                    | 830/1683 [00:12<00:12, 67.63it/s]

 50%|███████████████████▉                    | 837/1683 [00:12<00:12, 67.10it/s]

 50%|████████████████████                    | 844/1683 [00:12<00:12, 66.88it/s]

 51%|████████████████████▏                   | 851/1683 [00:12<00:12, 66.52it/s]

 51%|████████████████████▍                   | 858/1683 [00:12<00:12, 66.36it/s]

 51%|████████████████████▌                   | 865/1683 [00:12<00:12, 66.12it/s]

 52%|████████████████████▋                   | 872/1683 [00:13<00:12, 66.39it/s]

 52%|████████████████████▉                   | 879/1683 [00:13<00:11, 67.24it/s]

 53%|█████████████████████                   | 886/1683 [00:13<00:11, 67.02it/s]

 53%|█████████████████████▏                  | 893/1683 [00:13<00:11, 66.99it/s]

 53%|█████████████████████▍                  | 900/1683 [00:13<00:11, 67.20it/s]

 54%|█████████████████████▌                  | 907/1683 [00:13<00:11, 66.87it/s]

 54%|█████████████████████▋                  | 915/1683 [00:13<00:11, 67.70it/s]

 55%|█████████████████████▉                  | 922/1683 [00:13<00:11, 68.10it/s]

 55%|██████████████████████                  | 929/1683 [00:13<00:11, 67.84it/s]

 56%|██████████████████████▏                 | 936/1683 [00:13<00:10, 68.16it/s]

 56%|██████████████████████▍                 | 943/1683 [00:14<00:10, 68.22it/s]

 56%|██████████████████████▌                 | 950/1683 [00:14<00:10, 67.13it/s]

 57%|██████████████████████▋                 | 957/1683 [00:14<00:10, 67.52it/s]

 57%|██████████████████████▉                 | 964/1683 [00:14<00:10, 67.15it/s]

 58%|███████████████████████                 | 971/1683 [00:14<00:10, 67.12it/s]

 58%|███████████████████████▏                | 978/1683 [00:14<00:10, 66.98it/s]

 59%|███████████████████████▍                | 985/1683 [00:14<00:10, 66.17it/s]

 59%|███████████████████████▌                | 992/1683 [00:14<00:10, 66.27it/s]

 59%|███████████████████████▋                | 999/1683 [00:14<00:10, 66.90it/s]

 60%|███████████████████████▎               | 1006/1683 [00:14<00:09, 67.76it/s]

 60%|███████████████████████▍               | 1013/1683 [00:15<00:09, 67.69it/s]

 61%|███████████████████████▋               | 1020/1683 [00:15<00:09, 68.17it/s]

 61%|███████████████████████▊               | 1027/1683 [00:15<00:09, 67.88it/s]

 61%|███████████████████████▉               | 1034/1683 [00:15<00:09, 68.12it/s]

 62%|████████████████████████               | 1041/1683 [00:15<00:09, 68.10it/s]

 62%|████████████████████████▎              | 1048/1683 [00:15<00:09, 68.21it/s]

 63%|████████████████████████▍              | 1055/1683 [00:15<00:09, 68.47it/s]

 63%|████████████████████████▌              | 1062/1683 [00:15<00:09, 67.58it/s]

 64%|████████████████████████▊              | 1069/1683 [00:15<00:09, 67.67it/s]

 64%|████████████████████████▉              | 1076/1683 [00:16<00:08, 67.92it/s]

 64%|█████████████████████████              | 1083/1683 [00:16<00:08, 67.69it/s]

 65%|█████████████████████████▎             | 1090/1683 [00:16<00:08, 68.01it/s]

 65%|█████████████████████████▍             | 1097/1683 [00:16<00:08, 67.78it/s]

 66%|█████████████████████████▌             | 1104/1683 [00:16<00:08, 67.21it/s]

 66%|█████████████████████████▋             | 1111/1683 [00:16<00:08, 67.03it/s]

 66%|█████████████████████████▉             | 1118/1683 [00:16<00:08, 66.55it/s]

 67%|██████████████████████████             | 1125/1683 [00:16<00:08, 66.24it/s]

 67%|██████████████████████████▏            | 1132/1683 [00:16<00:08, 66.05it/s]

 68%|██████████████████████████▍            | 1139/1683 [00:16<00:08, 66.54it/s]

 68%|██████████████████████████▌            | 1146/1683 [00:17<00:07, 67.14it/s]

 69%|██████████████████████████▋            | 1153/1683 [00:17<00:07, 67.41it/s]

 69%|██████████████████████████▉            | 1160/1683 [00:17<00:07, 67.74it/s]

 69%|███████████████████████████            | 1167/1683 [00:17<00:07, 67.27it/s]

 70%|███████████████████████████▏           | 1174/1683 [00:17<00:07, 67.28it/s]

 70%|███████████████████████████▎           | 1181/1683 [00:17<00:07, 66.94it/s]

 71%|███████████████████████████▌           | 1188/1683 [00:17<00:07, 66.66it/s]

 71%|███████████████████████████▋           | 1195/1683 [00:17<00:07, 66.45it/s]

 71%|███████████████████████████▊           | 1202/1683 [00:17<00:07, 66.95it/s]

 72%|████████████████████████████           | 1209/1683 [00:18<00:07, 66.24it/s]

 72%|████████████████████████████▏          | 1216/1683 [00:18<00:07, 65.86it/s]

 73%|████████████████████████████▎          | 1223/1683 [00:18<00:06, 66.38it/s]

 73%|████████████████████████████▌          | 1230/1683 [00:18<00:06, 66.58it/s]

 73%|████████████████████████████▋          | 1237/1683 [00:18<00:06, 65.75it/s]

 74%|████████████████████████████▊          | 1244/1683 [00:18<00:06, 66.15it/s]

 74%|████████████████████████████▉          | 1251/1683 [00:18<00:06, 66.67it/s]

 75%|█████████████████████████████▏         | 1258/1683 [00:18<00:06, 67.52it/s]

 75%|█████████████████████████████▎         | 1265/1683 [00:18<00:06, 67.08it/s]

 76%|█████████████████████████████▍         | 1272/1683 [00:18<00:06, 66.61it/s]

 76%|█████████████████████████████▋         | 1279/1683 [00:19<00:05, 67.44it/s]

 76%|█████████████████████████████▊         | 1286/1683 [00:19<00:05, 67.13it/s]

 77%|█████████████████████████████▉         | 1293/1683 [00:19<00:05, 67.56it/s]

 77%|██████████████████████████████         | 1300/1683 [00:19<00:05, 67.00it/s]

 78%|██████████████████████████████▎        | 1307/1683 [00:19<00:05, 67.29it/s]

 78%|██████████████████████████████▍        | 1314/1683 [00:19<00:05, 67.74it/s]

 78%|██████████████████████████████▌        | 1321/1683 [00:19<00:05, 67.08it/s]

 79%|██████████████████████████████▊        | 1328/1683 [00:19<00:05, 67.31it/s]

 79%|██████████████████████████████▉        | 1335/1683 [00:19<00:05, 66.50it/s]

 80%|███████████████████████████████        | 1342/1683 [00:19<00:05, 66.27it/s]

 80%|███████████████████████████████▎       | 1349/1683 [00:20<00:05, 66.47it/s]

 81%|███████████████████████████████▍       | 1356/1683 [00:20<00:04, 66.51it/s]

 81%|███████████████████████████████▌       | 1363/1683 [00:20<00:04, 67.09it/s]

 81%|███████████████████████████████▋       | 1370/1683 [00:20<00:04, 66.92it/s]

 82%|███████████████████████████████▉       | 1377/1683 [00:20<00:04, 67.05it/s]

 82%|████████████████████████████████       | 1384/1683 [00:20<00:04, 66.81it/s]

 83%|████████████████████████████████▏      | 1391/1683 [00:20<00:04, 66.48it/s]

 83%|████████████████████████████████▍      | 1398/1683 [00:20<00:04, 66.62it/s]

 83%|████████████████████████████████▌      | 1405/1683 [00:20<00:04, 66.42it/s]

 84%|████████████████████████████████▋      | 1412/1683 [00:21<00:04, 66.85it/s]

 84%|████████████████████████████████▉      | 1419/1683 [00:21<00:03, 66.97it/s]

 85%|█████████████████████████████████      | 1426/1683 [00:21<00:03, 67.12it/s]

 85%|█████████████████████████████████▏     | 1433/1683 [00:21<00:03, 66.93it/s]

 86%|█████████████████████████████████▎     | 1440/1683 [00:21<00:03, 66.86it/s]

 86%|█████████████████████████████████▌     | 1447/1683 [00:21<00:03, 66.41it/s]

 86%|█████████████████████████████████▋     | 1454/1683 [00:21<00:03, 66.63it/s]

 87%|█████████████████████████████████▊     | 1461/1683 [00:21<00:03, 66.50it/s]

 87%|██████████████████████████████████     | 1468/1683 [00:21<00:03, 66.70it/s]

 88%|██████████████████████████████████▏    | 1475/1683 [00:21<00:03, 66.37it/s]

 88%|██████████████████████████████████▎    | 1482/1683 [00:22<00:02, 67.04it/s]

 88%|██████████████████████████████████▌    | 1489/1683 [00:22<00:02, 67.32it/s]

 89%|██████████████████████████████████▋    | 1496/1683 [00:22<00:02, 67.46it/s]

 89%|██████████████████████████████████▊    | 1503/1683 [00:22<00:02, 67.30it/s]

 90%|███████████████████████████████████    | 1511/1683 [00:22<00:02, 68.27it/s]

 90%|███████████████████████████████████▏   | 1518/1683 [00:22<00:02, 67.54it/s]

 91%|███████████████████████████████████▎   | 1525/1683 [00:22<00:02, 67.44it/s]

 91%|███████████████████████████████████▌   | 1532/1683 [00:22<00:02, 67.67it/s]

 91%|███████████████████████████████████▋   | 1539/1683 [00:22<00:02, 67.44it/s]

 92%|███████████████████████████████████▊   | 1546/1683 [00:23<00:02, 67.28it/s]

 92%|███████████████████████████████████▉   | 1553/1683 [00:23<00:01, 67.25it/s]

 93%|████████████████████████████████████▏  | 1560/1683 [00:23<00:01, 67.18it/s]

 93%|████████████████████████████████████▎  | 1567/1683 [00:23<00:01, 67.40it/s]

 94%|████████████████████████████████████▍  | 1574/1683 [00:23<00:01, 66.90it/s]

 94%|████████████████████████████████████▋  | 1581/1683 [00:23<00:01, 66.74it/s]

 94%|████████████████████████████████████▊  | 1588/1683 [00:23<00:01, 66.26it/s]

 95%|████████████████████████████████████▉  | 1595/1683 [00:23<00:01, 66.36it/s]

 95%|█████████████████████████████████████  | 1602/1683 [00:23<00:01, 65.95it/s]

 96%|█████████████████████████████████████▎ | 1609/1683 [00:23<00:01, 66.05it/s]

 96%|█████████████████████████████████████▍ | 1616/1683 [00:24<00:01, 66.79it/s]

 96%|█████████████████████████████████████▌ | 1623/1683 [00:24<00:00, 66.39it/s]

 97%|█████████████████████████████████████▊ | 1630/1683 [00:24<00:00, 67.02it/s]

 97%|█████████████████████████████████████▉ | 1637/1683 [00:24<00:00, 67.41it/s]

 98%|██████████████████████████████████████ | 1644/1683 [00:24<00:00, 67.35it/s]

 98%|██████████████████████████████████████▎| 1651/1683 [00:24<00:00, 66.44it/s]

 99%|██████████████████████████████████████▍| 1658/1683 [00:24<00:00, 66.94it/s]

 99%|██████████████████████████████████████▌| 1665/1683 [00:24<00:00, 66.87it/s]

 99%|██████████████████████████████████████▋| 1672/1683 [00:24<00:00, 66.15it/s]

100%|██████████████████████████████████████▉| 1679/1683 [00:25<00:00, 66.18it/s]

100%|███████████████████████████████████████| 1683/1683 [00:25<00:00, 67.06it/s]

  UAS: 0.9473
  LAS: 0.9352
  Total tokens: 33580 | Ignorados: 0
  Salvo em: ./predict_test_ablacao_linear_neuralmind_bert-large-portuguese-cased.csv

==================================================
Inferência: amadeusai/modernJabuticaBERT-Base-1k
Modelo salvo em: ./best_models_ablacao_linear/amadeusai_modernJabuticaBERT-Base-1k | LAS val = 0.8469

Loading weights:   0%|                                  | 0/138 [00:00<?, ?it/s]

Loading weights: 100%|█████████████████████| 138/138 [00:00<00:00, 10171.23it/s]

  0%|                                                  | 0/1683 [00:00<?, ?it/s]

  0%|▏                                         | 8/1683 [00:00<00:23, 72.65it/s]

  1%|▍                                        | 16/1683 [00:00<00:23, 72.19it/s]

  1%|▌                                        | 24/1683 [00:00<00:22, 72.82it/s]

  2%|▊                                        | 32/1683 [00:00<00:22, 72.42it/s]

  2%|▉                                        | 40/1683 [00:00<00:22, 72.88it/s]

  3%|█▏                                       | 48/1683 [00:00<00:22, 72.13it/s]

  3%|█▎                                       | 56/1683 [00:00<00:22, 71.07it/s]

  4%|█▌                                       | 64/1683 [00:00<00:22, 71.42it/s]

  4%|█▊                                       | 72/1683 [00:00<00:22, 72.30it/s]

  5%|█▉                                       | 80/1683 [00:01<00:22, 71.79it/s]

  5%|██▏                                      | 88/1683 [00:01<00:22, 72.13it/s]

  6%|██▎                                      | 96/1683 [00:01<00:21, 72.35it/s]

  6%|██▍                                     | 104/1683 [00:01<00:21, 72.04it/s]

  7%|██▋                                     | 112/1683 [00:01<00:22, 71.03it/s]

  7%|██▊                                     | 120/1683 [00:01<00:22, 70.70it/s]

  8%|███                                     | 128/1683 [00:01<00:22, 70.36it/s]

  8%|███▏                                    | 136/1683 [00:01<00:22, 70.22it/s]

  9%|███▍                                    | 144/1683 [00:02<00:21, 70.56it/s]

  9%|███▌                                    | 152/1683 [00:02<00:21, 70.60it/s]

 10%|███▊                                    | 160/1683 [00:02<00:21, 70.53it/s]

 10%|███▉                                    | 168/1683 [00:02<00:21, 70.47it/s]

 10%|████▏                                   | 176/1683 [00:02<00:21, 69.01it/s]

 11%|████▎                                   | 184/1683 [00:02<00:21, 69.38it/s]

 11%|████▌                                   | 192/1683 [00:02<00:21, 70.26it/s]

 12%|████▊                                   | 200/1683 [00:02<00:21, 70.58it/s]

 12%|████▉                                   | 208/1683 [00:02<00:20, 70.43it/s]

 13%|█████▏                                  | 216/1683 [00:03<00:20, 69.95it/s]

 13%|█████▎                                  | 223/1683 [00:03<00:21, 69.14it/s]

 14%|█████▍                                  | 231/1683 [00:03<00:20, 69.33it/s]

 14%|█████▋                                  | 239/1683 [00:03<00:20, 70.20it/s]

 15%|█████▊                                  | 247/1683 [00:03<00:20, 70.96it/s]

 15%|██████                                  | 255/1683 [00:03<00:19, 72.03it/s]

 16%|██████▎                                 | 263/1683 [00:03<00:19, 72.35it/s]

 16%|██████▍                                 | 271/1683 [00:03<00:19, 72.52it/s]

 17%|██████▋                                 | 279/1683 [00:03<00:19, 72.35it/s]

 17%|██████▊                                 | 287/1683 [00:04<00:19, 72.80it/s]

 18%|███████                                 | 295/1683 [00:04<00:19, 72.90it/s]

 18%|███████▏                                | 303/1683 [00:04<00:19, 71.80it/s]

 18%|███████▍                                | 311/1683 [00:04<00:19, 71.99it/s]

 19%|███████▌                                | 319/1683 [00:04<00:18, 72.36it/s]

 19%|███████▊                                | 327/1683 [00:04<00:18, 72.74it/s]

 20%|███████▉                                | 335/1683 [00:04<00:18, 72.04it/s]

 20%|████████▏                               | 343/1683 [00:04<00:18, 72.45it/s]

 21%|████████▎                               | 351/1683 [00:04<00:18, 72.25it/s]

 21%|████████▌                               | 359/1683 [00:05<00:18, 71.68it/s]

 22%|████████▋                               | 367/1683 [00:05<00:18, 70.19it/s]

 22%|████████▉                               | 375/1683 [00:05<00:18, 70.60it/s]

 23%|█████████                               | 383/1683 [00:05<00:18, 70.56it/s]

 23%|█████████▎                              | 391/1683 [00:05<00:18, 71.21it/s]

 24%|█████████▍                              | 399/1683 [00:05<00:17, 71.94it/s]

 24%|█████████▋                              | 407/1683 [00:05<00:17, 71.83it/s]

 25%|█████████▊                              | 415/1683 [00:05<00:17, 71.28it/s]

 25%|██████████                              | 423/1683 [00:05<00:17, 70.31it/s]

 26%|██████████▏                             | 431/1683 [00:06<00:17, 70.57it/s]

 26%|██████████▍                             | 439/1683 [00:06<00:17, 70.29it/s]

 27%|██████████▌                             | 447/1683 [00:06<00:17, 69.67it/s]

 27%|██████████▊                             | 454/1683 [00:06<00:17, 69.75it/s]

 27%|██████████▉                             | 462/1683 [00:06<00:17, 70.05it/s]

 28%|███████████▏                            | 470/1683 [00:06<00:17, 70.26it/s]

 28%|███████████▎                            | 478/1683 [00:06<00:17, 70.33it/s]

 29%|███████████▌                            | 486/1683 [00:06<00:17, 70.05it/s]

 29%|███████████▋                            | 494/1683 [00:06<00:17, 69.82it/s]

 30%|███████████▉                            | 502/1683 [00:07<00:16, 70.41it/s]

 30%|████████████                            | 510/1683 [00:07<00:16, 70.17it/s]

 31%|████████████▎                           | 518/1683 [00:07<00:16, 70.09it/s]

 31%|████████████▌                           | 526/1683 [00:07<00:16, 70.22it/s]

 32%|████████████▋                           | 534/1683 [00:07<00:16, 70.27it/s]

 32%|████████████▉                           | 542/1683 [00:07<00:16, 69.78it/s]

 33%|█████████████                           | 550/1683 [00:07<00:16, 70.66it/s]

 33%|█████████████▎                          | 558/1683 [00:07<00:15, 70.73it/s]

 34%|█████████████▍                          | 566/1683 [00:07<00:15, 70.38it/s]

 34%|█████████████▋                          | 574/1683 [00:08<00:15, 70.46it/s]

 35%|█████████████▊                          | 582/1683 [00:08<00:15, 69.63it/s]

 35%|██████████████                          | 590/1683 [00:08<00:15, 70.03it/s]

 36%|██████████████▏                         | 598/1683 [00:08<00:15, 70.29it/s]

 36%|██████████████▍                         | 606/1683 [00:08<00:15, 70.53it/s]

 36%|██████████████▌                         | 614/1683 [00:08<00:15, 71.00it/s]

 37%|██████████████▊                         | 622/1683 [00:08<00:14, 71.12it/s]

 37%|██████████████▉                         | 630/1683 [00:08<00:14, 71.34it/s]

 38%|███████████████▏                        | 638/1683 [00:08<00:14, 71.08it/s]

 38%|███████████████▎                        | 646/1683 [00:09<00:14, 71.00it/s]

 39%|███████████████▌                        | 654/1683 [00:09<00:14, 70.08it/s]

 39%|███████████████▋                        | 662/1683 [00:09<00:14, 70.15it/s]

 40%|███████████████▉                        | 670/1683 [00:09<00:14, 69.87it/s]

 40%|████████████████                        | 677/1683 [00:09<00:14, 69.80it/s]

 41%|████████████████▎                       | 685/1683 [00:09<00:14, 69.87it/s]

 41%|████████████████▍                       | 693/1683 [00:09<00:14, 70.01it/s]

 42%|████████████████▋                       | 701/1683 [00:09<00:14, 69.81it/s]

 42%|████████████████▊                       | 709/1683 [00:10<00:13, 69.97it/s]

 43%|█████████████████                       | 717/1683 [00:10<00:13, 70.45it/s]

 43%|█████████████████▏                      | 725/1683 [00:10<00:13, 70.72it/s]

 44%|█████████████████▍                      | 733/1683 [00:10<00:13, 70.77it/s]

 44%|█████████████████▌                      | 741/1683 [00:10<00:13, 70.61it/s]

 45%|█████████████████▊                      | 749/1683 [00:10<00:13, 71.09it/s]

 45%|█████████████████▉                      | 757/1683 [00:10<00:12, 71.45it/s]

 45%|██████████████████▏                     | 765/1683 [00:10<00:12, 71.42it/s]

 46%|██████████████████▎                     | 773/1683 [00:10<00:12, 71.28it/s]

 46%|██████████████████▌                     | 781/1683 [00:11<00:12, 71.48it/s]

 47%|██████████████████▊                     | 789/1683 [00:11<00:12, 71.04it/s]

 47%|██████████████████▉                     | 797/1683 [00:11<00:12, 70.27it/s]

 48%|███████████████████▏                    | 805/1683 [00:11<00:12, 70.43it/s]

 48%|███████████████████▎                    | 813/1683 [00:11<00:12, 70.62it/s]

 49%|███████████████████▌                    | 821/1683 [00:11<00:12, 70.68it/s]

 49%|███████████████████▋                    | 829/1683 [00:11<00:12, 70.63it/s]

 50%|███████████████████▉                    | 837/1683 [00:11<00:11, 70.54it/s]

 50%|████████████████████                    | 845/1683 [00:11<00:11, 70.69it/s]

 51%|████████████████████▎                   | 853/1683 [00:12<00:11, 70.05it/s]

 51%|████████████████████▍                   | 861/1683 [00:12<00:11, 69.97it/s]

 52%|████████████████████▋                   | 868/1683 [00:12<00:11, 69.44it/s]

 52%|████████████████████▊                   | 876/1683 [00:12<00:11, 70.04it/s]

 53%|█████████████████████                   | 884/1683 [00:12<00:11, 70.21it/s]

 53%|█████████████████████▏                  | 892/1683 [00:12<00:11, 70.59it/s]

 53%|█████████████████████▍                  | 900/1683 [00:12<00:11, 70.26it/s]

 54%|█████████████████████▌                  | 908/1683 [00:12<00:11, 70.22it/s]

 54%|█████████████████████▊                  | 916/1683 [00:12<00:10, 70.55it/s]

 55%|█████████████████████▉                  | 924/1683 [00:13<00:10, 70.81it/s]

 55%|██████████████████████▏                 | 932/1683 [00:13<00:10, 71.05it/s]

 56%|██████████████████████▎                 | 940/1683 [00:13<00:10, 71.35it/s]

 56%|██████████████████████▌                 | 948/1683 [00:13<00:10, 70.53it/s]

 57%|██████████████████████▋                 | 956/1683 [00:13<00:10, 70.63it/s]

 57%|██████████████████████▉                 | 964/1683 [00:13<00:10, 70.78it/s]

 58%|███████████████████████                 | 972/1683 [00:13<00:10, 70.60it/s]

 58%|███████████████████████▎                | 980/1683 [00:13<00:10, 70.02it/s]

 59%|███████████████████████▍                | 988/1683 [00:13<00:09, 69.82it/s]

 59%|███████████████████████▋                | 995/1683 [00:14<00:09, 69.72it/s]

 60%|███████████████████████▏               | 1003/1683 [00:14<00:09, 70.14it/s]

 60%|███████████████████████▍               | 1011/1683 [00:14<00:09, 70.62it/s]

 61%|███████████████████████▌               | 1019/1683 [00:14<00:09, 70.51it/s]

 61%|███████████████████████▊               | 1027/1683 [00:14<00:09, 70.53it/s]

 61%|███████████████████████▉               | 1035/1683 [00:14<00:09, 70.52it/s]

 62%|████████████████████████▏              | 1043/1683 [00:14<00:09, 70.71it/s]

 62%|████████████████████████▎              | 1051/1683 [00:14<00:08, 70.81it/s]

 63%|████████████████████████▌              | 1059/1683 [00:14<00:08, 70.46it/s]

 63%|████████████████████████▋              | 1067/1683 [00:15<00:08, 70.09it/s]

 64%|████████████████████████▉              | 1075/1683 [00:15<00:08, 70.13it/s]

 64%|█████████████████████████              | 1083/1683 [00:15<00:08, 69.98it/s]

 65%|█████████████████████████▎             | 1091/1683 [00:15<00:08, 70.63it/s]

 65%|█████████████████████████▍             | 1099/1683 [00:15<00:08, 70.57it/s]

 66%|█████████████████████████▋             | 1107/1683 [00:15<00:08, 70.39it/s]

 66%|█████████████████████████▊             | 1115/1683 [00:15<00:08, 70.14it/s]

 67%|██████████████████████████             | 1123/1683 [00:15<00:08, 69.70it/s]

 67%|██████████████████████████▏            | 1130/1683 [00:15<00:07, 69.51it/s]

 68%|██████████████████████████▎            | 1137/1683 [00:16<00:07, 69.16it/s]

 68%|██████████████████████████▌            | 1145/1683 [00:16<00:07, 69.74it/s]

 69%|██████████████████████████▋            | 1153/1683 [00:16<00:07, 70.58it/s]

 69%|██████████████████████████▉            | 1161/1683 [00:16<00:07, 70.85it/s]

 69%|███████████████████████████            | 1169/1683 [00:16<00:07, 70.73it/s]

 70%|███████████████████████████▎           | 1177/1683 [00:16<00:07, 70.54it/s]

 70%|███████████████████████████▍           | 1185/1683 [00:16<00:07, 70.43it/s]

 71%|███████████████████████████▋           | 1193/1683 [00:16<00:06, 70.20it/s]

 71%|███████████████████████████▊           | 1201/1683 [00:16<00:06, 70.38it/s]

 72%|████████████████████████████           | 1209/1683 [00:17<00:06, 69.79it/s]

 72%|████████████████████████████▏          | 1216/1683 [00:17<00:06, 69.43it/s]

 73%|████████████████████████████▎          | 1224/1683 [00:17<00:06, 69.79it/s]

 73%|████████████████████████████▌          | 1232/1683 [00:17<00:06, 69.80it/s]

 74%|████████████████████████████▋          | 1239/1683 [00:17<00:06, 69.45it/s]

 74%|████████████████████████████▊          | 1246/1683 [00:17<00:06, 69.36it/s]

 75%|█████████████████████████████          | 1254/1683 [00:17<00:06, 70.23it/s]

 75%|█████████████████████████████▏         | 1262/1683 [00:17<00:05, 70.29it/s]

 75%|█████████████████████████████▍         | 1270/1683 [00:17<00:05, 70.09it/s]

 76%|█████████████████████████████▌         | 1278/1683 [00:18<00:05, 70.42it/s]

 76%|█████████████████████████████▊         | 1286/1683 [00:18<00:05, 70.53it/s]

 77%|█████████████████████████████▉         | 1294/1683 [00:18<00:05, 70.60it/s]

 77%|██████████████████████████████▏        | 1302/1683 [00:18<00:05, 70.20it/s]

 78%|██████████████████████████████▎        | 1310/1683 [00:18<00:05, 70.79it/s]

 78%|██████████████████████████████▌        | 1318/1683 [00:18<00:05, 70.35it/s]

 79%|██████████████████████████████▋        | 1326/1683 [00:18<00:05, 70.47it/s]

 79%|██████████████████████████████▉        | 1334/1683 [00:18<00:04, 70.16it/s]

 80%|███████████████████████████████        | 1342/1683 [00:19<00:04, 69.87it/s]

 80%|███████████████████████████████▎       | 1349/1683 [00:19<00:04, 69.64it/s]

 81%|███████████████████████████████▍       | 1357/1683 [00:19<00:04, 69.85it/s]

 81%|███████████████████████████████▋       | 1365/1683 [00:19<00:04, 70.22it/s]

 82%|███████████████████████████████▊       | 1373/1683 [00:19<00:04, 70.19it/s]

 82%|████████████████████████████████       | 1381/1683 [00:19<00:04, 70.44it/s]

 83%|████████████████████████████████▏      | 1389/1683 [00:19<00:04, 70.58it/s]

 83%|████████████████████████████████▎      | 1397/1683 [00:19<00:04, 70.56it/s]

 83%|████████████████████████████████▌      | 1405/1683 [00:19<00:03, 70.56it/s]

 84%|████████████████████████████████▋      | 1413/1683 [00:20<00:03, 70.80it/s]

 84%|████████████████████████████████▉      | 1421/1683 [00:20<00:03, 71.04it/s]

 85%|█████████████████████████████████      | 1429/1683 [00:20<00:03, 70.81it/s]

 85%|█████████████████████████████████▎     | 1437/1683 [00:20<00:03, 70.46it/s]

 86%|█████████████████████████████████▍     | 1445/1683 [00:20<00:03, 70.25it/s]

 86%|█████████████████████████████████▋     | 1453/1683 [00:20<00:03, 70.38it/s]

 87%|█████████████████████████████████▊     | 1461/1683 [00:20<00:03, 69.80it/s]

 87%|██████████████████████████████████     | 1469/1683 [00:20<00:03, 69.86it/s]

 88%|██████████████████████████████████▏    | 1476/1683 [00:20<00:02, 69.74it/s]

 88%|██████████████████████████████████▍    | 1484/1683 [00:21<00:02, 70.23it/s]

 89%|██████████████████████████████████▌    | 1492/1683 [00:21<00:02, 71.05it/s]

 89%|██████████████████████████████████▊    | 1500/1683 [00:21<00:02, 70.62it/s]

 90%|██████████████████████████████████▉    | 1508/1683 [00:21<00:02, 71.30it/s]

 90%|███████████████████████████████████▏   | 1516/1683 [00:21<00:02, 70.96it/s]

 91%|███████████████████████████████████▎   | 1524/1683 [00:21<00:02, 70.52it/s]

 91%|███████████████████████████████████▌   | 1532/1683 [00:21<00:02, 70.87it/s]

 92%|███████████████████████████████████▋   | 1540/1683 [00:21<00:02, 71.07it/s]

 92%|███████████████████████████████████▊   | 1548/1683 [00:21<00:01, 70.92it/s]

 92%|████████████████████████████████████   | 1556/1683 [00:22<00:01, 70.62it/s]

 93%|████████████████████████████████████▏  | 1564/1683 [00:22<00:01, 70.64it/s]

 93%|████████████████████████████████████▍  | 1572/1683 [00:22<00:01, 70.57it/s]

 94%|████████████████████████████████████▌  | 1580/1683 [00:22<00:01, 70.77it/s]

 94%|████████████████████████████████████▊  | 1588/1683 [00:22<00:01, 70.24it/s]

 95%|████████████████████████████████████▉  | 1596/1683 [00:22<00:01, 70.58it/s]

 95%|█████████████████████████████████████▏ | 1604/1683 [00:22<00:01, 69.85it/s]

 96%|█████████████████████████████████████▎ | 1612/1683 [00:22<00:01, 70.47it/s]

 96%|█████████████████████████████████████▌ | 1620/1683 [00:22<00:00, 70.34it/s]

 97%|█████████████████████████████████████▋ | 1628/1683 [00:23<00:00, 70.44it/s]

 97%|█████████████████████████████████████▉ | 1636/1683 [00:23<00:00, 70.89it/s]

 98%|██████████████████████████████████████ | 1644/1683 [00:23<00:00, 71.06it/s]

 98%|██████████████████████████████████████▎| 1652/1683 [00:23<00:00, 70.09it/s]

 99%|██████████████████████████████████████▍| 1660/1683 [00:23<00:00, 70.35it/s]

 99%|██████████████████████████████████████▋| 1668/1683 [00:23<00:00, 69.96it/s]

100%|██████████████████████████████████████▊| 1675/1683 [00:23<00:00, 69.66it/s]

100%|███████████████████████████████████████| 1683/1683 [00:23<00:00, 70.01it/s]

100%|███████████████████████████████████████| 1683/1683 [00:23<00:00, 70.59it/s]

  UAS: 0.8700
  LAS: 0.8529
  Total tokens: 33580 | Ignorados: 0
  Salvo em: ./predict_test_ablacao_linear_amadeusai_modernJabuticaBERT-Base-1k.csv

## Resumo final

In [18]:
print("\n" + "="*65)
print("ABLAÇÃO LINEAR — DEPREL + HEAD (sem UPOS) — Conjunto de Teste")
print("="*65)
print(f"{'Modelo':<42} {'UAS':>7} {'LAS':>7}")
print("-"*65)
for model_name, metrics in final_metrics.items():
    short = model_name.split('/')[-1]
    print(f"{short:<42} {metrics['uas']:>7.4f} {metrics['las']:>7.4f}")

# Salvar métricas finais
results_summary = [
    {"model": k, "uas": v["uas"], "las": v["las"],
     "total_tokens": v["total_tokens"], "architecture": "linear_ablacao_sem_upos"}
    for k, v in final_metrics.items()
]
pd.DataFrame(results_summary).to_csv("ablacao_linear_test_metrics.csv", index=False)
print("\nMétricas salvas em ablacao_linear_test_metrics.csv")

=================================================================
ABLAÇÃO LINEAR — DEPREL + HEAD (sem UPOS) — Conjunto de Teste
=================================================================
Modelo                                         UAS     LAS
-----------------------------------------------------------------
bert-base-multilingual-cased                0.9244  0.9081
bert-base-portuguese-cased                  0.9320  0.9191
bert-large-portuguese-cased                 0.9473  0.9352
modernJabuticaBERT-Base-1k                  0.8700  0.8529

Métricas salvas em ablacao_linear_test_metrics.csv